### ISSUE TITLE
V8Runtime.createV8ValueString() and V8Runtime.createV8ValueFloat()

### ISSUE THREAD

**Issue by newk5** [caoccao/Javet#10]
I noticed these 2 methods seem to be missing, is this intended or maybe something that was overlooked?

**Comment by caoccao** [comment]
Good question. They are primitive types that don't require V8Runtime to expose methods for creating new instances. Just go ahead and **new** them.

Tips: just search the Javet unit test, you will get recommended coding guidelines for all of them. Good luck!
