### ISSUE TITLE
Limit Access

### ISSUE THREAD

**Issue by Sundarcj** [caoccao/Javet#112]
Is it possible to limit JS Built in modules. Like Node VM does?
similar to [vm2](https://github.com/patriksimek/vm2).

**Comment by caoccao** [comment]
Javet has 2 modes.

## V8 Mode

There is no built-in modules. The script can only access what the application wants to expose in V8 mode.

## Node.js Mode

It's the genuine Node.js runtime. So, please feel free to leverage any existing Node.js virtualization techniques.

---

Hope that makes sense. Please let me know if you have any questions.

**Comment by Sundarcj** [comment]
Thank you @caoccao  will check
