### ISSUE TITLE
How to use FS module?

### ISSUE THREAD

**Issue by Tankonyako** [caoccao/Javet#115]
As I understand it, it can be used if its object is obtained through ```(v8 Runtime.get Node Module("fs", NodeModuleAny.class )```maybe (naturally I use V8Host.getNodeInstance().createv8runtime()), but via require('fs') in the script it doesn't work

**Comment by caoccao** [comment]
As we discussed offline, the fix is to use `execute()` instead of `executeString()`. Welcome to thinking in Javet.
