### ISSUE TITLE
@V8Function( name="get" ) doesn't seem to work properly

### ISSUE THREAD

**Issue by stephan-ansems** [caoccao/Javet#118]
Hi,

The following is a failed attempt to a workaround for [this issue](https://github.com/caoccao/Javet/issues/117)

Lets assume that some class `Registry`:
```java
public class Registry {
  @V8Function( name="get" )
  public function Entry fetch( String key ) {
    System.out.println( "call to Register.fetch( '"+key+"')" );
    // magic implementation
  } 

  // ...etc...
}
```

Then somewhere else in the code we bind the registry to a runtime:
```java
  // Create the registry and bind it to the runtime...
  Register registry = new Registry();
  try (V8ValueObject object = runtime.createV8ValueObject()) {
    result = runtime.getGlobalObject().set( "registry", registry );
    object.bind(registry);
  }
```

Then when executing the following `runtime.getExecutor("registry.get( 'some-key' );").executeString();`  results in the following error: `TypeError: registry.get is not a function'`.

**Comment by caoccao** [comment]
1. Don't name a function to `get`, it is reserved to a `Map` and the way to access the getter in JS is `a['key']`. Proxy converter is able to detect the getter and setter automatically.
2. When using proxy converter, you don't really need to bind anything. If you do both to the same Java object, please be prepared for unexcepted behaviors.

**Comment by caoccao** [comment]
The proxy converter hardcodes a special treatment for `get()` and `set()` in Java. So, if you don't have such Java methods, you are away from this.

**Comment by stephan-ansems** [comment]
Hi @caoccao,

I think you misunderstand and I appologize for the confusion I'm causing. I actually stumled on two things simultaneously and that is why this is happening. 

The actual bug (at least I think it is a bug) is that the `name` parameter in the `@V8Function` annotation does not seem to do anything. So in my previous post i used the name `retrieve`. I'd expect that the name `retrieve` would be the name under which the method would be accessible in javascript, however this is not the case.

Am I misinterpreting the use of the `name` parameter?

**Comment by caoccao** [comment]
So far `@V8Function` or `@V8Property` is not consumed by any converters. But, I plan to empower some converters with fine-grained control over the API exposed to V8 via such annotations. So, in the future, this will come true. You are welcome placing detailed requirements.

**Comment by caoccao** [comment]
#121 has been filed for this feature.

**Comment by stephan-ansems** [comment]
I'll close this then as it will be fixed in a near future release
