### ISSUE TITLE
@V8Function on methods named 'get' are invoked with names of other methods as argument

### ISSUE THREAD

**Issue by stephan-ansems** [caoccao/Javet#119]
Hi,

Still a big fan of this project ;-)

I noticed that Javet gets 'confused' when there is a method called `get` in the object that is being used in the scripting environment. Apparently this `get` method also gets invoked whit the name of the actual method that is being invoked prior to the invocation of the indented method. 

I've reduced the example to the bare essentials. Hope this saves you some time... 

The application contains a bean that implements a simple bookstore. This bean has a method `inStock( String isbn )` to check if a particular book is in stock or not:
```java
public class Bookstore() {
  @V8Function
  public boolean inStock( String isbn ) {
    System.out.println( "call Bookstore.inStock( '"+isbn+"')" ); // <- for debugging
    // ...finds the book on some shelf and then....
   return true;
  }

  // NOTE: The presence of the following method seems to confuse Javet...
  @V8Function
  public Book get( String isbn ) {
    System.out.println( "call Bookstore.get( '"+isbn+"')" ); // <- for debugging
    // ...well...
  }
}
```

The application exposes an endpoint at `{host:port}/checkStock` which expects a json-object that represents a book. The property we're after is accessible under `book.isbn`.

```java
public boolean checkInStockThroughJavaScript( String isbn ) {
  // Create a Bookstore object that magically connects to the database!
  Bookstore bookstore = new Bookstore(); 

  // Prepare the script...
  String script = "bookstore.inStock( '"+isbn+"' );";

  try (engine = pool.getEngine() ) {
    // Add the bookstore to the runtime...
    runtime.getGlobalObject().set( "bookstore", bookstore);

    // Run the script and return the result...
    return runtime.getExecutor( script )..executeBoolean();

    // ...etc...
  }
  // ...etc, i know i should have cleaned up the bookstore...
}
```

When i run this i see an odd logging line on the console:
```
call Bookstore.get( 'inStock' )
```
Note that the method name is used as the parameter.

I sure hope this isn't 'as designed'...

**Comment by caoccao** [comment]
As I replied in #118, when you use proxy converter, you don't really need `@V8Function`. Proxy converter has its own way of doing things.

The Java `get()` is mapped to JS getter by the proxy converter. So, there's no `get()` in JS anymore. If you really need `get()` in JS, don't use the proxy converter, but the default object converter, then bind it.

**Comment by stephan-ansems** [comment]
The patch in v1.0.6 does resolve this issue. Thanks @caoccao
