### ISSUE TITLE
Cannot create runtime : dll already loaded in another classloader

### ISSUE THREAD

**Issue by marcban** [caoccao/Javet#124]
Hello, 

I use Javet to run js build tools (eslint, babel...) in a maven plugin.

But when updating the project in eclipse, the maven plugin is reloaded and fails trying to create again the javet runtime with `V8Host.getV8Instance().createV8Runtime();` :

``Failed to read ....AppData\Local\Temp\javet\20964\libjavet-v8-windows-x86_64.v.1.0.5.dll - Native Library ...\AppData\Local\Temp\javet\20964\libjavet-v8-windows-x86_64.v.1.0.5.dll already loaded in another classloader``

I think this fails because the dll is in the main classloader, where as the plugin has its own classloader.
Is there another way of retrieving a runtime without reloading the dll ?

**Comment by caoccao** [comment]
Please refer to this [doc](https://www.caoccao.com/Javet/reference/resource_management/load_and_unload.html) for detail and let me know if it works or not.

**Comment by marcban** [comment]
thanks for the answer @caoccao 

for me the problem is that Eclipse unloads/and reloads the plugin classes without notice when I update the project
so its not possible for me to unload the natives before as in the doc.

After that I cannot retrieve the V8 runtime, as createV8Runtime throws an exception (V8Host class was also reloaded, so static variables are nullified)

comparing to j2V8 code, it seems they ignore the exception when loading the natives, and I can't figure another way of doing this ?

**Comment by marcban** [comment]
for info here is the code in j2V8

```
 private synchronized static void load(final String tmpDirectory) {
        try {
            LibraryLoader.loadLibrary(tmpDirectory);
            nativeLibraryLoaded = true;
        } catch (Error e) {
            nativeLoadError = e;
        } catch (Exception e) {
            nativeLoadException = e;
        }
    }
```
The error is saved, but the process continue

**Comment by caoccao** [comment]
Thank you for the info. Here are 2 options I could think of.

1. Hook the plug-in unload event to unload Javet.
2. Javet may expose a new API in `IJavetLibLoadingListener` to surpress this error.

**Comment by marcban** [comment]
1. unfortunately, there is no unload event in the maven plugin api or m2eclipse...
2. I think, in that case, that even Javet is not able to catch an event,  as the javet  classes are just reloaded without notice
(as eclipse creates a new classloader)
3. that's why I'm very embarassed: I can't figure out any other solution that ignoring the native loading exception for creating the runtime, although I must admit it's not a clean solution

**Comment by caoccao** [comment]
Vous inquiète pas. Je pense que l'option 2 devrait fonctionner.

Please stay tuned. Or join [discord](https://discord.gg/R4vvKU96gw) to discuss with me in detail.

**Comment by caoccao** [comment]
That was implemented in this [commit](https://github.com/caoccao/Javet/commit/df81526c5f4fa778ae0fa2f553375784b6d0b76a).

- Linux build is at [Github actions](https://github.com/caoccao/Javet/actions).
- Windows build is at [gdrive](https://drive.google.com/drive/folders/1VSFBCPD77jVTCC3qY-k82QQZVYp9WI36).

**Comment by caoccao** [comment]
@marcban Another group of Javet users just confirmed this feature works. Please take a try and let me know if it works or not.

**Comment by marcban** [comment]
thank you @caoccao , it works !!

**Comment by caoccao** [comment]
C'est très bien. Thank you for the update. Do you mind closing this issue?
