### ISSUE TITLE
undefined symbol: node_module_register

### ISSUE THREAD

**Issue by zbh876325764** [caoccao/Javet#126]
Hello, I have a problem. My node service contains a package of addon.node files. Here is the error message. How to solve it?
![image](https://user-images.githubusercontent.com/42517813/145149479-b5e06f5f-d6f4-4630-a3c4-6452727abec0.png)

**Comment by caoccao** [comment]
Which OS do you use? Mac OS?

**Comment by zbh876325764** [comment]
Ubuntu 20.04.2 LTS

**Comment by caoccao** [comment]
Please follow this [doc](https://www.caoccao.com/Javet/reference/resource_management/modularization.html#patch-elf-native-modules-on-linux) to patch the native modules, and let me if it works or not.

**Comment by zbh876325764** [comment]
> 

Thank you very much. I'll try it later

**Comment by zbh876325764** [comment]
> Please follow this [doc](https://www.caoccao.com/Javet/reference/resource_management/modularization.html#patch-elf-native-modules-on-linux) to patch the native modules, and let me if it works or not.

This solution can solve such problems. Thank you
