### ISSUE TITLE
Error in V8ValueUtils.concat

### ISSUE THREAD

**Issue by stephan-ansems** [caoccao/Javet#127]
In the method [`V8ValueUtils.concat( ... )`](https://github.com/caoccao/Javet/blob/main/src/main/java/com/caoccao/javet/utils/V8ValueUtils.java#L46) the `delimiter` parameter will never be used due to a logic error in the method. The variable [`first`](https://github.com/caoccao/Javet/blob/main/src/main/java/com/caoccao/javet/utils/V8ValueUtils.java#L58) must be set to `false` after appending the first value.

Also it would be more readable if the following code was used:
```java
   /**
     * Concatenates the v8Values array to a String.
     *
     * @param delimiter the delimiter
     * @param v8Values  the V8 values
     * @return the string
     * @since 0.7.1
     */
    public static String concat(String delimiter, V8Value... v8Values) {
        if (v8Values == null || v8Values.length == 0)  return EMPTY;
        if (delimiter == null) delimiter = EMPTY;
     
        return Arrays.stream(v8Values).collect( Collectors.joiner( delimiter ) );
    }
```

**Comment by caoccao** [comment]
Woops, that's a bug when the code was ported to Android. I'll fix it.

Your code doesn't work for Android:

1. Stream API is not available in JDK 1.6.
2. joiner is not available in JDK 1.6.

In order to support Android, the whole Javet code base was re-written in JDK 1.6 compatible way. That's why some API are so verbose.

**Comment by stephan-ansems** [comment]
Got it, Javet sticks to v1.6 then.

**Comment by caoccao** [comment]
Fixed in this [commit](https://github.com/caoccao/Javet/commit/891179ce529cf6fe3f75ffaab3db65e82ad8d07a). Thank you for reporting this bug.
