### ISSUE TITLE
Suggestion: optimize Android native library loading

### ISSUE THREAD

**Issue by ceclin** [caoccao/Javet#129]
Some app only include armeabi-v7a in apk to reduce size, but JavetLibLoader will call System.loadLibrary("javet-v8-android-arm64.v.1.0.6") on 64-bit machine.

On Android platform, I think native library name can be set to the same without os arch, such as "libjavet-v8-android.v.1.0.6.so".

**Comment by caoccao** [comment]
Good suggestion. I'll update it in the next release.

**Comment by caoccao** [comment]
It was committed to the dev branch. Please let me know if it works.

**Comment by ceclin** [comment]
It works. Thank you!
