### ISSUE TITLE
Can we compile scripts once and execute is multiple times?

### ISSUE THREAD

**Issue by pmg1991** [caoccao/Javet#133]

**Comment by caoccao** [comment]
Yes, that's true.

**Comment by pmg1991** [comment]
Any example?

**Comment by caoccao** [comment]
Would [this](https://github.com/caoccao/Javet/blob/main/src/test/java/com/caoccao/javet/values/reference/TestV8Script.java) help?

**Comment by pmg1991** [comment]
Can V8Script be serialized , so that even after JVM start stop , just deserialize the compiled scripts and run any script with Javet engine pool in multithread application.

**Comment by caoccao** [comment]
That's called snapshot. V8 supports taking snapshot, however Javet doesn't extend that capability to JVM as for now.
