### ISSUE TITLE
Incompatible with old glibc

### ISSUE THREAD

**Issue by tristanlins** [caoccao/Javet#137]
The javet native part is incompatible with older glibc versions.
When running on ubuntu 16.04 / 18.04 or centos 7 / 8 (which is equivalent to redhat enterprise linux), you got an `UnsatisfiedLinkError: /tmp/javet/86/libjavet-v8-linux-x86_64.v.1.0.7.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/javet/86/libjavet-v8-linux-x86_64.v.1.0.7.so)`.
I created a minimal hello world test and run it agains multiple linux versions:
https://gitlab.com/tristanlins/javet-compatibility-test/-/pipelines/445343180

As you can see, all dists older than ubuntu 20.04 are not compatible.

I run into very similar problem, with my [jsass library](https://gitlab.com/jsass/jsass).
I solved this by using [centos 7 in docker](https://gitlab.com/jsass/docker/build-jsass.compiler.libsass-linux-amd64/-/blob/main/Dockerfile#L1) to build the native library.

As far as I understand the build process, it should work to replace [ubuntu 20.04 in the dockerfile](https://github.com/caoccao/Javet/blob/main/docker/linux-x86_64/base.Dockerfile#L18) with an older / other distri.

**Comment by caoccao** [comment]
## GLIBCXX_3.4.26

Hope #26 be helpful to you.

## Ubuntu 16.04 / 18.04 / CentOS 7

Please refer to this [doc](https://www.caoccao.com/Javet/tutorial/basic/installation.html#linux). Basically, private builds are required. I haven't created private builds for almost 7 months. You are welcome trying the legacy builds and let me know if they work. Actually, some Javet users managed to have the legacy builds work successfully on those Linux distributions.

Building Javet on Ubuntu 16.04 is a different story. The dockerfile won't work. Even to me, I will have to spend tens of hours figuring out how to build the latest version on Ubuntu 16.04 nowadays.

**Comment by tristanlins** [comment]
Sorry, I missed the discussion (only searched for issues :see_no_evil: ).
I gave it a try and close this issue for now.

**Comment by caoccao** [comment]
No problem. I just submitted this [commit](https://github.com/caoccao/Javet/commit/e488fb7bf8384f87225cd91cd2980ebcd51f80a4) to the dev branch. Do you mind trying [it](https://github.com/caoccao/Javet/actions) in your env?

**Comment by tristanlins** [comment]
I will try out

**Comment by tristanlins** [comment]
Looks good: https://gitlab.com/tristanlins/javet-compatibility-test/-/pipelines/445405631

**Comment by caoccao** [comment]
Sorry, I'm not able to visit your project. Is it a private project? So, my last commit makes it work?

**Comment by tristanlins** [comment]
Oops, I missed the visibility when creating the project :see_no_evil: 
It is public now

**Comment by caoccao** [comment]
That looks nice.

**Comment by aoqilinjian** [comment]
hello @tristanlins, 
you demo test v8, did you try nodejs ?
