### ISSUE TITLE
GC not work in Android app, memory leak.

### ISSUE THREAD

**Issue by zjgg888** [caoccao/Javet#138]
v8Runtime.getGlobalObject().set("StringBuilder", StringBuilder.class);
v8Runtime.getExecutor("function main() {\n" +
  "var builder = new StringBuilder();\n" +
  "for (var i = 0; i < 1024; i++) builder.append('a');\n" +
  "}\n" +
  "for(var i = 0;i < 10000; i++){ main();}").executeVoid();

**Comment by caoccao** [comment]
There are 2 things you may work on.

1. Change `var` to `const`.
2. Expose GC in V8 via [V8Flags](https://github.com/caoccao/Javet/blob/main/src/main/java/com/caoccao/javet/interop/V8Flags.java). Thus, you may explicitly enforce GC in the JS code.

**Comment by zjgg888** [comment]
I've tried this:
V8Flags flags = V8Host.getV8Instance().getFlags();
flags.setExposeGC(true);
V8Host.getV8Instance().setFlags();
How to explicitly enforce GC in the JS code ?
Also, I think that it's best to be collected automatically by the engine.

**Comment by zjgg888** [comment]
My js executor might long-running within a while loop, and each loop will create some objects which takes too many memories, so I need this engine auto release(auto collect) theses objects I never used.
Somethis like this:
while (true) {
const largeObj = createLargeObjectFromJavaInterop(); //V8ValueObject created by v8Runtime and bind to Interceptor
//some code invoke largeObj
//largeObj will not be used in next loop, and sure not be referenced anymore, so it should be collect by GC automatically.
}

**Comment by caoccao** [comment]
You may increase the V8 heap size via V8Flags.

**Comment by caoccao** [comment]
Also, you may monitor the heap usage with this [guide](https://www.caoccao.com/Javet/reference/resource_management/memory_management.html).

![](https://www.caoccao.com/Javet/_images/statistics_v8_heap_space_statistics.png)
![](https://www.caoccao.com/Javet/_images/statistics_v8_heap_statistics.png)
![](https://www.caoccao.com/Javet/_images/statistics_v8_shared_memory_statistics.png)

**Comment by zjgg888** [comment]
I have tried gc() in each loop and it worked.
Thanks.

> There are 2 things you may work on.
> 
> 1. Change `var` to `const`.
> 2. Expose GC in V8 via [V8Flags](https://github.com/caoccao/Javet/blob/main/src/main/java/com/caoccao/javet/interop/V8Flags.java). Thus, you may explicitly enforce GC in the JS code.
