### ISSUE TITLE
could it be used in arm linux? e.g. respberry pi.

### ISSUE THREAD

**Issue by HexinAI** [caoccao/Javet#141]
could it be used in arm linux? e.g. respberry pi.

**Comment by caoccao** [comment]
I think that's possible. You are welcome taking a try.

**Comment by kozi** [comment]
Hi, I would like to try the Linux-ARM version.

Is it planned that *Linux arm64* will be included in a future release?

**Comment by caoccao** [comment]
Linux arm64 will be supported from Javet v3.

However Linux arm is another story as:

1. I don't have the hardware.
2. I expect someone to sponsor that work.
