### ISSUE TITLE
Long <-> BigInt issues

### ISSUE THREAD

**Issue by ceggert87** [caoccao/Javet#147]
Hello there!

I'm currently trying to migrate a project that previously used a multiple year old version of J2V8 and am currently stumbling upon an issue that is probably best described by the following example:

```
            try {
                val runtime: V8Runtime = V8Host.getV8Instance().createV8Runtime()
                val testLong = 5L
                val longNumber : Long = Integer.MAX_VALUE+1L
                runtime.globalObject.set("test", testLong)

                runtime.getExecutor("var resultequals = test === 5;").executeVoid()
                Log.d("TESTAPP", "${runtime.globalObject.get<V8Value>("resultequals")}")

                runtime.getExecutor("var resultequals2 = test === 5n;").executeVoid()
                Log.d("TESTAPP", "${runtime.globalObject.get<V8Value>("resultequals2")}")

                runtime.getExecutor("var largenumberscript = 2147483648").executeVoid()
                runtime.getExecutor("var largenumberscripttype = typeof largenumberscript").executeVoid()
                Log.d("TESTAPP", "${runtime.globalObject.get<V8Value>("largenumberscripttype")}")

                runtime.globalObject.set("largenumberobject", longNumber);
                runtime.getExecutor("var largenumberobjecttype = typeof largenumberobject").executeVoid()
                Log.d("TESTAPP", "${runtime.globalObject.get<V8Value>("largenumberobjecttype")}")

                runtime.getExecutor("var resultstringify = JSON.stringify(test);").executeVoid()
                Log.d("TESTAPP", "${runtime.globalObject.get<V8Value>("reultstringify")}")
            } catch (e: JavetException) {
                Log.e("TESTAPP", "$e")
            }
```
With the output being:
```
TESTAPP: false
TESTAPP: true
TESTAPP: number
TESTAPP: bigint
TESTAPP: com.caoccao.javet.exceptions.JavetExecutionException: TypeError: Do not know how to serialize a BigInt
```

So basically typical numerical checks and json conversions are not working out of the box as "Long" is automatically assigned to the BigInt type.

Is there any possibility to let Javet put them in as a numerical value (I think that would be Number?) instead so that the "classical checks" work again with those values?
Apologies if this is explained somewhere already and I just overlooked it.

E: Extended the example a bit to make the issue a bit more apparent - as far as I have seen the javet_converter.h specifically wants to turn Long into a BigInt, but wouldn't the numeric range of long be covered with Number already and the BigInt would basically only be necessary for extremely large BigInteger objects?

**Comment by caoccao** [comment]
The behaviors you observed belong to V8. Javet doesn't interfere with any of them.

You may verify them in Node.js or Chrome Dev Tools as following.

```js
> const a = 1
undefined
> const b = 1n
undefined
> a + b
Uncaught TypeError: Cannot mix BigInt and other types, use explicit conversions
> a == b
true
> a === b
false
> JSON.stringify(a)
'1'
> JSON.stringify(b)
Uncaught TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
```

If you are interested in why Javet cannot treat `int` and `long` the same, I can give you some insights. V8 stores `bigint` as `double` internally. V8 relies on an internal flag indicating whether that `double` is a `double` or a `bigint`. Javet reads that flag and casts the `double` to `long`.

As far as I know J2V8 doesn't support `bigint`, so the issue you placed seems to be a new thing in your migration. If you really want to get a JSON string from a V8 value. Here are 2 ways for your reference.

1. Call `JSON.stringify(value, replacer)` with a custom `replacer`. Please refer to this [doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) for detail.
2. Get a Java object from Javet. Convert that Java object to a JSON string via a JSON library (e.g. Jackson, Gson).

**Comment by ceggert87** [comment]
I tried to get behind this with J2V8 and made the following observations:
- Can't reproduce this in Kotlin, but in Java, for some reason, I was able to do V8Object.add("something", (Long) myLong) and it would actually jump into the method using double.
- By doing that, the logic seems to work, though there is some rounding going on (maybe it doesn't quite cover the range of Long?) 
```
                val myNumber = Long.MAX_VALUE
                (runtime as V8Object).add("test", myNumber.toDouble())
                runtime.executeVoidScript("var jsontest = JSON.stringify(test);")
                Log.d("TESTAPP", "Test: ${runtime.get("test")}")
                Log.d("TESTAPP", "Test: ${runtime.get("jsontest")}")
```
This leads to: 
```
TESTAPP: Test: 9.223372036854776E18
TESTAPP: Test: 9223372036854776000
```
Not quite sure where the rounding is coming from ((runtime.get("test") as Double).toLong() has the correct value), at least on the java level the Double max values does cover the Long max value. In any case, this would explain why everything worked perfectly with that engine. I suppose I could check for Long values and do double casts then, but if possible in any way it would be amazing if it could work as intuitive as in the Chrome browser without losing the format.

**Comment by caoccao** [comment]
As your sample code points out, precision is lost during the `long -> double -> long` conversion. This is not expected by the majority of Javet users. Many J2V8 users who complain that J2V8 doesn't support `bigint` eventually choose Javet because the `bigint` in Javet is genuine (Javet has zero tolerance to precision loss).

However, if you are still in favor of the way you did in J2V8, you can do the same in Javet as well. Just feed Javet API with `double` and get `double` from Javet, then perform the `long -> double` and `double -> long` conversion outside of Javet.

**Comment by ceggert87** [comment]
> As your sample code points out, precision is lost during the `long -> double -> long` conversion.

That's only the case in the JSON.stringify() method though, to which the alternative is a crash. In fact, Javascript in JSFiddle behaves the same when doing
```
  let test = 9223372036854775807;
  console.log(JSON.stringify(test));
```
The stringify has the rounding while calculations with that number are still perfectly fine. Personally I find it more odd that passing a System.currentTimeMillis() into the javascript will result in a different type than Javascript's Date.now() and as such fail at typesafe comparisons, and any objects containing a timestamp failing to be put into JSON as a result.

As I found my workaround, I won't bother with this anymore though and will close the ticket. Hope this issue helps in case anyone else stumbles upon this error :). Thanks for the quick responses.

**Comment by caoccao** [comment]
Please use the Javet API for `ZonedDateTime` which works perfectly with JS `Date`.

> Personally I find it more odd that passing a System.currentTimeMillis() into the javascript will result in a different type than Javascript's Date.now() and as such fail at typesafe comparisons, and any objects containing a timestamp failing to be put into JSON as a result.
