### ISSUE TITLE
Private runtime symbols exported by libjavet-node-linux-x86_64.v.1.1.0.so

### ISSUE THREAD

**Issue by uhees** [caoccao/Javet#151]
I ran a `nm -gDC libjavet-node-linux-x86_64.v.1.1.0.so` and found that lots of symbols from used libraries as well as runtime libs are exported. I expected only to see v8 related symbols there.

Is it possible to fix this, so that only relevant symbols are exported?

TL;DR

That being said, many thanks for Javet, which is IMHO a well thought piece of software.

We have the strange situation that as soon as we include Javet into out project another JNI based module sometimes behaves very strangely. My hypothesis is that the other module is picking up the c++ runtime symbols exported by Javet, which seem to produce an ABI break.

Personally I am using macOS where I have not seen this strange behaviour. On the other hand am I limited in debugging stuff on x86 Linux.

**Comment by caoccao** [comment]
Thank you for raising this issue. I thought it would be OK for Linux, so I left the following comment in the source code. I'll try to turn off those unnecessary symbols.

```cmake
# https://github.com/caoccao/Javet/blob/main/cpp/CMakeLists.txt

# Exported symbol filter is disabled unless production issues call for it.
# https://www.gnu.org/software/gnulib/manual/html_node/LD-Version-Scripts.html
# target_link_libraries(Javet PUBLIC -Wl,--version-script=${CMAKE_SOURCE_DIR}/jni/version_script.map)
```

Actually, those symbols are turned off for Mac OS. I think that's why everything works fine for your applications on Mac OS.

**Comment by uhees** [comment]
Thanks for pointing this out. I haven't noticed this comment. I now use the same technique to limit the exported symbols in a custom build of the other module.

So far I did not succeed in building Javet (more specific V8) on my M1 Mac, but I am willing to try again in my spare time.

**Comment by caoccao** [comment]
Sorry for my late response. Shanghai has been completely locked down for 2 weeks. People are running out of food and supply and this terrible situation is going to last at least another 1 or 2 months. I didn't have any mental strength to take care of this issue till now. I've tested this fix which was committed just now. You may try the snapshot build at [actions](https://github.com/caoccao/Javet/actions) and let me know if you have any questions.

Regarding the Mac OS version, I left my MBA 2012 in the office and as the lockdown goes, I won't be able to touch it to produce anything in 1 or 2 months. Also, as I don't have any M1 devices, any help from you is welcome. Donation might be the best for me and for this project. Thank you.
