### ISSUE TITLE
How to encrypt my script

### ISSUE THREAD

**Issue by sornian** [caoccao/Javet#155]
How to encrypt my script
can i use snapshot to encrypt my script

**Comment by caoccao** [comment]
May I know why you want to encrypt your script? There are plenty of solutions, I think.

Javet doesn't support V8 snapshot for now.

**Comment by sornian** [comment]
Do you have any good suggestions to encrypt script

**Comment by caoccao** [comment]
> Do you have any good suggestions to encrypt script

Sorry, I wouldn't want to leave suggestions where I'm not that familiar with. Could you google that?
