### ISSUE TITLE
Supporting sandbox

### ISSUE THREAD

**Issue by Flaer** [caoccao/Javet#162]
Hello. Does javet supports some sort of sandboxes? I know that sandoxes exits for rhino and nashorn engines.

**Comment by caoccao** [comment]
I'm not sure what you are looking for because Javet brings something different.

- Javet V8 mode is a pretty good sandbox because there is no net/fs/timer, etc.
- Javet Node.js mode has `vm` or `vm2` which are the standard sandbox solution.

Please let me know if I misunderstood your question.

**Comment by Flaer** [comment]
Thanks a lot. Its enough for me. You have done a good description of available options.
