### ISSUE TITLE
Not able to read the js file and node_modules from inside the jar

### ISSUE THREAD

**Issue by harshit3994** [caoccao/Javet#163]
Currently i am working on a project where i need to execute Node library inside the jdk.

![image](https://user-images.githubusercontent.com/15375422/174100736-37f5bf45-6e70-4b71-ad07-1fbf2c0880c3.png)

Is it possible to read a file path which is inside the resource folder in jar.What is the best way,because i can't keep js file and node_modules outside the jar.

**Comment by caoccao** [comment]
The practical way is to build a single JS file via any bundle tools, e.g. webpack, swc, etc. and read the resource content to a string via a resource loader.

**Comment by harshit3994** [comment]
I tried bundling the library via webpack but it seems webpack does'nt seem to polyfill fs node module.Tried with both webpack5(where we need to polyfill explicitly).All core modules were polyfilled except fs.

Please let me know your thoughts about polyfilling fs module.

**Comment by caoccao** [comment]
There is no need to polyfill any Node.js built-in modules. Javet Node.js mode supports fs.

**Comment by harshit3994** [comment]
Our node library uses the fs module.When bundling it with webpack,it throws the error
"Can't resolve fs module".When we tried by using 
 resolve: {
    fallback: {
      fs: false,
    },
  },

It worked fine.But when we executed the string(bundled js library),we are getting the following error.

![image](https://user-images.githubusercontent.com/15375422/174248492-0893ceb1-c5e3-46bb-88e5-94ed610f479c.png)

**Comment by caoccao** [comment]
Could you make sure the bundle target runtime is Node.js?

**Comment by harshit3994** [comment]
I tried by setting the runtime to node in webpack.Then it gave the following err
![image](https://user-images.githubusercontent.com/15375422/174259027-5289c1dc-2bd0-4da6-9999-32b990579a0c.png)

From articles on net i could relate it might be typescript version issue,downgraded it as well.Then my build with tsc is failing

**Comment by caoccao** [comment]
I think I can provide limited help without the source code in your hands. Basically, I recommend you to create a single JS file and have it run in Node.js successful before trying it in Javet. Javet Node.js mode is a genuine Node.js runtime that has zero difference from the actual Node.js.

**Comment by harshit3994** [comment]
Thanks @caoccao for the help so far.

**Comment by harshit3994** [comment]
Since this issue is much related to webpack bundling.I am closing the issue

**Comment by harshit3994** [comment]
@caoccao can we bundle node_modules as well via webpack.From some articles on net,it is not recommended to include node_modules in bundle for backend apps Ref-
https://archive.jlongster.com/Backend-Apps-with-Webpack--Part-I

PS- When tried bundling without node_modules library seems to be working fine on Nodejs environment.But as a single file it doesn't works

**Comment by caoccao** [comment]
According to your specific requirement, you don't want your Java applications to access any physical folders other than the resources under classpath. Unfortunately, that resources folder is located inside the jar files and cannot be accessed by regular OS file API which is used by Node.js fs module. That leaves you no option other than packaging the whole node_modules in a mega JS file.

A less annoying approach would be:
1. Embed the whole node_modules folder in the jar file.
2. Extract the node_modules from the jar file to a temp location when the application is being initialized.
3. Point the Node.js to that temp location.

**Comment by harshit3994** [comment]
@caoccao Thanks for the inputs,with https://www.npmjs.com/package/@vercel/ncc we resolved the bundling issue.But when we were running this bundled js file it is giving the below javet exception error.

__dirname is not defined.Attaching the screenshot for reference
![image](https://user-images.githubusercontent.com/15375422/174550732-93c2b72a-c827-4e73-8e44-979f539f71e3.png)

**Comment by harshit3994** [comment]
![image](https://user-images.githubusercontent.com/15375422/174551460-89da1086-1bdc-4af9-88af-1f053153f19a.png)

**Comment by harshit3994** [comment]
Solution which is recommended in the doc is to set the __dirname directly.But again the question here is how we can get the path of js(__dirname) file which is inside the jar.

**Comment by caoccao** [comment]
You don't need to set anything addressing a location in the JAR file. Just point it anywhere and Node.js will accept that because V8 doesn't have file system access and only needs the resource path for error messages.
