### ISSUE TITLE
Version error of dylib in macos

### ISSUE THREAD

**Issue by wuruofeng** [caoccao/Javet#165]
Hello～
I have a library that contains Javet and deploy it to maven's private repository, here is its pom.xml:

        <dependency>
            <groupId>com.caoccao.javet</groupId>
            <artifactId>javet</artifactId>
            <version>1.1.5</version>
        </dependency>

        
        <dependency>
            <groupId>com.caoccao.javet</groupId>
            <artifactId>javet-macos</artifactId>
            <version>1.1.0</version>
        </dependency>

My question is that when I use this library in my mac environment, the Javet seems to found the wrong version of the dylib

console shows "Javet library /libjavet-v8-macos-x86_64.v.1.1.5.dylib is not found"

Obviously, the mac environment version should be 1.1.0 instead of 1.1.5

where goes wrong?

![image](https://user-images.githubusercontent.com/40079245/179653894-8a3d6125-4603-48c0-83b7-9c453d3574cc.png)
![image](https://user-images.githubusercontent.com/40079245/179653942-3df5d623-ec96-47dc-8af2-eed29b99b640.png)
![image](https://user-images.githubusercontent.com/40079245/179654012-8b7e7526-f1e4-405b-a037-7777e831e4ef.png)

**Comment by caoccao** [comment]
In general, you need to create multiple profiles which apply different set of config per OS. The pom.xml you posted only loads the first library which is v1.1.5. The second library is refused by JVM.

Please refer to this [sample](https://github.com/caoccao/Javenode/blob/main/pom.xml) for detail.

**Comment by gaberogan** [comment]
I am getting this error as well for version 3.0.2, which versions are compatible with macos?

**Comment by caoccao** [comment]
Please check this [doc](https://www.caoccao.com/Javet/tutorial/basic/installation.html) out. All versions are compatible with MacOS.
