### ISSUE TITLE
Error loading lodash

### ISSUE THREAD

**Issue by Aricgit** [caoccao/Javet#17]
have exception  when i use runtime.executeScript load lodash.js .  i want add lodash library in javet runtime

**Comment by caoccao** [comment]
Which mode did you use? Node.js or V8?

I wonder `executeScript` is a J2V8 API. In Javet, it's different. Usually, that's `v8Runtime.getExecutor(PathToLodash).executeVoid()`.

**Comment by Aricgit** [comment]
thanks for your reply 。


Before I used j2v8, lodash can be loaded, I want to replace it with jawet, because jawet supports multi-threaded use.


The attachment is my test process, the following exception will be reported




On 4/13/2021 14:04，Sam ***@***.***> wrote：

Which mode did you use? Node.js or V8?

I wonder executeScript is a J2V8 API. In Javet, it's different. Usually, that's v8Runtime.getExecutor(PathToLodash).executeVoid().

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
package com.skybird.edge.base.controlling.enginee;

import com.caoccao.javet.interop.engine.IJavetEngine;
import com.caoccao.javet.interop.engine.JavetEngineConfig;
import com.caoccao.javet.interop.engine.JavetEnginePool;
import com.caoccao.javet.values.primitive.V8ValueUndefined;
import com.skybird.edge.base.utils.FileUtils;

import java.io.File;

public class J2V8EngineeTest {

    public static void main(String[] args) {
        String path = "C:\\project\\skybird_edge3\\src\\main\\java\\com\\skybird\\edge\\addons\\web\\lib\\lodash\\lodash.js";

        try {
            JavetEngineConfig config = new JavetEngineConfig();
            config.setPoolDaemonCheckIntervalMillis(1);
            JavetEnginePool pool = new JavetEnginePool();
            IJavetEngine engine = pool.getEngine();
            Object lodashGet = engine.getV8Runtime().getGlobalObject().get("_.get");
            if (lodashGet instanceof V8ValueUndefined) {
                /*lodash lodash into pool engine*/
                String str = FileUtils.readFileToString(new File(path));
                engine.getV8Runtime().getExecutor(str).executeVoid();
            }

            engine.close();
        } catch (Exception e) {
            e.printStackTrace();
        }


    }
}

**Comment by Aricgit** [comment]
![image](https://user-images.githubusercontent.com/9571096/114506294-27016e80-9c64-11eb-8b6a-592e7a9a9dbd.png)

**Comment by caoccao** [comment]
In Javet, `eval()` is disabled by default for security reason. You may enable it by calling `com.caoccao.javet.interop.V8Runtime#allowEval`.

**Comment by Aricgit** [comment]
Thank you very much， is ok！
