### ISSUE TITLE
Reference to V8Runtime survives call to `V8Runtime#close()`

### ISSUE THREAD

**Issue by tiwoc** [caoccao/Javet#174]
Running the following test throws a runtime leakage exception:

```kotlin
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.caoccao.javet.interop.V8Host
import com.caoccao.javet.interop.V8Runtime
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class LeakTest {
    @Test
    fun testRuntime() {
        val v8Host = V8Host.getV8Instance()
        val v8Runtime = v8Host.createV8Runtime<V8Runtime>()
        v8Runtime.close()
        v8Host.close()
    }
}
```

Exception thrown:

```
com.caoccao.javet.exceptions.JavetException: 1 runtime(s) leakage is detected
	at com.caoccao.javet.interop.V8Host.close(V8Host.java:195)
```

I think that the reason for this lies in line 212 of V8Host.java:

https://github.com/caoccao/Javet/blob/2025548d87f68fe963d31dec27d25604a76a90f1/src/main/java/com/caoccao/javet/interop/V8Host.java#L206-L217

`INVALID_HANDLE` is `0L`, but the handle in this case is smaller than zero, which means that the runtime isn't removed from the map.

I would have posted a PR that makes the `>` a `!=` if I had the V8 build environment set up to test it, but I hope this description makes it an easy fix.

**Comment by caoccao** [comment]
Thank you for reporting this. It's interesting that the handle could be negative in some Android environments.

You are welcome submitting a PR to the dev branch. Cheers!

**Comment by caoccao** [comment]
It was fixed by this [commit](https://github.com/caoccao/Javet/commit/65554031b1a2eade7f22a1930d2966ab48f00ab5).

**Comment by tiwoc** [comment]
Thank you! I can't test this unfortunately because I wasn't successful in setting up the build environment, but the change looks good to me.

**Comment by tiwoc** [comment]
I can confirm that Javet 1.1.7 fixes this issue. Thanks again!
