### ISSUE TITLE
Using `isSuppressingError` forces me to implement `getLibPath` as well

### ISSUE THREAD

**Issue by kozi** [caoccao/Javet#175]
```java
JavetLibLoader.setLibLoadingListener(new IJavetLibLoadingListener() {
    @Override
    public boolean isSuppressingError(JSRuntimeType jsRuntimeType) {
        return true;
    }
});
```

If I add [this example code](https://www.caoccao.com/Javet/reference/resource_management/load_and_unload.html#can-already-loaded-in-another-classloader-be-suppressed) to my project I have to implement the method `getLibPath` as well because the default implementation in the interface returns null.

**Comment by caoccao** [comment]
It's up to you to decide to either create a listener or set an env var to tell Javet to suppress that error. In you case, I would suggest you to set env var `javet.lib.loading.suppress.error=true` during the application initialization.
