### ISSUE TITLE
For for Map

### ISSUE THREAD

**Issue by PyXiion** [caoccao/Javet#176]
Hello. I tried to use Map in a for-loop
```js
let keySet = map.keySet();
// doesn't work
for (let key of keySet) {
  // ... 
}
// doesn't work
for (let key in keySet) {
  // ... 
}
```
I have set all the necessary parameters
```java
javetProxyConverter.getConfig().setProxyMapEnabled(true);
javetProxyConverter.getConfig().setProxySetEnabled(true);
```
Map object
```java
Map<String, Object> map = new HashMap<>() {{
                put("x", 1);
                put("y", 2);
            }};
```

How can I do this?

**Comment by PyXiion** [comment]
I removed
javetProxyConverter.getConfig().setProxyMapEnabled(true);
javetProxyConverter.getConfig().setProxySetEnabled(true);
And everything worked
But I don't have access to .keySet(). I need for-loop for Map, and .keySet(). How to do it?

**Comment by caoccao** [comment]
Have you tried the bridge converter?

The proxy converter tries to apply JS native array, set, object to the Java counterparts so that getting both JS and Java behaviors altogether is very challenging. But, you can polyfill the JS object with the Java API.
