### ISSUE TITLE
Singe-characted method doesn't work

### ISSUE THREAD

**Issue by PyXiion** [caoccao/Javet#177]
Hello. The method with a single-character name does not work for me. I use a proxy converter. The method itself is available in the object.
JS code
![Screenshot_20220806_133130](https://user-images.githubusercontent.com/59997570/183245240-6b029ba5-57e3-4cd1-9da7-97ea9209e718.png)
Error
![Screenshot_20220806_133115](https://user-images.githubusercontent.com/59997570/183245262-c4d0b01e-caa6-4755-a69b-54ed13d8dba2.png)
rxy method returns this.
Therefore, there are no errors without the w methoв
![Screenshot_20220806_133151](https://user-images.githubusercontent.com/59997570/183245305-43c8dd57-4474-44cb-8058-f1cebb38a10f.png)
I tried to look in the source code for a place where single-character methods may be processed, but I didn't find this :(

rxy
![Screenshot_20220806_133826](https://user-images.githubusercontent.com/59997570/183245412-77270e49-2356-40aa-ab81-bb1c4adbcd68.png)
![Screenshot_20220806_133854](https://user-images.githubusercontent.com/59997570/183245421-8bd5c761-0b6b-458b-83af-28fe2f596bc1.png)
![Screenshot_20220806_133912](https://user-images.githubusercontent.com/59997570/183245434-e9a2afa6-2112-4210-aea1-332667661649.png)
And w.
![Screenshot_20220806_133942](https://user-images.githubusercontent.com/59997570/183245458-0b73999f-792f-4c74-bdfc-ed63a2e7ef53.png)
They are all in the same class and object
I don't understand what I'm doing wrong.

**Comment by caoccao** [comment]
There is nothing special for single-char functions. I'll check it out later.

**Comment by PyXiion** [comment]
Sorry, I'm not very smart
![Screenshot_20220806_200920](https://user-images.githubusercontent.com/59997570/183259039-2b9b39e0-e49f-4e66-ad18-ab1c2c99f9db.png)
![Screenshot_20220806_200942](https://user-images.githubusercontent.com/59997570/183259040-0f3175c1-26fa-4f17-816e-209459c5803f.png)

**Comment by PyXiion** [comment]
Will it work if I put on @Setter methods?  I'm going to try

**Comment by PyXiion** [comment]
Although it probably won't work:(

**Comment by PyXiion** [comment]
Yes, it can't be done
