### ISSUE TITLE
Reduce Javet size

### ISSUE THREAD

**Issue by PyXiion** [caoccao/Javet#178]
Can I reduce Javet size? Remove the Node.js and other unused components...

**Comment by caoccao** [comment]
Yes, please check this [doc](https://www.caoccao.com/Javet/reference/resource_management/load_and_unload.html) out.

**Comment by PyXiion** [comment]
Thanks

**Comment by blsites** [comment]
@caoccao how can we reduce the packaged apk size for android? It's now 200mb overhead
