### ISSUE TITLE
Transfer globalObject

### ISSUE THREAD

**Issue by PyXiion** [caoccao/Javet#184]
Can I transfer global objects from one V8Runtime to another? I have an array of V8Runtime and I want to make interaction between them
Like this:
```java
@Override
public V8Value require(String scriptId) throws JavetException {
    return Mappet.scripts.getUnique(scriptId).getEngine().getGlobalObject();
}
```
```js
let otherScript = require('otherScriptId'); // works
let someVar = otherScript.someVar; // does not work
```
How can I get globalObject as V8Value?

**Comment by caoccao** [comment]
The global object is a V8Value, but it cannot be shared among multiple V8Runtime instances. The only possible way seems to be using snapshot data. Javet doesn't support that feature to reduce the binary size.

**Comment by PyXiion** [comment]
It did work out
![Screenshot_20220822_225350](https://user-images.githubusercontent.com/59997570/186007133-11bb878c-5b46-43c4-85c1-085f885d0357.png)

```java
public class GlobalObjectWrapper {
    protected V8Runtime engine;

    public GlobalObjectWrapper(V8Runtime engine) {
        this.engine = engine;
    }

    public V8Value get(String name) throws JavetException {
        System.out.println("Getter");
        return engine.getGlobalObject().get(name);
    }

    public void set(String name, Object value) throws JavetException {
        System.out.println("Setter");
        engine.getGlobalObject().set(name, value);
    }
}
```
```java
public GlobalObjectWrapper require() throws JavetException {
        return new GlobalObjectWrapper(this.global);
}
```

**Comment by caoccao** [comment]
The proxied Java object is able to almost anything with excellent performance. Yes, in your case, you can let one V8 runtime interact with another V8 runtime.
