### ISSUE TITLE
Does using enginePool cause memory leaks？

### ISSUE THREAD

**Issue by Aricgit** [caoccao/Javet#19]
I need to run v8runtime 100~1000 per second, use enginepool to initialize the instance, and load the lodash library in each v8runtime. When running at full speed, the console has a lot of warnings.
 I have 2 questions: 
1. Will continuous operation cause memory leaks? 
2. How to release these objects in time?

![image](https://user-images.githubusercontent.com/9571096/114639842-65993680-9d01-11eb-9232-d5adc226a02b.png)

![image](https://user-images.githubusercontent.com/9571096/114640203-27e8dd80-9d02-11eb-919f-cdac340e09bc.png)

**Comment by caoccao** [comment]
Please read https://github.com/caoccao/Javet/blob/main/docs/tutorial/memory_management.rst very carefully and apply `try-with-resource`.

In your code, you need to wrap `lodashGet`. Usually, people from J2V8 need some time to get used to the Javet coding style.

``` java
try (V8Value lodashGet = ...) {
    if (lodashGet.isUndefined()) {
        // ...
    }
}
```
