### ISSUE TITLE
js内用java对象与字符串进行拼接操作后结果异常

### ISSUE THREAD

**Issue by goldenduo** [caoccao/Javet#191]
```js
let javaobj= ...  //调用java返回java对象
console.log(javaobj)
console.log("fff"+javaobj)
```
输出结果：
```
{x:92,y:229,width:133,height:73}
fffundefined
```
请问有没有workaround

**Comment by goldenduo** [comment]
<img width="284" alt="image" src="https://user-images.githubusercontent.com/46618424/192928675-85d5cb79-74b1-44d4-8d95-924f7abc615b.png">
这是chrome的结果，如果不能直接显示javaobj的toString方法，能显示这样也行。至少不是undefined这么迷惑的结果。

**Comment by caoccao** [comment]
I think that is a feature not implemented yet.

**Comment by caoccao** [comment]
It has been implemented by this [commit](https://github.com/caoccao/Javet/commit/5f159f453d2c25258d76d52ce23150911cf7dd69) and will be included in the next release.
