### ISSUE TITLE
How do I differentiate an exception caused by the throw keyword on the javascript side?

### ISSUE THREAD

**Issue by jcrabanal** [caoccao/Javet#204]
```
function testThrow() {
    throw "Something";
}
```

Hello again. This js code generates a JavetExecutionException. Is it possible to check if this exception is caused by a explicit throw in the javascript side? Or is there any other way to do it? Can I get the thrown object on the java side?

**Comment by caoccao** [comment]
Yes, you can get a `JavetScriptingError` from the `JavetExecutionException`. There is a `context` object in `JavetScriptingError` for you to transfer anything from JS to Java. E.g.

```js
// In JS
throw { a: 1, b: 2}
```

```java
// In Java
e.getScriptingError().getContext().get("a");
e.getScriptingError().getContext().get("b");
```

**Comment by caoccao** [comment]
Why would you want to throw a primitive value? It's recommended to throw an error. E.g.

```js
throw Object.assign(new Error(), { a: 1, b: 2 });
```

**Comment by jcrabanal** [comment]
I know, but it's untrusted code running on an app framework. I'd still like to retrieve the thrown object whatever it may be.

After all, this is just so I can do a decent toString() and pass safe and detailed stuff to an error handler.

**Comment by caoccao** [comment]
I wonder if you could catch that error, put the error in an object, re-throw that object.

**Comment by jcrabanal** [comment]
I thought about it, but I saw later that the JavetScriptingError constructor takes the V8Value and that you did some type conversion for V8ValueError and V8ValueObject.

I've added code for converting V8ValuePrimitive:

```
} else if (v8Value instanceof V8ValuePrimitive) {
    V8ValuePrimitive<?> v8ValuePrimitive = (V8ValuePrimitive<?>) v8Value;
    Object value = v8ValuePrimitive.getValue();
    String sValue = value != null ? value.toString() : "";
    detailedMessage = sValue;
    message = sValue;
    stack = "";
}
```
Works for me!
