### ISSUE TITLE
How to implement delay function in  V8 mode?

### ISSUE THREAD

**Issue by goldenduo** [caoccao/Javet#206]
`delay` is different from `sleep` , `delay` will not block js ui thread but only stop a while and prevent processing the next line of code. It is possible to execute js or get callback when delaying. 
  Is there any api to hangup v8 to implement `delay` function in V8 mode?

**Comment by caoccao** [comment]
Please check out the project Javenode developed by me. It has a standard implementation.

**Comment by goldenduo** [comment]
I've looked at that project but don't find it helpful. That project has no code that suspends the execution of v8, it just does a delayed callback.

**Comment by goldenduo** [comment]
I've found sth.Thanks.
```js
v8ValuePromiseResolver = getEventLoop().getV8Runtime().createV8ValuePromise();
if (recurrent) {
    timerId = getEventLoop().getVertx().setPeriodic(delay, id -> {
        if (!isClosed()) {
            if (resolve) {
                try {
                    v8ValuePromiseResolver.resolve(v8ValueResult);
                } catch (Throwable t) {
                    getLogger().logError(t, "Failed to resolve the promise.");
                }
            } else {
                try {
                    v8ValuePromiseResolver.reject(v8ValueResult);
                } catch (Throwable t) {
                    getLogger().logError(t, "Failed to reject the promise.");
                }
            }
        }
    });
```

**Comment by goldenduo** [comment]
I found another problem: how to call the keyword `await` of js in Java.
I want to implemnt `delay` in the way below
```js
delay()
```
rather than
```js
await delay()
```

**Comment by caoccao** [comment]
Just hook the JS call and sleep in Java.

**Comment by goldenduo** [comment]
I don't understand.How to avoid using `await` by hooking the JS?

**Comment by caoccao** [comment]
Please check this [doc](https://www.caoccao.com/Javet/tutorial/basic/interception.html) out.

**Comment by goldenduo** [comment]
Java Code:
```java
void delay(){
     v8Runtime.getExecutor("await java.delayWithPromise()").executeVoid();
}
V8ValuePromise delayWithPromise(){
    //worker thread sleep and return promise
}
```
JS code:
```js
delay()
```
Is this what you mean? I think it's terrible if it's in the case of many complex functions.

**Comment by caoccao** [comment]
Why would you want to use `Promise`? Please follow the doc. Just call `TimeUnit.SECONDS.sleep()` in Java.

**Comment by goldenduo** [comment]
I dont want to block the V8 main thread. `delay` is different from `sleep` .

**Comment by goldenduo** [comment]
If `sleep`, will it work when call  `executeVoid()` in other thread?

**Comment by caoccao** [comment]
JS is single-threaded. Please always keep that in mind. Only one thread can take over the control of V8. You have 2 choices.

1. Force that thread to sleep.
2. Fork a new thread via `Promise` and `await` that `Promise`.

**Comment by goldenduo** [comment]
So that‘s why I want to use `Promise`,but it seems no way to implement `delay()`  but `await delay()` work.

**Comment by caoccao** [comment]
That question belongs to TC39, I think.
