### ISSUE TITLE
does the NodeModuleModule.setRequireRootDirectory method support to set a path that in jar file resource folder?

### ISSUE THREAD

**Issue by luojh** [caoccao/Javet#21]
my nodejs scripts are in the resource folder, and the app run as a jar file.

the code just like:
`
Path nodeModulesRoot = new PathMatchingResourcePatternResolver().getResource("classpath:/node/node_modules").getFile().toPath();
nodeRuntime.getNodeModule(NodeModuleModule.class).setRequireRootDirectory(nodeModulesRoot);`

an then we get the error:
java.io.FileNotFoundException: class path resource [node/node_modules] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/app.jar!/BOOT-INF/classes!/node/node_modules

**Comment by caoccao** [comment]
Good question.

1. This feature is limited by Node.js runtime for security reason. Once a Node.js host process starts, Node.js runtime doesn't allow setting the working directory out of the initial working directory. Obviously, this is to prevent scripts attacking the runtime environment.
2. Also, Node.js runtime also requires the directory to be an actual folder in the file system. That results the error you met.

My suggestion is to resolve the path so that it becomes the one recognized by Node.js runtime.

**Comment by luojh** [comment]
i get it, thank you !

**Comment by Quixomatic** [comment]
> Good question.
> 
> 1. This feature is limited by Node.js runtime for security reason. Once a Node.js host process starts, Node.js runtime doesn't allow setting the working directory out of the initial working directory. Obviously, this is to prevent scripts from attacking the runtime environment.
> 2. Node.js runtime also requires the directory to be an actual folder in the file system. That results in the error you met.
> 
> My suggestion is to resolve the path so that it becomes the one recognized by Node.js runtime.

Sorry for my lack of understanding. What do you mean by resolve the path? I bundled my entire nodejs project into a single dist folder. Was hoping to access that without ever having to leave the JAR file. Everything I have tried so far has failed. Is there any way to access folders in the JAR?

**Comment by caoccao** [comment]
Node.js is keen on real (aka physical) file system path. The file path inside a jar file is not a physical file path from OS perspective. The app has to copy everything to a physical path and point the working dir to it.

**Comment by Quixomatic** [comment]
> Node.js is keen on real (aka physical) file system path. The file path inside a jar file is not a physical file path from OS perspective. The app has to copy everything to a physical path and point the working dir to it.

Is there a way for a JAR to move its contents to a physical folder on the server automatically when it is run? I know this question isn't really specific to your library.

**Comment by caoccao** [comment]
I would put everything into one zip file and unzip that file to somewhere physical.
