### ISSUE TITLE
Another simple use case as #205 but with ES6

### ISSUE THREAD

**Issue by sanke69** [caoccao/Javet#210]
Hi again Sam,

I try to adapt the solution from #205 to get it works with an ES6 Module and it is not quite easy to understand how to do it...

I have read 
[Modularization - Javet 2.0.2 documentation](https://www.caoccao.com/Javet/reference/resource_management/modularization.html)

But it mainly deals with DIY modules or external modules...

Here is my module, another way to start a server but in a ES6 way:

```javascript
import * as http from 'node:http';

const config = { port : 8080, hostname : "localhost" };

var server = http.createServer();

server.on("request",   onServerRequest);
server.on('error',     onServerIssue);
server.on('listening', onServerListening);

function onServerRequest(req, res) {
    res.writeHead(200, { 'Content-Type':'text/html' });
    res.end( "<html><body><h1>It Works!</h1></body></html>" );
}
function onServerListening() {
    var addr = server.address();
    var bind = typeof addr === 'string' ? ' [UNIX]' : '';
    var host = server.address().address;
    var port = server.address().port;

    host = host === '::' || host === '127.0.0.1' ? 'localhost' : host;

    console.log(`Server is running on http://${host}:${port} ${bind}`);
}
function onServerIssue(error) {
    console.error({error});
}


function startServer() {
    server.listen(config.port, config.hostname);
}

function stopServer() {
    server.close();
}
```

 and my last attempt in Java:

```java
IV8Executor v8exec = nodeRuntime.getExecutor(main_script);
// nodeRuntime.getNodeModule(NodeModuleModule.class).setRequireRootDirectory(local_relative_path);
v8exec.setModule(true);
v8exec.executeVoid();
nodeRuntime.getGlobalObject().invokeVoid("startServer");
```

Just add the `v8exec.setModule(true);`

and it returns :
`JavetExecutionException: Error: Cannot find package 'node:http'`

which is an internal node module.

My question is simple, how to get the module find internal NodeJS module ?

Thanks in advance ;)

**Comment by caoccao** [comment]
The Node.js internal resolver has been disabled. I think it can be set as a fallback solution.
