### ISSUE TITLE
Tests failed on Android

### ISSUE THREAD

**Issue by ceclin** [caoccao/Javet#211]
@Miaow233 and I tried building node on Android. Here is [build result](https://github.com/ceclin/build-javet-node-android/actions/runs/3604627527).

Then, we tried running unit tests on Android devices as following steps:
1. Install Termux App
2. Install git and gradle on Android
3. Git clone Javet and check out the main branch (currently v2.0.2)
4. Copy shared native libraries to src/main/resources (just for [library loading](https://github.com/caoccao/Javet/blob/daf71f4551d22bc8feb6d0f1349db811de635cce/src/test/java/com/caoccao/javet/BaseTestJavet.java#L53))
5. Run `./gradlew test`

Interestingly, tests also failed with v8 mode (libjavet-v8-android.v.2.0.2.so in javet-android-2.0.2.aar is used), so it seems not a problem specific to node mode.

It seems all failure points are related to V8RuntimeCount checks.

All tests passed after I commented following lines:
- [BaseTestJavetRuntime.java#L47](https://github.com/caoccao/Javet/blob/daf71f4551d22bc8feb6d0f1349db811de635cce/src/test/java/com/caoccao/javet/BaseTestJavetRuntime.java#L47)
- [BaseTestJavetRuntime.java#L56](https://github.com/caoccao/Javet/blob/daf71f4551d22bc8feb6d0f1349db811de635cce/src/test/java/com/caoccao/javet/BaseTestJavetRuntime.java#L56)
- [TestNodeRuntime.java#L56](https://github.com/caoccao/Javet/blob/daf71f4551d22bc8feb6d0f1349db811de635cce/src/test/java/com/caoccao/javet/interop/TestNodeRuntime.java#L56)
- [BaseTestJavetPool.java#L35](https://github.com/caoccao/Javet/blob/daf71f4551d22bc8feb6d0f1349db811de635cce/src/test/java/com/caoccao/javet/BaseTestJavetPool.java#L35)
- [TestJavetEnginePool.java#L68](https://github.com/caoccao/Javet/blob/daf71f4551d22bc8feb6d0f1349db811de635cce/src/test/java/com/caoccao/javet/interop/engine/TestJavetEnginePool.java#L68)

Additional information:
- @Miaow233 uses arm64 Android phone and I use x86_64 Android emulator on Windows

**Comment by ceclin** [comment]
Sorry, I did something wrong...

Termux installs OpenJDK 17 by default, which makes testDynamicProxyHandlerInStaticMode() failed, then causes all following (maybe) tests failed.

By the way, I think a test should not be affected by other tests. X﹏X

**Comment by caoccao** [comment]
The test suite is not designed for testing the Android binaries. In other words, the Android binaries are not test covered at all. Commenting on those assertions makes no sense because that leads to serious memory leaks.

Under the hook, the Android jar loads the binary directly into the default classloader. That results in some test cases failing because the test cases are designed for other platforms where the binaries are loaded into their dedicated classloaders.

**Comment by ceclin** [comment]
> By the way, I think a test should not be affected by other tests. X﹏X

I ran unit tests on my Windows laptop (not Android emulator) and the same result occurred.

Here is the test report of `testDynamicProxyHandlerInStaticMode()`:
```
org.opentest4j.AssertionFailedError: ownKeys should work. ==> expected: <["STATIC_READONLY_VALUE","STATIC_WRITABLE_VALUE","annotatedInterfaces","annotatedSuperclass","annotation","annotations","anonymousClass","array","canonicalName","class","classLoader","classes","componentType","constructors","declaredAnnotations","declaredClasses","declaredConstructors","declaredFields","declaredMethods","declaringClass","enclosingClass","enclosingConstructor","enclosingMethod","enum","enumConstants","fields","genericInterfaces","genericSuperclass","interface","interfaces","localClass","memberClass","methods","modifiers","name","package","primitive","protectionDomain","signers","simpleName","superclass","synthetic","typeName","typeParameters"]> but was: <["STATIC_READONLY_VALUE","STATIC_WRITABLE_VALUE","annotatedInterfaces","annotatedSuperclass","annotation","annotations","anonymousClass","array","canonicalName","class","classLoader","classes","componentType","constructors","declaredAnnotations","declaredClasses","declaredConstructors","declaredFields","declaredMethods","declaringClass","enclosingClass","enclosingConstructor","enclosingMethod","enum","enumConstants","fields","genericInterfaces","genericSuperclass","interface","interfaces","localClass","memberClass","methods","modifiers","module","name","nestHost","nestMembers","package","packageName","primitive","protectionDomain","signers","simpleName","superclass","synthetic","typeName","typeParameters"]>
```

I think this failure is because JDK 11 adds new methods to `java.lang.Class`.

For following reasons:

1. All tests are successful in JDK 8.
2. `testDynamicProxyHandlerInStaticMode()` and some other tests fail in JDK 11.
3. If I comment [these lines](https://github.com/caoccao/Javet/blob/daf71f4551d22bc8feb6d0f1349db811de635cce/src/test/java/com/caoccao/javet/values/reference/TestV8ValueProxy.java#L144), all tests are successful in JDK 11.
4. If I replace the expected result with the correct output in JDK 11, all tests are successful in JDK 11.
5. If I add `assertTrue(false);` after [these lines](https://github.com/caoccao/Javet/blob/daf71f4551d22bc8feb6d0f1349db811de635cce/src/test/java/com/caoccao/javet/values/reference/TestV8ValueProxy.java#L144), `testDynamicProxyHandlerInStaticMode()` and some other tests fail in JDK 8.

I am sure the failure of `testDynamicProxyHandlerInStaticMode()` will cause some other tests to fail.

**Comment by ceclin** [comment]
> Commenting on those assertions makes no sense because that leads to serious memory leaks.

I know it. It is because in the test report too many tests fail at those assertions and I want to check if there are any other failure reasons.

**Comment by ceclin** [comment]
> In other words, the Android binaries are not test covered at all.

I would appreciate it if node mode can be used on Andoird. With current codebase in main branch, if we fix `testDynamicProxyHandlerInStaticMode()`, all tests are successful in both v8 and node mode on Android. Cound you give some advice about it? For example, what potential problems it may have or what we should do next to make node mode really available on Android.

**Comment by farendaibiao** [comment]
> > In other words, the Android binaries are not test covered at all.
> 
> I would appreciate it if node mode can be used on Andoird. With current codebase in main branch, if we fix `testDynamicProxyHandlerInStaticMode()`, all tests are successful in both v8 and node mode on Android. Cound you give some advice about it? For example, what potential problems it may have or what we should do next to make node mode really available on Android.

modules cannot pass, https://www.caoccao.com/Javet/reference/resource_management/modularization.html
the workingDirectory is invalid

**Comment by ceclin** [comment]
@farendaibiao Sorry, I don't know what you mean.

Here is an available example in an Android app:

```kotlin
private fun nodeMode() {
    val base = File(filesDir, "node_modules")
    if (base.exists())
        base.deleteRecursively()
    File(base, "decimal.js").let {
        it.mkdirs()
        File(it, "package.json").writeText(
            """
            content of package.json
        """.trimIndent()
        )
        File(it, "decimal.js").writeText(
            """
            content of decimal.js
        """.trimIndent()
        )
    }

    val nodeRuntime = V8Host.getNodeInstance().createV8Runtime<NodeRuntime>()
    nodeRuntime.getNodeModule(NodeModuleModule::class.java)
        .setRequireRootDirectory(base)
    val result = nodeRuntime.getExecutor(
        """
        const Decimal = require('decimal.js');
        const a = new Decimal(1.23);
        const b = new Decimal(2.34);
        let result = a.add(b);
        JSON.stringify(result);
    """.trimIndent()
    ).executeString()
    textView.text = result
    nodeRuntime.close()
}
```

@caoccao It seems there is a mistake in [doc](https://www.caoccao.com/Javet/reference/resource_management/modularization.html):
```
File workingDirectory = new File(JavetOSUtils.WORKING_DIRECTORY, "scripts/node/test-node");
```
which should be:
```
File workingDirectory = new File(JavetOSUtils.WORKING_DIRECTORY, "scripts/node/node_modules");
```

**Comment by farendaibiao** [comment]
> @farendaibiao Sorry, I don't know what you mean.
> 
> Here is an available example in an Android app:
> 
> ```kotlin
> private fun nodeMode() {
>     val base = File(filesDir, "node_modules")
>     if (base.exists())
>         base.deleteRecursively()
>     File(base, "decimal.js").let {
>         it.mkdirs()
>         File(it, "package.json").writeText(
>             """
>             content of package.json
>         """.trimIndent()
>         )
>         File(it, "decimal.js").writeText(
>             """
>             content of decimal.js
>         """.trimIndent()
>         )
>     }
> 
>     val nodeRuntime = V8Host.getNodeInstance().createV8Runtime<NodeRuntime>()
>     nodeRuntime.getNodeModule(NodeModuleModule::class.java)
>         .setRequireRootDirectory(base)
>     val result = nodeRuntime.getExecutor(
>         """
>         const Decimal = require('decimal.js');
>         const a = new Decimal(1.23);
>         const b = new Decimal(2.34);
>         let result = a.add(b);
>         JSON.stringify(result);
>     """.trimIndent()
>     ).executeString()
>     textView.text = result
>     nodeRuntime.close()
> }
> ```
> 
> @caoccao It seems there is a mistake in [doc](https://www.caoccao.com/Javet/reference/resource_management/modularization.html):
> 
> ```
> File workingDirectory = new File(JavetOSUtils.WORKING_DIRECTORY, "scripts/node/test-node");
> ```
> 
> which should be:
> 
> ```
> File workingDirectory = new File(JavetOSUtils.WORKING_DIRECTORY, "scripts/node/node_modules");
> ```

have a try https://www.cdnpkg.com/crypto-js

**Comment by caoccao** [comment]
I wonder if it's better to discuss these somewhere else. @ceclin @farendaibiao Do you mind joining the discord server? And there's also a dedicated WeChat group.
