### ISSUE TITLE
Can compiled scripts be persisted to disk?

### ISSUE THREAD

**Issue by jcrabanal** [caoccao/Javet#212]
Feature request:

In Rhino, for performance reasons, I was able to save the generated java bytecode of compiled scripts to restore them after a cold boot, avoiding script parsing, building the AST, etc.

In V8 there is no java bytecode involved, but it seems that some sort of v8 bytecode caching could be done:

[https://github.com/v8/v8/blob/8.8.276/include/v8.h#L1710](https://github.com/v8/v8/blob/8.8.276/include/v8.h#L1710)

[https://medium.com/compilers/calculating-1-1-in-javascript-part-2-e01f336503d0](https://medium.com/compilers/calculating-1-1-in-javascript-part-2-e01f336503d0)

**Comment by jcrabanal** [comment]
Awesome.

As I'd like to do the caching myself, I'll be handling the files and removing them when unneeded. Something like instancing V8Script objects from byte arrays, input streams or whatever would be great.

**Comment by caoccao** [comment]
It's half way done at this [commit](https://github.com/caoccao/Javet/commit/e7df88ac98e68088fada09b5bbfe875a033ea984). Please let me know if you have any questions.

**Comment by jcrabanal** [comment]
Looks good to me.

But I don't see any methods to restore from cold boot?

**Comment by caoccao** [comment]
The 2nd half is at this [commit](https://github.com/caoccao/Javet/commit/a095f95af66d54473bc8e22c2208e3c1d5926721).

**Comment by jcrabanal** [comment]
Very nice, thank you.

**Comment by caoccao** [comment]
With this [commit](https://github.com/caoccao/Javet/commit/3381f24226b7589111778d425966a478a6a7568b), module, script and function all support loading cached data `byte[]`.
