### ISSUE TITLE
Can't spawn an http server from node.js inside javet

### ISSUE THREAD

**Issue by newk5** [caoccao/Javet#22]
I have a main.js file with this code:

```javascript
const express = require("express");
const app = express();

app.listen(3000, "0.0.0.0", () => {
    console.log(`Running server`);
});
```
And from java I'm doing this:
```java
  V8Host v8Host = V8Host.getNodeInstance();

  V8Runtime v8 = v8Host.createV8Runtime();
  v8.getExecutor(new File("main.js")).execute();
        
  Scanner in = new Scanner(System.in);
  System.out.println("running server, press enter stop");
  in.nextLine();
```
I dont get any errors but the server never starts either.

**Comment by caoccao** [comment]
I guess there are 2 pitfalls in dealing with Node.js.

1. The Java thread is lended to Node.js runtime. If that Java thread is blocked at readline, Node.js runtime is frozen. So, you need to create a worker thread hosting that Node.js runtime.
2. Node.js activates its event loop when it exits. That is almost unknown to the majority of Node.js developers. As in an embedded environment, application has 2 choices: either close that Node.js runtime, or call`await()`. Yes, `await()` is a special API provided by Javet. It allows application to trigger that event loop without exiting.

Good luck 🤞

**Comment by newk5** [comment]
Hmm I guess this becomes a big problem for my use case. Seeing as I'm using node embedded inside a java game server, I can never use await() because that will block the main server thread and if I do that the whole server will become unresponsive.

I'm trying to explore your first option, creating a different thread to spawn that Node.js runtime but it doesn't solve my issue either. Am I understanding correctly that if I have a .js file that spawns a node.js long running process (like http server) and I run that from javet, that specific Node.js runtime is forever lost/frozen to the point I can't even call other functions on that .js file? Even if I spawn that node.js runtime in a different thread, after the node.js http server starts, I can no longer interact with that runtime from java, unless I'm doing something wrong 🤔  This is what I tried:

main.js
```javascript
const express = require("express");
const app = express();

app.listen(3000, "0.0.0.0", () => {
    console.log(`Running server`);
});

function hello() {
    console.log("hello")
}
```
java code
```java
//spawn the runtime in a different thread so it doesn't block the main thread with internal node.js long running processes
       Thread t = new Thread(() -> {
            V8Host v8Host = V8Host.getNodeInstance();
            v8 = v8Host.createV8Runtime();
            try {
                v8.getExecutor(new File("main.js")).execute();
                v8.await();
            } catch (JavetException ex) {
                ex.printStackTrace();
            }
        });
        t.setDaemon(true);
        t.start();

        try {
            Scanner in = new Scanner(System.in);
            System.out.println("running server, press enter to execute function");
            in.nextLine();
            //call function from main.js from a different thread
            v8.getGlobalObject().invoke("hello", false);
            System.out.println("executed hello()");
            in.nextLine();
        } catch (JavetException e) {
            e.printStackTrace();
        }

```

The javascript hello() function is never called.

**Comment by caoccao** [comment]
This is a very interesting thing, even to me because I'm also exploring how to better play with Node.js in JVM. I'll try that sometime later. One quick experiment I think you could do is to remove line 1-6 from `main.js` and do that again.

**Comment by newk5** [comment]
Yep, if I remove the code to start the http server from my main.js file, it works because await() no longer freezes the node runtime, but I need to keep the code there for my use case

**Comment by caoccao** [comment]
I'll do some test later and get back to you.

**Comment by caoccao** [comment]
I just tried and confirmed that what you wanted to achieve seems to be impossible. Here are my thoughts for your reference.

That express server relies on Node.js event loop being activated. That's what `await()` does. However, once the Node.js event loop is activated, the V8 embedded in that Node.js runtime will no longer respond to calls from JVM. The reason is simple:

* V8 is single threaded
* Node.js has its own event loop (libuv)

The door is still open, I suppose. The key is how to borrow that thread and event loop. Here are 2 options for your reference.

Option 1: Timer
---

1. Intercept a JS function in Java. Let's say `a()`.
2. Set a timer with the callback function `a()` in JS.
3. Node.js will periodically call back to Java via `a()`.
4. In the callback, Java will be able to invoke `test()`.

Option 2: Express Server
---

Step 1, 3, 4 are the same, but step 2 may be replaced by an express event handler.

Summary
---

In general, these 2 options are the same in terms of borrowing the Node.js thread and event loop. Hope that makes sense. Please let me know if you have any questions.

**Comment by caoccao** [comment]
Option 3: Hack Node.js Event Loop
---

I think it's possible and will give it a try sometime later.

**Comment by caoccao** [comment]
Good news! **Option 3: Hack Node.js Event Loop** works. I think once v0.8.6 is released, this issue may be closed.

**Comment by newk5** [comment]
I tested 0.8.6 it works but it seems that .await() doesn't always activate the event loop. If I call a JS function that does NOT use the nodejs event loop and then I call await() it wont activate the event loop. This means every time I call a JS function I have to spawn a new thread and call await() to activate the event loop because I dont know in which JS function the user will need the event loop.


It would be nice if await() always activated the event loop even if there were no items in the task queue, that way I would only need to call it once. Right now it seems it only activates the event loop if there are tasks in the queue, which forces me to call await() after every JS function because I dont know which JS function will add tasks to the event loop queue

**Comment by caoccao** [comment]
In your case, I suggest that worker thread host its own event loop in Java. That's simply `while (true) { await(); sleep(); }`.

**Comment by caoccao** [comment]
There's nothing special in that. Basically, all Javet API are the equal. I suggest you to mark your executor as **module** so that Node.js treats it as a Promise in the event loop.

**Comment by newk5** [comment]
I cant do this because when I set my executor to **module**, .invoke() and .execute() stop working.

**Comment by caoccao** [comment]
I suggest you wrap those scripts in modules and call `require()` instead. That's also what I did in my migration.

``` js
// module-a.js
exports.a = ...;
```

``` java
try (var a = nodeRuntime.getExecutor("require('module-a.js')").execute()) {
    a.invoke(...);
}
```

**Comment by newk5** [comment]
But that will force me to use invoke() which is my main issue and the reason I'm using .execute  instead.

I need to avoid invoke() when the functions has arguments because as you know in very high freq. situations, this will have a big memory overhead when converting the java objects to V8Values because of .setFunction.

Is there really now way for javet to automatically process the event loop on .execute() the same way it does for invoke()?

**Comment by caoccao** [comment]
That touches another tricky area I think I will document somewhere later.

`execute()` can only see global context, and be seen by global context. That seems to be the technical bottle neck of the current design. I tend to believe that is a V8 feature instead of a defect. So, that may explain why some of your calls just don't work.

`invoke()` and `call()` are different because they can see local context.

In your case, some blocks become local context once they are evaluated by V8 runtime. You need a bridge which is visible to global context and also sees the previous local context. What I suggest you to do is to prepare that bridge, then `invoke()` that bridge.

Hope this makes sense. Please let me know if you have any questions.

**Comment by newk5** [comment]
But as I said, I can't use invoke() in high freq. situations because of the memory overhead, so I'm not really sure how to proceed. I just need a way to force the event loop to be processed with .execute()

**Comment by newk5** [comment]
Ok so I did more testing and now even when using .execute the event loop is being processed. I'm not sure why, on my previous test when using .execute it ignored event loop tasks and only work when using invoke(). So I'm not sure what is happening but there is inconsistent behaviour, sometimes the event loop is ignored and sometimes it's not,  I still dont know why, I'll make some more tests and get back to you when I have something more specific.

**Comment by caoccao** [comment]
Interesting, `invoke()` should save more resource than `execute()` does. I wonder if you can share your project with me for a code review and performance test, and we may come up with more ideas.

**Comment by newk5** [comment]
You can see my code here: https://github.com/newk5/vcmp-nodejs-plugin/blob/master/src/main/java/com/github/newk5/vcmp/nodejs/plugin/ServerEventHandler.java

But that is not up to date with the latest tests I have been doing with 0.8.6. But anyways I noticed now the problem is not specific to .execute() as I thought. I am now noticing scenarios where even when using invoke() the event loop is still being ignored. (Btw I'm doing what you suggested hosting my own event loop in a worker thread and calling await)

Anyways when I have something more specific I will create a small reproducer and post here.

**Comment by caoccao** [comment]
I see. I wonder if you could invite me as a contributor, and I would be able to submit pull request based on the latest Javet (not released). And, yes, reproducing the issues in your branch is very helpful for me to save time for tuning Javet.

**Comment by newk5** [comment]
I could add you as a contributor, but my project needs a game server binary and the game to run, so you'd have to install the game and the server,  But it's okay, I was able to reproduce the issue in an isolated case, I created a small snippet for you to be able to reproduce it, test this:

```java
 static V8Runtime v8 = null;
    static AtomicBoolean started = new AtomicBoolean();

    public static void main(String[] args) {

        Thread t = new Thread(() -> {
            try {
                V8Host v8Host = V8Host.getNodeInstance();
                v8 = v8Host.createV8Runtime();

                v8.getExecutor(new File("main.js")).execute();
                started.set(true);
                while (true) {
                    v8.await();
                    Thread.sleep(500);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        });
        t.setDaemon(true);
        t.start();
        while (!started.get()) {
            //wait for the runtime to start
        }

        try {
            System.out.println("wait for the request response....");
            v8.getGlobalObject().invoke("makeRequest");
            Scanner in = new Scanner(System.in);

            in.nextLine();
            v8.getGlobalObject().invoke("runServer");
            
            System.out.println("executed makeRequest() press enter to quit");
            in.nextLine();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```
main.js
```javascript


var unirest = require("unirest");
var req = unirest("POST", "http://mockbin.com/request");

const express = require("express");
const app = express();

function makeRequest(){

    req.headers({'Accept': 'application/json', 'Content-Type': 'application/json'});
    req.form({ "parameter": 23, "foo": "bar" });


    req.end(function (res) {
        if (res.error) throw new Error(res.error);

        console.log(res.body);
        console.log("http request callback returned, press enter now to start the http server");
       
       
    });

}

function runServer(){
    app.listen(3200, "0.0.0.0", () => {
        console.log(`Running server`);
    });
}



```
The http request callback is called successfully when the function makeRequest() is ran, but the callback for the http server is never called when the function runServer() is called. Make sure you do:
```
npm install express
npm install unirest
```
Try the exact code above and you will be able to reproduce the issue. Wait for the http request response and then press enter.

**Comment by caoccao** [comment]
Nice, I'll check it out sometime later.

**Comment by caoccao** [comment]
I reviewed the source code and suggest you to move `v8.getGlobalObject().invoke("runServer");` from main thread to worker thread as following. Please let me know if this works.

``` java
        Thread t = new Thread(() -> {
            try {
                V8Host v8Host = V8Host.getNodeInstance();
                v8 = v8Host.createV8Runtime();

                v8.getExecutor(new File("main.js")).executeVoid();
                // Here
                v8.getGlobalObject().invoke("runServer");
                started.set(true);
                while (true) {
                    v8.await();
                    Thread.sleep(500);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        });
```

**Comment by newk5** [comment]
That worked although I dont exactly understand why. But anyway, that was just an example I made for you to be able to reproduce the issue. For my actual project, I don't know which javascript function will start the http server, that is controlled by the user. It might not even exist any function that will start an http server, so how do I know if I should wrap .invoke in a thread or not?

**Comment by caoccao** [comment]
How?
---

The theory behind that is what I mentioned above: a worker thread is required to host that Node.js event loop. So, the main thread can handle everything except that event loop. The worker thread can be simplified to the following.

``` java
Thread t = new Thread(() -> {
    while (true) {
        try {
            v8Runtime.await();
            Thread.sleep(100);
        } catch (InterruptedException e) {
            break;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
});
t.start();
```

Tips
---

* Any requests hitting Node.js server are handled by the worker thread inside the Node.js event loop.
* Any injections from JVM are handled by the main thread (or other threads).
* Javet makes these possible by setting up the bridge between JVM and Node.js, taking care of the thread safety, etc.

Summary
---

In your case, your application doesn't need to know whether the request is for opening a server or not, whether the request is from Node.js or JVM, everything just works because the worker thread hosts the Node.js event loop.

Please let me know if you have any questions.

**Comment by newk5** [comment]
But you just told me  to remove the event loop above:

>  drop the event loop in worker thread as following. Please let me know if this works.


It only worked when I removed it.

**Comment by caoccao** [comment]
That was for narrowing the issue. Please try my latest suggestion to see if it works.

**Comment by newk5** [comment]
It also doesn't work. Here's my code:
```java
 static V8Runtime v8 = null;

    public static void main(String[] args) throws JavetException {

        V8Host v8Host = V8Host.getNodeInstance();
        v8 = v8Host.createV8Runtime();

        v8.getExecutor(new File("main.js")).execute();

        Thread t = new Thread(() -> {
            while (true) {
                try {
                    v8.await();
                    Thread.sleep(100);
                } catch (InterruptedException e) {
                    break;
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
        t.setDaemon(true);
        t.start();

        try {
            System.out.println("wait for the request response....");
            v8.getGlobalObject().invoke("makeRequest");
            Scanner in = new Scanner(System.in);

            in.nextLine();
            v8.getGlobalObject().invoke("runServer");

            System.out.println("executed runServer() press enter to quit");
            in.nextLine();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

````
You can see the main.js file above in my previous post. You will the http server callback that logs "Running server" is never called.

**Comment by newk5** [comment]
To be clear, what I'm trying to say here is:  

- When hosting an event loop in a worker thread, it doesn't work  (my example above proves that). 
- And if I remove the event loop running in my worker thread like you suggested, it works, but for my use case the contents of the JS functions I'm invoking() are not coded by me, they are coded by my users, so I have no way of knowing which functions are spawning an http server so I can't call await()

**Comment by newk5** [comment]
Thank you! That's exactly what I need. I'll wait for the next release and give it a try 👍

**Comment by newk5** [comment]
Thanks I just tried it and I can confirm it works, great job 👍

**Comment by caoccao** [comment]
Wonderful! Thank you for the great help!
