### ISSUE TITLE
mac build node error   

### ISSUE THREAD

**Issue by aoqilinjian** [caoccao/Javet#220]
I have build v8 and node success, 

sh build-macos.sh -DV8_DIR=/Users/game/workspace_goblin/javet/v8       success
but node fail , node clone from github
---------------------------------------
topjoy@topjoydeMacBook-Pro-6 cpp % sh build-macos.sh -DNODE_DIR=/Users/game/workspace_goblin/javet/node                                                 
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/game/workspace_goblin/javet/Javet/cpp/build
[  9%] Building CXX object CMakeFiles/JavetStatic.dir/jni/com_caoccao_javet_interop_NodeNative.cpp.o
[  9%] Building CXX object CMakeFiles/Javet.dir/jni/com_caoccao_javet_interop_NodeNative.cpp.o
[ 13%] Building CXX object CMakeFiles/Javet.dir/jni/com_caoccao_javet_interop_V8Native.cpp.o
[ 18%] Building CXX object CMakeFiles/JavetStatic.dir/jni/com_caoccao_javet_interop_V8Native.cpp.o
/Users/topjoy/workspace_goblin/javet/Javet/cpp/jni/com_caoccao_javet_interop_V8Native.cpp:99:25: error: no member named 'ShutdownPlatform' in 'v8::V8'
                v8::V8::ShutdownPlatform();
                ~~~~~~~~^
/Users/topjoy/workspace_goblin/javet/Javet/cpp/jni/com_caoccao_javet_interop_V8Native.cpp:99:25: error: no member named 'ShutdownPlatform' in 'v8::V8'
                v8::V8::ShutdownPlatform();
                ~~~~~~~~^
1 error generated.
1 error generated.

**Comment by caoccao** [comment]
You cloned the wrong version of Node.js. Please align with the version written in the README.

**Comment by aoqilinjian** [comment]
yes, I use node-18.12.1  build success 
thank you very much
