### ISSUE TITLE
ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by aoqilinjian** [caoccao/Javet#221]
Exception in thread "main" com.caoccao.javet.exceptions.JavetExecutionException: ReferenceError: exports is not defined
	at com.caoccao.javet.interop.V8Native.execute(Native Method)
	at com.caoccao.javet.interop.V8Runtime.execute(V8Runtime.java:858)
	at com.caoccao.javet.interop.executors.V8StringExecutor.execute(V8StringExecutor.java:76)
	at com.caoccao.javet.interop.IV8Executable.executeVoid(IV8Executable.java:170)
	at com.topjoy.v8.javet.function.TestFileScript4Import.test1(TestFileScript4Import.java:41)
	at com.topjoy.v8.javet.function.TestFileScript4Import.main(TestFileScript4Import.java:21)

 how can I support commonjs ？

--------test1.js----------------------------
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
exports.__esModule = true;
var test2_1 = require("./test2");
var test1 = /** @class */ (function (_super) {
    __extends(test1, _super);
    function test1() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    test1.prototype.run = function () {
        _super.prototype.run.call(this);
        console.log("test1 run");
    };
    return test1;
}(test2_1["default"]));
exports["default"] = test1;
var t1 = new test1();
t1.run();

--------test2.js----------------------------
"use strict";
exports.__esModule = true;
var test2 = /** @class */ (function () {
    function test2() {
    }
    test2.prototype.run = function () {
        console.log("test2 run");
    };
    return test2;
}());
exports["default"] = test2;

**Comment by caoccao** [comment]
Please read this [doc](https://www.caoccao.com/Javet/reference/resource_management/modularization.html).

**Comment by aoqilinjian** [comment]
test1.js   function
---------------
export function TestReturn(a, b) {
    var t1 = new test1();
    t1.run();
    return t1.add(a.toString(), b);
}
-----------------------
java method

 public static void test1() throws JavetException {

        String path = ConstUtil.JAVA_SCRIPT_PATH+"model";
        V8Host v8Host = V8Host.getNodeInstance();
        NodeRuntime nodeRuntime = v8Host.createV8Runtime();

        File workingDirectory = new File(path);

        nodeRuntime.getNodeModule(NodeModuleModule.class).setRequireRootDirectory(workingDirectory);
        File scriptFile = new File(path + "/test1.js");
        nodeRuntime.getExecutor(scriptFile).setModule(true).executeVoid();

        String result1 = nodeRuntime.getGlobalObject().invokeString("TestReturn", "3", "5");
        System.out.println("result1="+ result1);
    }

but the result null，from the doc，  I dont know how get the result

**Comment by aoqilinjian** [comment]
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
exports.__esModule = true;
var test2_1 = require("./test2");
var test1 = /** @class */ (function (_super) {
    __extends(test1, _super);
    function test1() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    test1.prototype.run = function () {
        _super.prototype.run.call(this);
        console.log("test1 run");
    };
    test1.prototype.add = function (a, b) {
        return a + b;
    };
    return test1;
}(test2_1["default"]));
exports["default"] = test1;
export function TestReturn(a, b) {
    var t1 = new test1();
    t1.run();
    return t1.add(a.toString(), b);
}
-------------
this is test1.js

**Comment by caoccao** [comment]
You need to call `require()` to load that module. It's just like how you do things in Node.js.

**Comment by aoqilinjian** [comment]
I search all the javet source, I cant find the require method
can you give me a example?

**Comment by caoccao** [comment]
You don't need to compile any modules. Just place your files as they are with Node.js. It is the same way you use Node.js.

**Comment by aoqilinjian** [comment]
we use ts,  need  compile to js

**Comment by aoqilinjian** [comment]
my test case 
 https://github.com/aoqilinjian/v8.git
can you help me look at the class  TestFileScript4Import.java, 
pacage at  com.topjoy.v8.javet.function

thank you very much

**Comment by caoccao** [comment]
- Please review the legacy issues some of which are similar to yours.
- Executing a module is useless because you will get a Promise. You need another script to import that module.
- You don't need to execute a module if you use `require`. If your JS code can be executed in pure Node.js, so does Javet.

**Comment by aoqilinjian** [comment]
I review all the issues
I think you are right, but, I  dont know my case  where the bug is?
please help me take a look.

**Comment by caoccao** [comment]
Please join the discord server to reach me.

**Comment by aoqilinjian** [comment]
微信 ，qq， 或者 钉玎 可以吗？

**Comment by aoqilinjian** [comment]
我可以加一下您的微信或者qq，或者钉钉吗？
