### ISSUE TITLE
Add Automatic-Module-Name entry to JAR manifest

### ISSUE THREAD

**Issue by blutorange** [caoccao/Javet#229]
Right now when we add javet as a dependency in a Java module, e.g.

```java
/**
 * Provides an IJsExecutor implementation that executes JavaScript via Javet/NodeJS, useful for tests.
 */
module org.company.http.javet {
  requires org.slf4j;
  requires javet;

  requires transitive org.company.http.api;
  
  exports org.company.http.javet.api;
}
```

we get a warning message regarding the module name

> Name of automatic module 'javet' is unstable, it is derived from the module's file name.

This can be solved by adding `Automatic-Module-Name` to the `MANIFEST.MF` of the JAR file, see e.g. http://branchandbound.net/blog/java/2017/12/automatic-module-name/ or https://docs.oracle.com/javase/9/docs/specs/jar/jar.html

It would be great if that manifest entry could be added! The module name must not contain special characters (I had at least one library which used invalid character in the module name, making it completely unusable)

> A module name consists of one or more Java identifiers ([§3.8](https://docs.oracle.com/javase/specs/jls/se13/html/jls-3.html#jls-3.8)) separated by "." tokens.

**Comment by caoccao** [comment]
Good idea. Hope this [commit](https://github.com/caoccao/Javet/commit/2a299a48bd0f31f78d976703f4fd8ef785936f37) serves you well.

**Comment by blutorange** [comment]
Thank you very much, this is greatly appreciated and gets rid of annoying warning : )
