### ISSUE TITLE
Javet 2.1.1 crashes on closing the runtime

### ISSUE THREAD

**Issue by jcrabanal** [caoccao/Javet#238]
I see in the changelog that javet no longer stores callback contexts in the global reference table since 2.1.1, which is good, I was having trouble with excessive references.

But the latest version of javet will JNI crash the app if you bind a JavetCallbackContext when the close() method of the V8Runtime gets invoked:

    A/ample.javettest: runtime.cc:689] JNI DETECTED ERROR IN APPLICATION: JNI ERROR (app bug): jobject is an invalid JNI transition frame reference or invalid reference: 0x7589859eb0 (use of invalid jobject)

Here is sample code that reproduces this:

    package com.example.javettest;
    
    import android.os.Bundle;
    import android.widget.TextView;
    
    import androidx.annotation.Nullable;
    import androidx.appcompat.app.AppCompatActivity;
    
    import com.caoccao.javet.interop.V8Host;
    import com.caoccao.javet.interop.V8Runtime;
    import com.caoccao.javet.interop.callback.JavetCallbackContext;
    import com.caoccao.javet.interop.executors.IV8Executor;
    import com.caoccao.javet.values.reference.V8ValueGlobalObject;
    
    public class ActivityTest extends AppCompatActivity {
    
        private TextView vText;
    
        @Override
        protected void onCreate(@Nullable Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.activity_layout);
            vText = findViewById(R.id.script_result);
            try (V8Runtime v8Runtime = V8Host.getV8Instance().createV8Runtime()) {
                V8ValueGlobalObject globalObject = v8Runtime.getGlobalObject();
                globalObject.bindFunction("aaa", new JavetCallbackContext(this, getClass().getMethod("hello")));
                IV8Executor executor = v8Runtime.getExecutor("'Hello Javet'");
                String sResult = executor.executeString();
                vText.setText(sResult);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }

        public void hello() {
            if (vText == null) {
                return;
            }
            vText.post(new Runnable() {
                @Override
                public void run() {
                    vText.setText("world");
                }
            });
        }
    }

I believe the problem lies around here, in V8Runtime.java:

    /**
     * Remove callback contexts.
     *
     * @since 0.8.3
     */
    void removeCallbackContexts() {
        synchronized (callbackContextLock) {
            if (!callbackContextMap.isEmpty()) {
                final int callbackContextCount = callbackContextMap.size();
                for (long handle : callbackContextMap.keySet()) {
                    removeJNIGlobalRef(handle);
                }
                logger.logWarn("{0} V8 callback context object(s) not recycled.",
                        Integer.toString(callbackContextCount));
                callbackContextMap.clear();
            }
        }
    }

**Comment by caoccao** [comment]
Update: Yes, that is a bug which is muted on PC but causes crash on Android. It's fixed by this [commit](https://github.com/caoccao/Javet/commit/b24bb2e4b2707c73f75ea2bc92ed1f870a91dda6). Please wait for the next release. Thank you.

**Comment by jcrabanal** [comment]
Thank you for your efforts. JNI is definitely way more strict in Android.

The log message warning there makes me wonder. Am I supposed to release/free those callbacks in some other way?

**Comment by caoccao** [comment]
There is a workaround. Remove that function and call GC before closing the runtime.
