### ISSUE TITLE
Javet doesn't differentiate java methods overloads with different parameter types with bind

### ISSUE THREAD

**Issue by bananasmoothii** [caoccao/Javet#251]
So when using `bind`, with a Java class instance, if two methods have the same name but not the same argument types (e.g. one methods takes a `Player` and the other one takes an `Iterable<Player>`, `Player` being a minecraft player so it has nothing to do with javet) And if I call the one that takes only a `Player` in js, i get
```
com.caoccao.javet.exceptions.JavetExecutionException: Error: Callback signature mismatches: expected parameter type is interface java.lang.Iterable, actual parameter type is class org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer
 	at com.caoccao.javet.interop.V8Native.functionCall(Native Method)
 	at A-0.1-all.jar//com.caoccao.javet.interop.V8Runtime.functionCall(V8Runtime.java:949)
 	at A-0.1-all.jar//com.caoccao.javet.interop.V8Internal.functionCall(V8Internal.java:98)
 	at A-0.1-all.jar//com.caoccao.javet.values.reference.V8ValueFunction.callExtended(V8ValueFunction.java:104)
 	at A-0.1-all.jar//com.caoccao.javet.values.reference.IV8ValueFunction.callVoid(IV8ValueFunction.java:285)
```
(`CraftPlayer` implements the interface `Player`)

This gets solved when using `JavetProxyConverter()` and using `getGlobalObject().set("...", new MyClass())` instead of
```java
    try (V8ValueObject v8ValueObject = v8Runtime.createV8ValueObject()) {
        v8Runtime.getGlobalObject().set("a", v8ValueObject);
        v8ValueObject.bind(testInterceptor);
    }
```

**Comment by caoccao** [comment]
So, there's no problem, right?

**Comment by bananasmoothii** [comment]
I'd say the bind method should work with overloads, but if you choose not to support that, you can...

**Comment by caoccao** [comment]
> I'd say the bind method should work with overloads, but if you choose not to support that, you can...

`bind()` comes with a little better performance, but less flexibility. If you are looking for overloading the functions, there are 2 ways:

1. Use the proxy / bridge converter.
2. Write your own routing methods with the signature like `V8Value test(V8Value... v8Values)` which is able to capture all the calls to `test()` without getting blamed by Javet.

**Comment by bananasmoothii** [comment]
Ok so it isn't supported by Javet, this could be worth mentioning in the docs :)
