### ISSUE TITLE
How do I use Nashon's "Java.type()" in Javet?

### ISSUE THREAD

**Issue by jae-cheol** [caoccao/Javet#252]
I'm curious about how to refer to Java class in JavaScript and call the referenced function like Nashorn.

ex nashorn javascript code)
var NashornTest = Java.type("mapping.NashornTest");
var result = NashornTest.func1("John Doe");
print(result);

**Comment by caoccao** [comment]
Welcome to the Javet way!

All you need to do is to follow this [doc](https://www.caoccao.com/Javet/reference/converters/proxy_converter.html), and use the Java way.

```java
v8Runtime.getGlobalObject().set("Class", Class.class);
v8Runtime.getExecutor("Class.forName(...);").executeVoid();
```

There are plenty of samples in the doc.

**Comment by jae-cheol** [comment]
> Welcome to the Javet way!
> 
> All you need to do is to follow this [doc](https://www.caoccao.com/Javet/reference/converters/proxy_converter.html), and use the Java way.
> 
> ```java
> v8Runtime.getGlobalObject().set("Class", Class.class);
> v8Runtime.getExecutor("Class.forName(...);").executeVoid();
> ```
> 
> There are plenty of samples in the doc.

When using "Nashon," Java was immediately available in "JavaScript" without "pre-work."
Does "Jabet" require "pre-work"?

**Comment by caoccao** [comment]
> When using "Nashon," Java was immediately available in "JavaScript" without "pre-work."

Security is the top priority in Javet. By default, applications get a genuine V8 without any non-ECMA features. Javet has been heavily used to execute external scripts in public cloud. The malicious script could simply call `System.exit(0)` to kill the JVM if Javet made these available by default.

So, if you want to empower the V8 runtime to access all of the Java capabilities, just do as my last reply indicates (few lines of code).

**Comment by jae-cheol** [comment]
> > When using "Nashon," Java was immediately available in "JavaScript" without "pre-work."
> 
> Security is the top priority in Javet. By default, applications get a genuine V8 without any non-ECMA features. Javet has been heavily used to execute external scripts in public cloud. The malicious script could simply call `System.exit(0)` to kill the JVM if Javet made these available by default.
> 
> So, if you want to empower the V8 runtime to access all of the Java capabilities, just do as my last reply indicates (few lines of code).

If I need 10 classes, should I write 10 lines?

**Comment by caoccao** [comment]
> If I need 10 classes, should I write 10 lines?

* Yes, if you want to.
* No. You may only inject a factory which can return those 10 classes. The lines to be written are always fixed.
