### ISSUE TITLE
how to remove the strict mode restrict ? 

### ISSUE THREAD

**Issue by grdk37** [caoccao/Javet#253]
when i. execute this code below ,i get the exception 
  
```
String jsencrypt = ...; // a String represents js from a file . 
v8Runtime.getExecutor(jsencrypt).executeVoid();
```
the same js script can be exeuted from j2v8 , or  Nashorn or rhino , but cannot be executed by javet. 
how to solve this ,  since the js file is very much long ---about 10,000 lines,  it is very difficult to change the js file . 

Exception in thread "main" com.caoccao.javet.exceptions.JavetCompilationException: SyntaxError: Strict mode code may not include a with statement
        at com.caoccao.javet.interop.V8Native.scriptExecute(Native Method)
        at com.caoccao.javet.interop.V8Runtime.execute(V8Runtime.java:922)
        at com.caoccao.javet.interop.executors.V8StringExecutor.execute(V8StringExecutor.java:107)
        at com.caoccao.javet.interop.IV8Executable.executeVoid(IV8Executable.java:170)

**Comment by caoccao** [comment]
Please call [V8Flags.setUseStrict(false)](https://www.caoccao.com/Javet/reference/javadoc/com/caoccao/javet/interop/options/V8Flags.html#setUseStrict-boolean-) before creating any V8Runtime, and strict mode will be turned off.

**Comment by grdk37** [comment]
> Please call [V8Flags.setUseStrict(false)](https://www.caoccao.com/Javet/reference/javadoc/com/caoccao/javet/interop/options/V8Flags.html#setUseStrict-boolean-) before creating any V8Runtime, and strict mode will be turned off.

thanks a lot ..   it is very nice of you.   very appreciation. 

just a little suggestion. 
in the tutorial ,  in some place ,it is written  
`NodeRuntime nodeRuntime = V8Host.getNodeInstance().createV8Runtime()`
in another place ,it is written 
`V8Runtime v8Runtime = V8Host.getNodeInstance().createV8Runtime()`

after downloading the jar ,i finally learnt that. NodeRuntime is a sub class of. V8Runtime. 
it is still a little confused when i  first read the tutorial ..

**Comment by grdk37** [comment]
after some research ,i finally got it ...   
thank you very much. 

```
 V8RuntimeOptions.V8_FLAGS.setUseStrict(false);
               
      try (V8Runtime v8Runtime = V8Host.getV8Instance().createV8Runtime()) {

            v8Runtime.getExecutor(jsencrypt).executeVoid();
}
```
