### ISSUE TITLE
Reduce android apk size

### ISSUE THREAD

**Issue by gituser8796** [caoccao/Javet#266]
Hi @caoccao, 

Is there a way to reduce the apk size for android? Size is increased by 200mb after adding Javet

**Comment by caoccao** [comment]
There are generally 2 approaches.

1. One `.so` file per CPU arch - You don't need to package all 4 `.so` files. That will reduce the size by 3/4.
2. Build Javet by yourself with trimmed V8 - You may trim V8 following the official doc to reduce the binary size. Please be aware the benefits are not significant and that requires some knowledge on building V8 and Javet.

**Comment by gituser8796** [comment]
Thanks @caoccao I'm going to try it
