### ISSUE TITLE
v8Runtime.getGlobalObject().invokeObject(fnName, arg); is returning null in a random manner

### ISSUE THREAD

**Issue by Lookout-ent** [caoccao/Javet#269]
v8Runtime.getGlobalObject().invokeObject(fnName, arg); is returning null sometimes.
I'm using javetEnginePool 
I have a script which is executed and a function is invoked with different arguments every time.
The behaviour is very random. Sometimes it returns the expected output and sometimes it returns null with the same argument
One thing i noticed is that it's a particular engine of the pool which is returning null
Maybe that engine has run into some exception/issue ??

**Comment by caoccao** [comment]
I'm sure there are bugs in your code. Could you post the code for the troubleshooting?

**Comment by Lookout-ent** [comment]
`function fnName(arg) {
        var modifiedArg = arg;
        try {
            modifiedArg = modify(arg)
        }
        catch (err) {
            modifiedArg = code;
        }
        return modifiedArg
    }`
    
    this function is invoked. there is no chance it would return any exception or return null if arg is not null
    I'm creating a pool of size N. I have executed my script on each engine of the pool using a multi-threaded task(not sure if javet provides a way to fetch all engines of the pool at once )
    
    now in my application, since i have already executed the script on engines, i'm simply invoking the function (fnName) 
    
    to elaborate the null situation. With the same argument sometimes it will return expected value and sometimes null.
    
    Is there any chance that my script is not executed on some engines and when invoking the function it is returning null ?But shouldn't it throw exception stating that function is not recognized or something like this ?
    Or is there any chance that after some idle time the engine has lost the executed script ? or maybe released ? I don't want any engine to get released without me explicitly releasing it 
    
    one more thing. Earlier i wasn't catching the exception in my function (fnName) so maybe it threw exception earlier and invokeObject returned null at that time(but it should throw exception instead ). and somehow that has altered the engine behaviour ? But now i'm catching the exception and have creating a new pool everytime ,when starting my application.
    So this null behaviour shouldn't be cached anyway.

**Comment by caoccao** [comment]
I think the bug is in your Java code. Could you share how you use Javet?

**Comment by Lookout-ent** [comment]
I'm creating a engine pool :
```
JavetEngineConfig poolConfig = new JavetEngineConfig();
            poolConfig.setPoolMaxSize(60);
            poolConfig.setJSRuntimeType(JSRuntimeType.V8);
            javetEnginePool = new JavetEnginePool<>(poolConfig);
```

then using a multi-threaded task i'm executing my script on the engines : i need some input here
i have a script which will not be changing and it has one function which needs to be invoked multiple times with one argument
for this purpose, to avoid multiple execution of my script on a engine, i'm using a multi-threaded task to execute the script and later on i'll be just invoking the function.
is there a better way to do this in javet ?

` try (IJavetEngine<V8Runtime> javetEngine = javetEnginePool.getEngine()) {
            V8Runtime v8Runtime = javetEngine.getV8Runtime();
            v8Runtime.getExecutor(scriptContent).executeVoid();
            v8Runtime.lowMemoryNotification();
        } catch (JavetException e) {
            e.printStackTrace();
        }`
        
        
  this will happen when application is starting 
  now as per the need i'll invoke the function in the script using :
  
  `try {
               try (IJavetEngine<V8Runtime> javetEngine = javetHelper.getJavetEnginePool().getEngine()) {          
                V8Runtime v8Runtime = javetEngine.getV8Runtime();
                rewrittenArg = v8Runtime.getGlobalObject().invokeObject("fnName", arg);              
            }     
        } catch (Exception e) {
            log.error("failed to rewrite argument {}");
        }`

**Comment by caoccao** [comment]
I think the bug here is you expect the initialization would touch all engines, however, it's not, because the engines are reused. So later, when you actually consume the engines some of which haven't been initialized yet.

The recommended way is as follows.

1. Sub-class engine, initialize the engine when it is being created.
2. Sub-class engine pool, return the sub-classed engine.

**Comment by Lookout-ent** [comment]
okay .. it could be 
is there any timeout after which engine is automatically released ?
and once released, i think i will lose the initialization as well 

i don't want any engine to be released based on timeout. Once created and initialized, i don't want it to get released ever.
Is this configurable ?

**Comment by caoccao** [comment]
Please follow my guide and the issue you are worrying about doesn't exist.

**Comment by Lookout-ent** [comment]
okay.. thanks 
let me try your approach

**Comment by Lookout-ent** [comment]
After some debugging i found that the engines were indeed released. Since i'm using try with resources, engine close is being called making the engine idle and once it crosses the poolIdleTimeout , the engine is released.
I need to control the poolIdleTimeout.

**Comment by caoccao** [comment]
Thanks for the update. It seems you've found your way, right?

**Comment by Lookout-ent** [comment]
yes .. right
but can u please confirm couple of things  
can u confirm if my understanding is correct regarding engine reset is correct ? will i lose the script initialization after engine reset ?

and i would expect that when script is not initialized/executed and if any method is invoked , javet should return an exception instead of null value

**Comment by caoccao** [comment]
If you follow my guide, the initialization is always executed when the engine is being created or reset. So, you don't need to tweak those timeout parameters.

It's V8 that decides when to throw errors, or when to return `undefined`. Javet doesn't interfere with V8.

**Comment by caoccao** [comment]
If you follow my guide, the initialization is always executed when the engine is being created or reset. So, you don't need to tweak those timeout parameters.

It's V8 that decides when to throw errors, or when to return `undefined`. Javet doesn't interfere with V8.

**Comment by Lookout-ent** [comment]
okay ... that sounds reasonable 
probably i'll close this issue then
