### ISSUE TITLE
android 是否支持nodejs呢

### ISSUE THREAD

**Issue by 0cococ** [caoccao/Javet#275]
<img width="900" alt="image" src="https://github.com/caoccao/Javet/assets/108533707/78c200db-09d0-4c3d-828b-f4d866dd31f2">
目前nodejs的二进制文件完全是可以在android平台运行的也可以正常使用npm的库 之前j2v8并没有支持nodejs在android上面 如果支持了nodejs会有很棒的生态

**Comment by caoccao** [comment]
There is a private build. Please check [this repo](https://github.com/ceclin/build-javet-node-android) out.

**Comment by 0cococ** [comment]
有微信群吗想一起交流学习




Boss
***@***.***




------------------ 原始邮件 ------------------
发件人: Sam Cao ***@***.***&gt;
发送时间: 2023年10月7日 09:22
收件人: caoccao/Javet ***@***.***&gt;
抄送: 1Plan ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [caoccao/Javet] android 是否支持nodejs呢 (Issue #275)





 
There is a private build. Please check this repo out.

**Comment by caoccao** [comment]
Node.js for Android will be supported soon. You may ping me at discord to get the WeChat qrcode.

**Comment by caoccao** [comment]
Snapshot build is ready at Actions.
