### ISSUE TITLE
how to call V8ValueFunction and get return value

### ISSUE THREAD

**Issue by Aricgit** [caoccao/Javet#28]
![image](https://user-images.githubusercontent.com/9571096/116193187-8af65d80-a761-11eb-8da2-36b56378d855.png)

My method has many parameters that need to be passed in, but it does not work.

**Comment by Aricgit** [comment]
close

**Comment by caoccao** [comment]
I think this [tutorial](https://github.com/caoccao/Javet/blob/main/docs/tutorial/manipulate_v8_function.rst) may help you with that.
