### ISSUE TITLE
GLIBC version not found for Javet 3.0.1 and Ubuntu 20.04

### ISSUE THREAD

**Issue by kozi** [caoccao/Javet#285]
### GLIBC version not found for Javet 3.0.1 and Ubuntu 20.04

Is there a way I can solve this problem?

> Ubuntu 20.04 still has standard support until May 2025.
> so it would be good if Javet could also run on this version, wouldn't it?

**Comment by caoccao** [comment]
Javet v3.0.0 is the last version built from Ubuntu 20.04.

It's possible to build v3.0.1 in Ubuntu 20.04, but that would take some extra effort. Please ping me at discord for details if you need a private build.

**Comment by caoccao** [comment]
v3.0.3 will be built on Ubuntu 20.04 for better compatibility. Please let me know if you have any questions.

**Comment by caoccao** [comment]
If you are fine with visiting the discord, ping me for the snapshot build of the next release. Gern geschehen.
