### ISSUE TITLE
IV8Executor#toObject cost too much cpu

### ISSUE THREAD

**Issue by Radiums** [caoccao/Javet#289]
![image](https://github.com/caoccao/Javet/assets/7265692/ad4806f3-a03f-4ec4-82f3-d639201c1d23)
wonder how to slove
version 1.1.0

**Comment by caoccao** [comment]
The overall performance depends on how complicated your objects are. It's similar to `JSON.parse` or `JSON.stringify`.

There are a few ways to improve the performance.

1. Upgrade to the latest version of Javet. Please refer to project [JavetPerf](https://github.com/caoccao/JavetPerf) for details.
2. Use `JavetProxyConverter` wisely.
3. Write your own converters.
4. Have code review with me.

**Comment by Radiums** [comment]
com.caoccao.javet.interop.converters.JavetObjectConverter 
with this convert
why JavetObjectConverter convert with lock and reflect instead Json result parse to JavaObject?

**Comment by caoccao** [comment]
I guess there might be some misunderstandings between us. Would you mind visiting the discord to discuss with me in detail?
