### ISSUE TITLE
add V8Property annotation

### ISSUE THREAD

**Issue by tansm** [caoccao/Javet#29]
你好，很开心试用您的 javet 项目，我的英文很糟糕，但我觉得您应该能看懂中文。
我在学习使用时发现只有 V8Function 。例如：
```kotlin
package kd.bos.olapServer

import com.caoccao.javet.annotations.V8Function
import com.caoccao.javet.interop.V8Runtime

class ScriptDimension(
    private val v8Runtime : V8Runtime,
    private val realObj : DimensionNode
) {
    @get:V8Function
    val name : String get() = realObj.name
}
```

当我注入这个实例后，我的 js 脚本只能这样使用（accounts就是我注入的ScriptDimension实例）：
```js
accounts.getName()
```
这些书写对用户不友好，我希望是：
```js
accounts.name
```

我查看了代码的实现，我发现只有 V8Function 注解，我希望能够增加： V8Property 这样的注解。
```kotlin
package kd.bos.olapServer

import com.caoccao.javet.annotations.V8Function
import com.caoccao.javet.interop.V8Runtime

class ScriptDimension(
    private val v8Runtime : V8Runtime,
    private val realObj : DimensionNode
) {
    @V8Property
    val name : String get() = realObj.name
}
```
您觉得这个主意如何？

------------------------------------------------------
Hello, I am very happy to try your javet project. My English is very bad, but I think you should be able to read Chinese.
When I was learning to use it, I found that there was only V8Function. E.g:
```kotlin
package kd.bos.olapServer

import com.caoccao.javet.annotations.V8Function
import com.caoccao.javet.interop.V8Runtime

class ScriptDimension(
    private val v8Runtime: V8Runtime,
    private val realObj: DimensionNode
) {
    @get:V8Function
    val name: String get() = realObj.name
}
```

When I inject this instance, my js script can only be used like this (accounts is the ScriptDimension instance I injected):
```js
accounts.getName()
```
These writings are not user-friendly, I hope they are:
```js
accounts.name
```

I checked the implementation of the code, and I found that there are only V8Function annotations, and I hope to add: V8Property annotations.
```kotlin
package kd.bos.olapServer

import com.caoccao.javet.annotations.V8Function
import com.caoccao.javet.interop.V8Runtime

class ScriptDimension(
    private val v8Runtime: V8Runtime,
    private val realObj: DimensionNode
) {
    @V8Property
    val name: String get() = realObj.name
}
```
What do you think of this idea?

**Comment by caoccao** [comment]
Thank you for raising this issue. That is in the plan. I guess I'll check it out in May.

And no worry, Chinese is my first class language. In the meanwhile, you may visit https://gitter.im/caoccao/Javet to contact me in real-time.

**Comment by caoccao** [comment]
That feature has been released. Please refer to this [doc](https://github.com/caoccao/Javet/blob/main/docs/reference/v8_function.rst) for detail.
