### ISSUE TITLE
How can I run asynchronously background task in V8?

### ISSUE THREAD

**Issue by wHoIsDReAmer** [caoccao/Javet#291]
Does not it support?

like this

```javascript
async function foo() {
    while (true) {
        // TODO SOME
        Thread.sleep(1000);
    }
}
foo();

// and can call another synchronous function
function test() {

}
```

```java
// Java
// ... after call foo function

test.call(null, null);
// but above code is not work
```
I know that javenode comes out already, but is there no way?

**Comment by caoccao** [comment]
Yes, you need to enable the V8 module. Project [Javenode](https://github.com/caoccao/Javenode) is a good example.

**Comment by caoccao** [comment]
The pattern is the same. The async capability is powered by `Promise`. That project demonstrates how to implement `Promise`.
