### ISSUE TITLE
Unexpected behavior for Strings when using the Bridge/Proxy Converter

### ISSUE THREAD

**Issue by bralax** [caoccao/Javet#295]
I recently noticed some weird behavior when working with the proxy or bridge converter in Javet.

Looking [here](https://github.com/caoccao/Javet/blob/main/src/main/java/com/caoccao/javet/interop/converters/JavetBridgeConverter.java#L52) we check if the object is a primitive and convert it to its matching primitive type but if it's an object type, then we proxy it.

Java strings are immutable objects which means that rather than getting V8ValueStrings for java strings we get proxied java string objects. This causes some super weird behavior when doing things like the spread operator as the object provided has non-string keys (even though they are actually strings).

I'm not sure if this the desired behavior or a bug but wanted to bring it up.

**Comment by caoccao** [comment]
The bridge converter wraps all Java primitives / objects. That includes `String`. Some native JS operations for sure break. That's the nature of the bridge converter.

If you feel there are some unexpected behaviors, do you mind leaving the sample code and your expected behaviors?

**Comment by anonyein** [comment]
> I recently noticed some weird behavior when working with the proxy or bridge converter in Javet.
> 
> Looking [here](https://github.com/caoccao/Javet/blob/main/src/main/java/com/caoccao/javet/interop/converters/JavetBridgeConverter.java#L52) we check if the object is a primitive and convert it to its matching primitive type but if it's an object type, then we proxy it.
> 
> Java strings are immutable objects which means that rather than getting V8ValueStrings for java strings we get proxied java string objects. This causes some super weird behavior when doing things like the spread operator as the object provided has non-string keys (even though they are actually strings).
> 
> I'm not sure if this the desired behavior or a bug but wanted to bring it up.

java String is not char, that you check is Primitive, what do you mean of the  spread operator?

**Comment by caoccao** [comment]
I'm sorry I still don't get what your expected behavior is. The bridge converter doesn't produce native JS string, so the spread operator for native JS string doesn't apply. Please show me the code.

**Comment by bralax** [comment]
Sorry. Was out during the day. Here's a sample with unexpected behavior:
```JAVA
import com.caoccao.javet.exceptions.JavetException;
import com.caoccao.javet.interop.V8Host;
import com.caoccao.javet.interop.V8Runtime;
import com.caoccao.javet.interop.converters.JavetBridgeConverter;
import com.caoccao.javet.values.reference.V8ValueFunction;

public class Test {

    public static void main(String[] args) throws JavetException {
        try (V8Runtime runtime = V8Host.getV8Instance().createV8Runtime()) {
            runtime.setConverter(new JavetBridgeConverter());
            V8ValueFunction function = runtime.createV8ValueFunction("(() => {const func = (javaObj) => {\n" +
                    "    console.log({...javaObj});\n" +
                    "};\n" +
                    "return func;})()");
            function.call(null, new TestClass(1));
        }
    }

    public static class TestClass {
        private Integer field;

        public TestClass(Integer field) {
            this.field = field;
        }

        public Integer getField() {
            return field;
        }

        public void setField(Integer field) {
            this.field = field;
        }
    }
}
```

My expectation and the expectation of javascript users is that this should print `{"field": 1}` but instead you get the following exception:

```
Exception in thread "main" com.caoccao.javet.exceptions.JavetExecutionException: TypeError: #<Object> is not a valid property name
	at com.caoccao.javet.interop.V8Native.call(Native Method)
	at com.caoccao.javet.interop.V8Runtime.call(V8Runtime.java:416)
	at com.caoccao.javet.interop.V8Internal.call(V8Internal.java:49)
	at com.caoccao.javet.values.reference.V8ValueFunction.callExtended(V8ValueFunction.java:97)
	at com.caoccao.javet.values.reference.IV8ValueFunction.call(IV8ValueFunction.java:50)
```

It's a common use case to immutably modify data by copying fields to a new object.

**Comment by caoccao** [comment]
Thank you for posting the sample code. I believe that's something Javet won't provide built-in support to.

# Why doesn't Javet Support That?

- A Java object via JS proxy is **NOT** a JS object. There are a lot of conflicts at API level. E.g. `forEach`, `toString`.
- JS doesn't allow overload, but Java allows overload. In Java, multiple methods can have the same method name, but different signatures. These overloaded methods cannot be cast to one JS function. That implies there is **NO** 1-to-1 mapping between the Java object and the JS object.
- Some magic JS operations rely on JS symbols that are completely absent in Java. E.g. `const a = { [Symbol.toPrimitive]: () => 'abc' }; console.log('' + a);` outputs `'abc'`. In your case, the spread operator relies on `Symbol.iterator` which is unknown to the Java object.

# What is the Solution?

I suggest you write your own converter that can fill those gaps. The converter design is very open for sub-classing. Please let me know if you have any questions.

**Comment by anonyein** [comment]
> Thank you for posting the sample code. I believe that's something Javet won't provide built-in support to.
> 
> # Why doesn't Javet Support That?
> * A Java object via JS proxy is **NOT** a JS object. There are a lot of conflicts at API level. E.g. `forEach`, `toString`.
> * JS doesn't allow overload, but Java allows overload. In Java, multiple methods can have the same method name, but different signatures. These overloaded methods cannot be cast to one JS function. That implies there is **NO** 1-to-1 mapping between the Java object and the JS object.
> * Some magic JS operations rely on JS symbols that are completely absent in Java. E.g. `const a = { [Symbol.toPrimitive]: () => 'abc' }; console.log('' + a);` outputs `'abc'`. In your case, the spread operator relies on `Symbol.iterator` which is unknown to the Java object.
> 
> # What is the Solution?
> I suggest you write your own converter that can fill those gaps. The converter design is very open for sub-classing. Please let me know if you have any questions.

Maybe conert to json by Gson or use protobuf more convenient

**Comment by caoccao** [comment]
> Maybe conert to json by Gson or use protobuf more conveniently, he made it too complex

There is no need to convert it to JSON. Please refer to this [doc](https://www.caoccao.com/Javet/reference/converters/object_converter.html#register-custom-objects) for detail.

**Comment by caoccao** [comment]
This issue is partially addressed by this [commit](https://github.com/caoccao/Javet/commit/14d282e2d161ced72ba6130b96da14caa8b67598). Please let me know if you have any questions.

**Comment by caoccao** [comment]
It'll be completely resolved in the upcoming release. Please stay tuned.
