### ISSUE TITLE
Node js not work in android

### ISSUE THREAD

**Issue by appt2** [caoccao/Javet#299]
hi im using your library for android node js not work

**Comment by caoccao** [comment]
Javet doesn't support Node.js on Android for now.

**Comment by appt2** [comment]
> Javet doesn't support Node.js on Android for now.

Will this problem be solved in the future?

**Comment by caoccao** [comment]
Someone friends tried it out. Please refer to #275 for details. They are with me in a WeChat group. Please let me know if you are interested in the discussion.

**Comment by caoccao** [comment]
Node.js for Android will be supported soon.

**Comment by appt2** [comment]
> Node.js for Android will be supported soon.

nice

**Comment by appt2** [comment]
@caoccao Can you add a feature like a Python interpreter, that is, I can give code to run the output, for example, in a terminal that I made myself, or a TextView

**Comment by caoccao** [comment]
I'm not sure what you mean. Better grab me at discord for details.

**Comment by caoccao** [comment]
Snapshot build is ready at Actions.

**Comment by appt2** [comment]
Sorry, I didn't understand anything at all from your library. I'm going to make a node.js ide so that my user enters code and displays it in an output, but I don't understand, how can you help me?

**Comment by caoccao** [comment]
Did you try JavetShell? It's an APK. You just install it and run it. It's a GUI that does what you describe.

**Comment by appt2** [comment]
> Did you try JavetShell? It's an APK. You just install it and run it. It's a GUI that does what you describe.

Yes, I saw it, but its language is Kotlin, I don't know Kotlin

**Comment by caoccao** [comment]
That's something I cannot help with.

**Comment by aiselp** [comment]
> Node.js for Android will be supported soon.

期待Android上的nodejs😘
