### ISSUE TITLE
警告: Received promise reject callback with event 0 PromiseRejectWithNoHandler.

### ISSUE THREAD

**Issue by miniphper** [caoccao/Javet#301]
[
![111](https://github.com/caoccao/Javet/assets/30486761/c9e52a75-4593-4c89-9629-e6b526827d0f)
](url)

![222](https://github.com/caoccao/Javet/assets/30486761/ca5ecad0-c10f-47ef-8a6e-c8e2fcaebd03)

![333](https://github.com/caoccao/Javet/assets/30486761/65ac68ce-a2de-480c-827f-93c8546a190b)

 V8Runtime v8Runtime = V8Host.getV8Instance().createV8Runtime();

**Comment by miniphper** [comment]
When using the module function of the V8 engine, error codes cannot provide error information

**Comment by caoccao** [comment]
Please refer to this [doc](https://www.caoccao.com/Javet/reference/v8_values/v8_promise.html#unhandled-rejection) for details.

**Comment by miniphper** [comment]
@caoccao thanks  
![77777](https://github.com/caoccao/Javet/assets/30486761/1818557d-55dc-4d77-891c-58c5d2ade4eb)
