### ISSUE TITLE
How to capture errors in Promise in Java?

### ISSUE THREAD

**Issue by rongrong1000** [caoccao/Javet#302]
``` java
    public static void main(String[] args) {
        try (V8Runtime v8Runtime = V8Host.getNodeInstance().createV8Runtime()) {
            v8Runtime.getExecutor("""
                async function a() {
                	bbb()
                }
                
                a()
                """).execute();
        } catch (Throwable e) {
            e.printStackTrace();
        }
    }
```

If an error occurs, the JVM will shut down

If the content of JavaScript is not controlled

What should I do?

Thanks

**Comment by caoccao** [comment]
You may get it by the `Promise` returned by that `execute()`, and you must call `await()` to pump the event loop so that V8 can actually process the async task queue.

Please refer to this [doc](https://www.caoccao.com/Javet/reference/v8_values/v8_promise.html) for detail.

**Comment by rongrong1000** [comment]
Thank you very much. The problem has been resolved.

**Comment by rongrong1000** [comment]
Can I still know his `sourceLine` and `resource` and `startColumn` and `endColumn` for this situation, i need them

The error type I have captured now is ` V8ValueError`

**Comment by caoccao** [comment]
Yes, it has all you need. Please refer to this [file](https://github.com/caoccao/Javet/blob/main/src/test/java/com/caoccao/javet/exceptions/TestJavetExecutionException.java) for details.

**Comment by rongrong1000** [comment]
Thank you very much for your help
