### ISSUE TITLE
How to obtain the value of 'error. code' in Java

### ISSUE THREAD

**Issue by rongrong1000** [caoccao/Javet#307]
In Java
```
public static void main(String[] args) {
        try {
            V8Runtime v8Runtime = V8Host.getNodeInstance().createV8Runtime();
            v8Runtime.getExecutor("""
                    require('nohave')
                    """).executeVoid();
        } catch (JavetException e) {
            e.printStackTrace();
        }
    }
```
I have 'JavetException e', how can I obtain the value of 'code'

In Nodejs
```
try {
	require('nohave')
} catch (e) {
	console.log('code: ' + e.code)
}
```
print: code: MODULE_NOT_FOUND

**Comment by rongrong1000** [comment]
I found it in 'e.getScriptingError(). getContext() .getContext()'

Does it have the potential to become a property of 'JavetScriptingError'

**Comment by rongrong1000** [comment]
![code](https://github.com/caoccao/Javet/assets/77261556/a0df363e-6f7f-43bb-9f23-15fe763f01d1)

I believe that 'message', 'stack', and 'code' have the same status

'JavetScriptingError' has' message 'and' stack ', but no' code '

**Comment by caoccao** [comment]
Everything is in the context. `code` doesn't exist in ECMAScript, so there is no API level support.
