### ISSUE TITLE
com.sun.javafx.collections not exported in javafx.base

### ISSUE THREAD

**Issue by Vexcited** [caoccao/Javet#315]
Hey ! I've been hitting an issue with my JavaFX app in Javet recently,

```console
Error: Callback clear failed with error message class com.caoccao.javet.interop.proxy.ScoredExecutable cannot access class com.sun.javafx.collections.VetoableListDecorator (in module javafx.base) because module javafx.base does not export com.sun.javafx.collections to unnamed module @27f6bb16
```

---

I initialize my V8 (not Node) instance with the following : 

```java
V8Runtime v8Runtime = V8Host.getV8Instance().createV8Runtime();

JavetBridgeConverter javetBridgeConverter = new JavetBridgeConverter();
v8Runtime.setConverter(javetBridgeConverter);

JavetJVMInterceptor javetJVMInterceptor = new JavetJVMInterceptor(v8Runtime);
javetJVMInterceptor.register(v8Runtime.getGlobalObject());

v8Runtime.getExecutor("globalThis.java = javet.package.java").executeVoid();
v8Runtime.getExecutor("globalThis.javafx = javet.package.javafx").executeVoid();

// then i executeVoid() my index.mjs file (with module mode)
```

Finally, on the JavaScript end, I just have

```typescript
const vBox = new javafx.scene.layout.VBox();
const children = vBox.getChildren();
children.clear();
```

And when running, I get the error I gave at the start of this issue.

---

Also, I found [an issue on jruby that talks about the same thing](https://github.com/jruby/jruby/issues/6287) and it somehow got fixed apparently.

Appending the following to my `pom.xml` fixes the issue though, but I guess it's just a workaround ?

```xml
<plugin>
  <groupId>org.openjfx</groupId>
  <artifactId>javafx-maven-plugin</artifactId>
  <version>${javafx.maven.plugin.version}</version>
  <configuration>
    <mainClass>${javafx.mainClass}</mainClass>
    <options>
      <option>--add-exports</option>
      <option>javafx.base/com.sun.javafx.collections=ALL-UNNAMED</option>
    </options>
  </configuration>
</plugin>
```

**Comment by caoccao** [comment]
Thank you for raising this issue. Other Javet uses met this issue as well. `--add-exports` seems to be the best solution.

From Java 9, the module design enforces the applications to explicitly `--add-exports` to those protected modules whereas libraries like Javet, JRuby have no way of accessing those modules illegally. What JRudy patched was just ignoring the non-exported API, which would result in another error like `TypeError: clear is not a function`.

So I made the decision long time ago not to apply the patch that JRuby did for the following reasons.

1. The error is inevitable.
2. The current behavior is more informative in terms of finding the `--add-exports` solution.

Please let me know if you have any questions.

**Comment by Vexcited** [comment]
I see !

Since I just started to learn Java, I thought it was something on Javet side but if it's a Java issue, then we can't do anything else, I guess.

Thanks you for the time you spent on replying (and how quick it was) !
I'll keep the `add-exports` method since it's the best way of doing it.

Thanks again (I don't think I have any questions, and if I have, I'll probably ask in the Discord) !
I'll close the issue.
