### ISSUE TITLE
Load the class of the external jar

### ISSUE THREAD

**Issue by AsyncProxy** [caoccao/Javet#324]
When I use URLClassLoader and Class.forName to load the class of the external jar, how do I get JavetProxyConverter to do the automatic proxy? (although I can do it myself, but I think it can be auto-proxy)

**Comment by caoccao** [comment]
Could you leave a repo with the minimal reproducible code?

**Comment by AsyncProxy** [comment]
![1](https://github.com/caoccao/Javet/assets/85269966/90d66210-2612-49f3-b1cf-9c4accf3d4ff)
![2](https://github.com/caoccao/Javet/assets/85269966/e6e83491-88ff-4b07-8bbc-e6aa5084e041)
![3](https://github.com/caoccao/Javet/assets/85269966/3c9570c8-e7ca-4c7d-ba78-98b330104f12)

This is how I write it, I first load the outer jar in the normal way, and load the classes inside, className is the example

**Comment by AsyncProxy** [comment]
![1](https://github.com/caoccao/Javet/assets/85269966/cba41721-4b59-455e-b9c3-61679a6b48c6)
![2](https://github.com/caoccao/Javet/assets/85269966/9b77c18b-a2cf-4896-957a-720a57d600f9)
![3](https://github.com/caoccao/Javet/assets/85269966/941c2348-1e7c-41f3-82e6-af44d53d7f17)

This is how I write it, I first load the outer jar in the normal way, and load the classes inside, className is the example

**Comment by caoccao** [comment]
Kotlin classes are not standard Java classes. Javet is at JDK 8 for backward compatibility reason, so it doesn't recognized the Kotlin classes.

**Comment by AsyncProxy** [comment]
> Kotlin 类不是标准的 Java 类。出于向后兼容性的原因，Javet 在 JDK 8 上，因此它无法识别 Kotlin 类。

https://github.com/caoccao/Javet/issues/324#issuecomment-2080814450,I mean load the class of the external jar and expect the proxy to be able to proxy it

**Comment by caoccao** [comment]
> > Kotlin 类不是标准的 Java 类。出于向后兼容性的原因，Javet 在 JDK 8 上，因此它无法识别 Kotlin 类。
> 
> [#324 (comment)](https://github.com/caoccao/Javet/issues/324#issuecomment-2080814450) mean load the class of the external jar and expect the proxy to be able to proxy it

There are details you didn't disclose. That's why I need a repo with all the code.

**Comment by AsyncProxy** [comment]
> > > Kotlin 类不是标准的 Java 类。 出于向后兼容性的原因，Javet 在 JDK 8 上，因此它无法识别 Kotlin 类。
> > 
> > 
> > [#324 （注释）](https://github.com/caoccao/Javet/issues/324#issuecomment-2080814450) 意味着加载外部 jar 的类并期望代理能够代理它
> 
> 有些细节你没有透露。这就是为什么我需要一个包含所有代码的存储库。

I tested, I used my code on Verskold to test that the class that loads Hal loads works fine, but you get an error output Eero: Karl Bachlo Fryder Waith Eero Mesag 'Trodesistep Ben Krasfeld

My test code:`import java.io.File;
import java.io.IOException;
import java.net.*;

public class Mian {
    public static void main(String[] args) throws ClassNotFoundException {
        loadJar("./API.jar");
    }

    public static void loadJar(String jar) {
        try {
            File file = new File(jar);
            URL url = file.toURI().toURL();
            URLClassLoader loader = new URLClassLoader(new URL[]{url});

            System.out.println(loader.loadClass("com.tools.api.test"));
        } catch (IOException | ClassNotFoundException E) {E.printStackTrace();}
    }
}
`

Vscode: class com.tools.api.test
Android: Callback loadJar failed with error message can't load this type of class file

**Comment by AsyncProxy** [comment]
> > > Kotlin 类不是标准的 Java 类。 出于向后兼容性的原因，Javet 在 JDK 8 上，因此它无法识别 Kotlin 类。
> > 
> > 
> > [#324 （注释）](https://github.com/caoccao/Javet/issues/324#issuecomment-2080814450) 意味着加载外部 jar 的类并期望代理能够代理它
> 
> 有些细节你没有透露。这就是为什么我需要一个包含所有代码的存储库。

我现在使用DexClassLoader成功加载了dex，但是我想希望您实现类被加载到内存当中，自动代理该类，或者提供某个接口来允许我手动代理该类

**Comment by caoccao** [comment]
Everything is stored in `ClassDescriptorStore`. You can register arbitrary classes there.

**Comment by AsyncProxy** [comment]
> 所有内容都存储在 .您可以在那里注册任意类。`ClassDescriptorStore`

ClassDescriptorStore.getClassMap().put(clazz, new ClassDescriptor(V8ProxyMode.Class, clazz, ?));
I'm not very familiar with this API, how do I write the last plugin

**Comment by caoccao** [comment]
Without the a repo, my help is limited.

**Comment by AsyncProxy** [comment]
> 没有回购，我的帮助是有限的。

Thank you, my friend, I solved it by manually registering and it works normally, but I personally feel a bit cumbersome
