### ISSUE TITLE
process.exit Engine Error

### ISSUE THREAD

**Issue by AsyncProxy** [caoccao/Javet#325]
`try {
            V8Node.getExecutor("process.exit(0)").executeVoid();
        } catch (JavetException e) {
            e.printStackTrace();
        }`

Executing "process.exit()" will cause the engine to report an error directly

**Comment by caoccao** [comment]
This call is not supposed to be supported in Javet because of the Javet design.

**Comment by AsyncProxy** [comment]
So can I only block it manually？

**Comment by caoccao** [comment]
Please try [JavetSanitizer](https://github.com/caoccao/JavetSanitizer) or [swc4j](https://github.com/caoccao/swc4j) that provides the AST analysis if you want to block it.

**Comment by AsyncProxy** [comment]
> 如果您想阻止它，请尝试提供 AST 分析的 [JavetSanitizer](https://github.com/caoccao/JavetSanitizer) 或 [swc4j](https://github.com/caoccao/swc4j)。

Then I also want to ask, is there an API that can serialize and print your V8ValueObject, that is, it is returned with the object, and finally it is a string, and all the properties are displayed, not [object Object] like that, and don't encounter toJsonString, if {} has an unrecognized object (function or the like), return {} like this

**Comment by caoccao** [comment]
Or, just simply run the following.

```js
> delete process.exit
true
> process.exit(0)
Uncaught TypeError: process.exit is not a function
```

**Comment by AsyncProxy** [comment]
> 或者，只需运行以下命令即可。
> 
> ```js
> > delete process.exit
> true
> > process.exit(0)
> Uncaught TypeError: process.exit is not a function
> ```

I guess it would be better for me to rewrite the exit method myself to be compatible, but is there a solution to this problem https://github.com/caoccao/Javet/issues/325#issuecomment-2081832121
