### ISSUE TITLE
Serialize the object

### ISSUE THREAD

**Issue by AsyncProxy** [caoccao/Javet#328]
You can add an API to implement Node.js kind of console.log print object, serialize all data objects in it, instead of displaying [object object], and toJsonString, when you encounter a function or an unrecognized object in the object, you can't convert it

**Comment by aiselp** [comment]
你可以用nodejs模块`util`格式化之后再发送给java

**Comment by AsyncProxy** [comment]
> 你可以用nodejs模块`util`格式化之后再发送给java

Oops, I'm really stupid, I actually forgot to have a util module, you look at my memory, haha, thank you!
