### ISSUE TITLE
Sequence interface

### ISSUE THREAD

**Issue by AsyncProxy** [caoccao/Javet#338]
Can you implement a serialization interface for your engine interface, I need to pass objects across processes, but you don't seem to support serialization

**Comment by caoccao** [comment]
Please try V8 snapshot. Otherwise, it's technically impossible.

**Comment by AsyncProxy** [comment]
> Please try V8 snapshot. Otherwise, it's technically impossible.

If that doesn't work, I'll have to run it in a process, but Node.js if I run into an endless loop during the execution process, and the Java side calls the engine's close method can't force the engine down, can I redesign this method?
