### ISSUE TITLE
Restore the exit

### ISSUE THREAD

**Issue by AsyncProxy** [caoccao/Javet#348]
process.exit can force exit, can you redesign this API, I need it, I don't want to rewrite it for the killProcess of the android method.

**Comment by caoccao** [comment]
`process.exit = () => {}`

**Comment by AsyncProxy** [comment]
> `process.exit = () => {}`

You may be mistaken about what I mean, but I mean, you can redesign the API in Javet so that it exits the engine like a pure Node.js.
