### ISSUE TITLE
How to call async functions

### ISSUE THREAD

**Issue by sebdomdev** [caoccao/Javet#349]
I'm starting a node server (that keeps running) and I have some async functions that I would like to call. Starting the server works but I can't seem to find a way to call the async functions and get a result.

I have function is async and is supposed to return a string. From what I can tell, the only way to call a function is to use V8Runtime.globalObject.get("functionName").call... . 

However, when I call the function that way, I'm getting a string "[object Promise]" back. When I try to cast it to a IV8ValuePromise (using V8Runtime.globalObject.get<V8ValueFunction>("functionName").callObject<IV8ValuePromise>(null) I'm getting a ClassCastException saying that java.util.HashMap cannot be cast to IV8ValuePromise.

I found this documentation https://www.caoccao.com/Javet/reference/v8_values/v8_promise.html but it seems to apply only to the opposite way of calling promises (i.e. turning java code into a promise that can be called from the NodeJS server).

Is there any way to call an async NodeJS function (or one returning a JavaScript Promise) from Java and get a result back?

**Comment by caoccao** [comment]
Calling asyn functions is tricky. You cannot cast it to a Java object, for now. Instead, you have to get it as `V8ValuePromise`, then pump the event loop by calling `await()`.

Please refer to the [test cases](https://github.com/caoccao/Javet/blob/main/src/test/java/com/caoccao/javet/values/reference/TestV8ValuePromise.java) for detail.

By the way, I plan to convert `Promise` to `CompletableFuture`, but am still hesitating.

**Comment by sebdomdev** [comment]
Thanks for responding so quickly. I tried looking at the test cases but they only show me how V8ValuePromise works, not how to get one from the runtime when calling the async function.

When I try to return a V8ValuePromise, like you suggested (with "runtime.globalObject.get<V8ValueFunction>("functionName")"), I'm getting the following exception:

java.lang.ClassCastException: com.caoccao.javet.values.reference.V8ValueFunction cannot be cast to com.caoccao.javet.values.reference.V8ValuePromise

How can I get a V8ValuePromise from a V8ValueFunction?

Your help is much appreciated!

**Comment by caoccao** [comment]
Please try to replace `get()` with `invoke()`.

**Comment by sebdomdev** [comment]
Awesome, that worked! Thank you so much!!!
