### ISSUE TITLE
[Feature] Proxied Java Class Can be Extended by JS Class

### ISSUE THREAD

**Issue by AsyncProxy** [caoccao/Javet#355]
Java classes cannot be inherited by JS classes to override methods.

**Comment by caoccao** [comment]
It'll take 40 hours to implement this feature. Who is going to sponsor the development?

**Comment by AsyncProxy** [comment]
> It'll take 40 hours to implement this feature. Who is going to sponsor the development?

If this feature can be realized, I am willing to sponsor the development, please give me the sponsorship channel!

**Comment by AsyncProxy** [comment]
> It'll take 40 hours to implement this feature. Who is going to sponsor the development?

I've tried imitation and it works, but it doesn't work well.
