### ISSUE TITLE
可以加载mysql库吗？

### ISSUE THREAD

**Issue by chenddcoder** [caoccao/Javet#358]
@Test
    public void testLoadModule() throws JavetException {
        File decimalJSFile = new File(
                JavetOSUtils.WORKING_DIRECTORY,
                "node_modules/mysql/index.js");
        if (decimalJSFile.exists() && decimalJSFile.canRead()) {
            System.out.println("Loading "+ decimalJSFile.getAbsolutePath());
            V8Runtime v8Runtime = V8Host.getNodeInstance().createV8Runtime();
            v8Runtime.getExecutor(decimalJSFile).executeVoid();
        } else {
            System.out.println(decimalJSFile.getAbsolutePath()+"{0} is not found.");
            System.out.println("Please make sure Node.js is installed, then visit script/node directory and run npm install.");
        }
    }
加载mysql库会抛出这个异常
com.caoccao.javet.exceptions.JavetExecutionException: ReferenceError: exports is not defined

	at com.caoccao.javet.interop.V8Native.scriptExecute(Native Method)
	at com.caoccao.javet.interop.V8Runtime.execute(V8Runtime.java:1056)
	at com.caoccao.javet.interop.executors.V8StringExecutor.execute(V8StringExecutor.java:107)
	at com.caoccao.javet.interop.IV8Executable.executeVoid(IV8Executable.java:192)
是否有方案解决

**Comment by caoccao** [comment]
Why do you run scripts under `node_modules`? That doesn't seem to be a common practice. Here are some suggestions.

1. Put your script in another folder.

```
├── node_modules
└── test.js
```

2. Make sure the script runs well in Node.js, then try Javet.
3. [Patch the native lib](https://www.caoccao.com/Javet/reference/resource_management/modularization.html).

**Comment by chenddcoder** [comment]
嗯，我试试

**Comment by chenddcoder** [comment]
可以的，谢谢
