### ISSUE TITLE
setPurgeEventLoopBeforeClose

### ISSUE THREAD

**Issue by aiselp** [caoccao/Javet#361]
I found that `setPurgeEventLoopBeforeClose` has been deleted. Is there any alternative method?

**Comment by aiselp** [comment]
```js
let i = 0
setInterval(() => {
  i++;
  if (i>5){
    process.exit()
  }
}, 1000);
```
In the current situation, even if nodeRuntime is closed and the await call has exited, the code will continue to run.

**Comment by caoccao** [comment]
That's the nature of Node.js. If you run the same code in Node.js, it keeps running as well.

**Comment by aiselp** [comment]
Understand, Java applications are usually executed in a single process, while NodeJS is multi-process

**Comment by caoccao** [comment]
The following API has been added to address this issue. I believe it will resolve the issue you met. Please wait for the next release and let me know if you have any questions.

```java
NodeRuntime.isStopping()
NodeRuntime.setStopping()
```

**Comment by aiselp** [comment]
I'm not sure why the previous `setPurgeEventLoopBeforeClose` was deleted. If it's because multiple NodeRuntimes share a single node event loop, then this method may not solve the fundamental problem. I'm worried that the remaining events may continue to run in other NodeRuntimes.
My current solution is to get all ids by modifying the `setTimeout` related functions, and finally clear them all when closing the NodeRuntime

**Comment by caoccao** [comment]
It was a complete redesign in Javet, so that API was removed as part of the old design.

Just try the snapshot one. The event loop is skipped completely.

**Comment by aiselp** [comment]
Great, that's definitely a better way

**Comment by aiselp** [comment]
There is another problem I am currently facing. After creating an es module, I want to set some content on `import.meta`, but I have no way to get this object

**Comment by caoccao** [comment]
Please create another issue with detailed info, or ping me at discord.
