### ISSUE TITLE
[BUG] SIGSEGV when returning a newly created V8ValueObject to JavaScript on linux

### ISSUE THREAD

**Issue by NGSpace** [caoccao/Javet#362]
Hello, I recently made the switch to linux and started testing one of my projects on linux, I had previously done most of my testing on windows. Since the "problematic" project was made in Java it was a pretty smooth transition, except for thing, one of my tests failed, after narrowing it down I found that 2 of the JavaScript functions I had implemented caused a SIGSEGV when executed, both of which returned non-primitive objects (not strings, ints or booleans). However, the creation of the object itself (which is done by my code) is not the part that causes the crash, after a little more testing I found that returning the object is what caused the crash.

I noticed that running the "toString()" method after creating the object, it returns "Runtime is already closed". after a bit of checking I found out the "close" function is infact not called early (at least not by my own code). which made me come to the conclusion that it is not my own code that is causing the issue, however I may be wrong.

If it helps, you can see my function implementations here: https://github.com/NGSpace/hudder/blob/main/src/main/java/io/github/ngspace/hudder/compilers/JavaScriptCompiler.java
and my Object converter here: https://github.com/NGSpace/hudder/blob/main/src/main/java/io/github/ngspace/hudder/compilers/JavetObjConverter.java

However a lot of it is related to other parts of the objects so I will try to highlight the important parts:

The faulty javascript function:
```java
    	Func<Exception> func = s->{
    		V8ValueObject newobj = engine.createV8ValueObject();
    		Hudder.log("TTTTTh"+ newobj.toProtoString());
    		
    		
    		var r =  new JavetObjConverter().toV8Value(engine, Hudder.ins.player.getInventory().getStack(s[0].asInt()));
    		Hudder.log("The ");
    		Hudder.log("The " + r.toString());
    		
    		return r;
    	};
    	
    	gb.bindFunction(new JavetCallbackContext("getItem", DirectCallThisAndResult, func));
```

The JavetObjectConverter (extends JavetProxyConverter):
```java
	@SuppressWarnings("unchecked")
	@Override
	public V8Value toV8Value(V8Runtime engine, Object object, int depth)
			throws JavetException {
		if (object instanceof CompileResult c) {
			try (V8ValueObject newobj = engine.createV8ValueObject()) {
				newobj.set("topleft", c.TopLeftText,
						"bottomleft", c.BottomLeftText,
						"topright", c.TopRightText,
						"bottomright", c.BottomRightText,
						"topleftscale", c.TLScale,
						"bottomleftscale", c.BLScale,
						"toprightscale", c.TRScale,
						"bottomrightscale", c.BRScale);
				return newobj;
			}
		}
		if (object instanceof ItemStack stack) {
			try (V8ValueObject newobj = engine.createV8ValueObject()) {
				Hudder.log("r");
				newobj.set("name", stack.getName().getString());
				Hudder.log("rr");
				newobj.set("durability", stack.getMaxDamage()-stack.getDamage());
				newobj.set("maxdurability", stack.getMaxDamage());
				newobj.set("count", stack.getCount());
				newobj.set("maxcount", stack.getMaxCount());
				Hudder.log("rr");
				return newobj;
			}
		}
		if (object instanceof V8ValueObject) {Hudder.log("Tr");return (V8ValueObject) object;}
		return super.toV8Value(engine, object, depth);
	}
```

I'm sorry if this is too long...

**Comment by caoccao** [comment]
You cannot return a V8 value object in a try-with-resource. That for sure results in core dump.

**Comment by NGSpace** [comment]
Huh... I understand the issue but that means windows was the faulty one? why didn't I encounter this on Windows? It should have also crashed?

Also I feel real dumb right now...

**Comment by caoccao** [comment]
I guess you were just lucky as the GC kicking time is kind of OS related.

**Comment by NGSpace** [comment]
Huh... this is pretty bad...
