### ISSUE TITLE
是否可以设置node:fs权限限制策略

### ISSUE THREAD

**Issue by chenddcoder** [caoccao/Javet#363]
const fs=require('node:fs')
const files = fs.readdirSync('./');
const filePath = './newFile.txt';
fs.writeFile(filePath, '这是新文件的内容', (err) => {
    if (err) {
        console.error('文件创建时发生错误:', err);
    } else {
        console.log('文件创建成功！');
    }
});
fs.unlink(filePath, (err) => {
    if (err) {
        console.error('删除文件时出错:', err);
    } else {
        console.log('文件删除成功！');
    }
});

我发现fs可以创建成功文件，并且可以删除文件，能否配置javet的访问权限，例如不允许删除文件

**Comment by caoccao** [comment]
You may pass console arguments to Node.js. This is the standard way. Javet doesn't make changes to the Node.js source code.
