### ISSUE TITLE
是否支持配置console.log的打印输出？

### ISSUE THREAD

**Issue by chenddcoder** [caoccao/Javet#364]
console.log的打印内容，我通过日志无法看到，是否支持配置打印到指定文件中

**Comment by caoccao** [comment]
You will have to do that by yourself. Please go over the tutorials.

**Comment by rongrong1000** [comment]
我也遇到了此问题, 不过我选择了重写console.log 然后 包装成js对象, 在替换原有的log 函数, 这是可行的, 我一直在这样用
