### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by xiaoye-2018** [caoccao/Javet#375]
Why is this project less efficient than j2v8? It is also V8, and the code executed here is simple. Is it because of the complex structure of Javet design? I read the source code briefly, but didn't find any conclusions. Can you tell me the specific reasons?

 The code is as follows

``` java

public class PerformanceTest {

    public static void main(String[] args) throws Exception {
        javet_v8(); // 3195
        j2v8(); // 755
    }

    private static void j2v8() {
        V8 runtime = V8.createV8Runtime();
        runtime.add("key", "key1");
        runtime.add("key2", "key2");
        long l = System.currentTimeMillis();
        for (int i = 0; i < 1000000; i++) {
            String s = runtime.executeStringScript("key + key2;");
            // System.out.println(s);
        }
        System.out.println(System.currentTimeMillis() - l);
        runtime.release();
    }

    private static void javet_v8() {
        // Step 1: Create a V8 runtime from V8 host in try-with-resource.
        try (V8Runtime v8Runtime = V8Host.getV8Instance().createV8Runtime()) {
            V8Locker v8Locker = v8Runtime.getV8Locker();
            V8ValueGlobalObject globalObject = v8Runtime.getGlobalObject();
            globalObject.set("key", "user");
            globalObject.set("key2", "user");
            IV8Executor executor = v8Runtime.getExecutor("key + key2;");
            long l = System.currentTimeMillis();
            for (int i = 0; i < 1000000; i++) {
                String s = executor.executeString();
            }
            System.out.println(System.currentTimeMillis() - l);
            v8Locker.close();
        } catch (JavetException e) {
            throw new RuntimeException(e);
        }
    }
}
```

![image](https://github.com/user-attachments/assets/574e6373-c57c-41bd-afc9-4938c71e4f29)

**Comment by caoccao** [comment]
The lib loading takes time. You are actually testing the lib loading time. V8 is getting larger and larger so that loading the lib takes longer time. Comparing a modern V8 with a tiny 8 years old V8 doesn't prove anything, unless someone enjoys running production code in that 8 years old V8.

**Comment by xiaoye-2018** [comment]
The code here only calculates the time to execute the script. The initialization time above is not included. I just want to test the performance of executing simple js. Is there any problem with my test? @caoccao

**Comment by caoccao** [comment]
1. Please leave a repo with the complete code.
2. The V8 version gap is so huge so that the conclusions are meaningless.
3. The use case is meaningless in the real world.

**Comment by xiaoye-2018** [comment]
1. The above code is complete
2. What's the point of upgrading if the new upgraded version results in lower operating efficiency?
3. This example really has no meaning in reality. I just wrote it to simplify JS to test. In fact, we use JS in our project only to convert Java objects into appropriate business objects according to the relevant JS configuration. I have tested that the efficiency is still lower than J2V8.

**Comment by caoccao** [comment]
If your CPU is Intel or AMD (desktop or mobile), there's a technology called [Turbo Boost](https://www.intel.com/content/www/us/en/gaming/resources/turbo-boost.html).

Whatever you put at the beginning of your test runs slow because the turbo boost is not trigger. After the first call, the OS realizes the workload is high and turns on the turbo boost so that the second call runs much faster.

If you don't leave a repo with complete code and describe the test env, I cannot help with the issue. I seldom see people loving an 8 years old lib.
