### ISSUE TITLE
hwo to register a class

### ISSUE THREAD

**Issue by lovelyjpw** [caoccao/Javet#38]
function _test()
{
	var _pt = new JavaPoint;
	_pt.x = 20;
	_pt.y = 30;
	var pt2 = new JavaPoint(78,69);
}

what shoud I do to define JavaPoint in Java?
is like @V8Function named @V8Class?

@Data
@AllArgsConstructor
@NoArgsConstructor
@V8Class?
public class JavaPoint {
    private int x;
    private int y;
}

thanks

**Comment by caoccao** [comment]
Are you using Lombok? For now, Javet is not compatible with Lombok. But, I wonder if you could tweak Lombok plug-in to generate the annotation needed by Javet.

**Comment by iGabyTM** [comment]
> Are you using Lombok? For now, Javet is not compatible with Lombok. But, I wonder if you could tweak Lombok plug-in to generate the annotation needed by Javet.

Alright but how is this done without Lombok? Also, is there anything like a wiki on how to bind properties and such or just the java/test module?

**Comment by caoccao** [comment]
> > Are you using Lombok? For now, Javet is not compatible with Lombok. But, I wonder if you could tweak Lombok plug-in to generate the annotation needed by Javet.
> 
> Alright but how is this done without Lombok? Also, is there anything like a wiki on how to bind properties and such or just the java/test module?

Please refer to this [tutorial](https://github.com/caoccao/Javet/blob/main/docs/tutorial/interception.rst) for how to bind properties and functions. And, if you check the source code out, you will find the Javet API is open to creating your own annotation.

**Comment by iGabyTM** [comment]
Maybe I don't get it, but I'm asking how to register a class so I could create new instances in javascript.

**Comment by caoccao** [comment]
> Maybe I don't get it, but I'm asking how to register a class so I could create new instances in javascript.

Hope this [tutorial](https://github.com/caoccao/Javet/blob/main/docs/tutorial/object_converter.rst) is what you want.
