### ISSUE TITLE
Why can't we determine the primitive type first?

### ISSUE THREAD

**Issue by xiaoye-2018** [caoccao/Javet#380]
Most of the js executed in our project get some primitive types, such as string, number, etc. Is there a way to judge in advance
![image](https://github.com/user-attachments/assets/67b4ba6c-1cb1-4a1a-8361-b9cc3911e8da)

**Comment by caoccao** [comment]
1. Getting primitive properties from a V8 object doesn't hit this code path. These calls are optimized with direct type conversion without `if-else`.
2. Some reference types can also be primitive types so that they must go through the reference type checks firstly.

**Comment by xiaoye-2018** [comment]
If there are too many invalid judgments, will it affect performance? Can you give an example to illustrate whether the reference type includes the original type? Are some complex return types really used in actual applications?

**Comment by xiaoye-2018** [comment]
I consult GPT and conclude that there will be no problem if you first determine the original type.
