### ISSUE TITLE
How to call java Class from javascript without preinjection ?

### ISSUE THREAD

**Issue by changkejun** [caoccao/Javet#382]
At nashorn, I can call java from javascript like the next sample. Any java class can be called with the "Packages" or "java" keyword. At the sample, FileInputStream and FileManager are java class.
```js
var br = new java.io.FileInputStream(Packages.efw.file.FileManager.get(this._path));
```
At javet, I know I can inject a class in java and use it in javascript. 
https://www.caoccao.com/Javet/tutorial/advanced/java_and_javascript_interop.html

Is there a way to call any java class from javascript without preinjection like nashorn?

**Comment by caoccao** [comment]
Please follow this [tutorial](https://www.caoccao.com/Javet/tutorial/advanced/access_the_whole_jvm.html).

**Comment by changkejun** [comment]
Thank you for your link.  There is the code in your sample.
```java
v8Runtime.getExecutor("let java = javet.package.java").executeVoid();
```
Does it mean I can call my self java class package like the next code ?
```java
v8Runtime.getExecutor("let Mypkg = javet.package.mypkg").executeVoid();
```

**Comment by caoccao** [comment]
Yes.
