### ISSUE TITLE
Issue with calling java function with String[] param from javascript

### ISSUE THREAD

**Issue by changkejun** [caoccao/Javet#383]
I am puzzled about how to do with the String[] type param in javet javascript for java function. Would you give me some advice ? The next is my code.

```java
public final class FileManager {
	public static void zip(
		String toZipPath,  
		boolean toZipPathIsAbs, 
		String[] fromFilePaths, 
		String basePath, 
		boolean basePathIsAbs) throws IOException{
	 ...
	}
}
```
```js
console.log(newFile);
console.log(isAbs);
console.log(files);
console.log(parentPath);
console.log(isAbs);
javet.package.efw.file.FileManager.zip(newFile,isAbs, files, parentPath,isAbs);
//---------------the debug output is the next. The zip function does not run.--------------
/*
upload/startup.bat.zip
false
["upload/startup.bat"]
upload
false
*/
```
I found the info from the help document. Does it means I must change the java function param from 
String[] to ArrayList ?
![image](https://github.com/user-attachments/assets/237289d8-4152-4e1a-b658-37ab2973f7a0)

**Comment by caoccao** [comment]
Please check #351 out. `Object.seal()` can help with that.
