### ISSUE TITLE
Lambda object support?

### ISSUE THREAD

**Issue by lijinhong11** [caoccao/Javet#384]
Just set the lambda objects directly in global object and convert them to a JS function. Can you do it?

**Comment by caoccao** [comment]
Please check this [doc](https://www.caoccao.com/Javet/reference/v8_values/v8_function.html) out.

**Comment by lijinhong11** [comment]
is there a way to host multi script files?
Some functions worked but other script files don't have it.
weird

**Comment by caoccao** [comment]
I don't seem to understand your question.

**Comment by lijinhong11** [comment]
1. How to manage many script files at the same time
2. Some functions defined in some script files, but others don't have the function

**Comment by caoccao** [comment]
Please check this [doc](https://www.caoccao.com/Javet/reference/resource_management/modularization.html) out.
