### ISSUE TITLE
[Feature Request] Add an argument to @V8Property annotation to use as a getter or setter in JS.

### ISSUE THREAD

**Issue by colonelpopcorn** [caoccao/Javet#391]
I don't know if there's a way to do this currently, but right now I am trying to port Chai and some of Postman's scripting features over to a Java library for testing Postman collections. However, there is a nuanced use case in trying to implement these libraries using Javet. The issue is when I annotate a method with the `@V8Property`, but I cannot invoke as I would a JavaScript getter function. Consider the following JavaScript:

```javascript
pm.test("Should accept all mime types", () => {
    // This line here                              vvvv
    pm.expect(pm.response.json().headers["Accept"]).to.equal("*/*");
    pm.expect().throw();
});

pm.test("Should have a host of httpbin.org", () => {
    // This line here                            vvvv
    pm.expect(pm.response.json().headers["Host"]).to.eq("httpbin.org");
});

pm.collectionVariables.set("amzn_trace_id", pm.response.json().headers["X-Amzn-Trace-Id"]);
```
In this example above, I expect the `expect` function to return an object. This object then has multiple methods on it that return itself in order to chain english words together. I would like these methods to be accessible as getters in JavaScript so that I don't have to explicitly call the method in JavaScript. While I'm at it I think we could do something similar for setters. Consider the following Java class:

```java
public class PostManJSRuntime {
    @V8Property
    public PostmanJSVariablePool expect(final Object actual) {
        return new Expector(actual)
    }
    
}
public class Expector {
    private final Object actual;
    public Expector(final Object actual) {
      this.actual = actual;
    }
    
    @V8Property
    public Expector to() {
      // I expect to be able to call this in JavaScript as a getter like so
      // `rootObject.to.be.equal("some value")`
      return this;
    }
    
    @V8Property
    public Expector not() {
      return this;
    }
    
    @V8Property
    public Expector be() {
      return this;
    }
    
    public Expector equal(final Object expected) {
      // Compare actual with expected, throw error if not equal (check with negation first)
      return this;
    }
}
```

I'm not sure if this able to implemented as a proxy plugin and if it is some guidance would be greatly appreciated. If not, my thought is to include a flag on the annotation. Something like `useJSGetter` as a boolean flag or something like that.

**Comment by caoccao** [comment]
Good question. Here are my thoughts for your reference.

## Annotations are for `bind()`

The annotations like `V8Function`, `V8Property` are for `V8ValueObject.bind()`. The converter shouldn't be from the proxy converter family. It is designed to cover the majority of use cases, but it surely doesn't cover all the edge cases.

## What should I do then?

As you've already found out, the recommended approach is to implement a proxy plugin. It comes with the following benefits.

* There is zero intrusion to the target class, especially if that class is from a 3rd party library where annotating it is impossible.
* Applications have full control over all the API signatures they want to expose.
* The underlying callback count is fixed. If you go with the `bind()`, the callback count is linear to the API count you want to expose. The huge number of callbacks impacts the performance considerably. But, with the proxy plugin, the performance overhead is fixed and subtle.

**Comment by caoccao** [comment]
By the way, an efficient way of returning `this` as a property is as follows.

```java
@V8Property(thisObjectRequired = true)
public V8ValueObject to(V8ValueObject thisObject) throws JavetException {
    return thisObject;
}
```

**Comment by colonelpopcorn** [comment]
Thank you for your response. I will go ahead with a custom proxy converter and comment back here when I have something working. Feel free to close this issue for now.
