### ISSUE TITLE
TypeError [ERR_NO_ICU]: "fatal" option is not supported on Node.js compiled without ICU

### ISSUE THREAD

**Issue by ms-novatti** [caoccao/Javet#393]
The following code fails with the error `TypeError [ERR_NO_ICU]: "fatal" option is not supported on Node.js compiled without ICU`:

    try (V8Runtime v8Runtime = V8Host.getNodeInstance().createV8Runtime()) {
        v8Runtime.getExecutor(
                "const web3 = require('@solana/web3.js');" +
                "console.log(web3);"
        )/*.setModule(true)*/.executeVoid();

    } catch (Exception e) {
        e.printStackTrace();
    }

I am using Javet version 3.1.7

I noticed that the error is handled differently depending on if calling setModule(true) or not.
When calling with setModule(true) I get a more useful stack trace, but the Java process exits.
Here is the more useful stack trace:

> node:internal/encoding:487
>           throw new ERR_NO_ICU('"fatal" option');
>                 ^
> 
> TypeError [ERR_NO_ICU]: "fatal" option is not supported on Node.js compiled without ICU
>     at new TextDecoder (node:internal/encoding:487:17)
>     at Object.<anonymous> (./node_modules/borsh/lib/index.js:37:21)
>     at Module._compile (node:internal/modules/cjs/loader:1469:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
>     at Module.load (node:internal/modules/cjs/loader:1288:32)
>     at Module._load (node:internal/modules/cjs/loader:1104:12)
>     at Module.require (node:internal/modules/cjs/loader:1311:19)
>     at require (node:internal/modules/helpers:179:18)
>     at Object.<anonymous> (./node_modules/@solana/web3.js/lib/index.cjs.js:8:13)
>     at Module._compile (node:internal/modules/cjs/loader:1469:14) {
>   code: 'ERR_NO_ICU'
> }
> 
> Node.js v20.17.0

The line in borsh/lib/index.js is as follows:
`const textDecoder = new ResolvedTextDecoder("utf-8", { fatal: true });`

I believe the Node that is compiled and included inside Javet needs to be compiled with the ICU included in order for this to work.

**Comment by caoccao** [comment]
Please check the following docs out for detail.

1. [Can i18n be Supported?](https://www.caoccao.com/Javet/faq/troubleshooting/can_i18n_be_supported.html)
2. [Unhandled Rejection](https://www.caoccao.com/Javet/reference/v8_values/v8_promise.html#unhandled-rejection)

**Comment by ms-novatti** [comment]
I have got the code to work by using a polyfill for the text decoder.

`npm install text-encoding`

    const {TextEncoder, TextDecoder} = require('text-encoding');
    global.TextEncoder = TextEncoder;
    global.TextDecoder = TextDecoder;

I hope this helps someone.

**Comment by caoccao** [comment]
i18n has been officially supported since v4.0.0.
