### ISSUE TITLE
About passing java objects to v8

### ISSUE THREAD

**Issue by qq511340079** [caoccao/Javet#395]
When executing js code multiple times in the same V8Runtime, each execution of js code will correspond to a java object instance, and the method of the java object will be called back in js. I use v8Runtime.getGlobalObject().set("JObj", this), which will cause the subsequent execution to overwrite the previously set JObj, resulting in the wrong java object being called. Maybe I am using it incorrectly.
Thanks for your answer.
java code: 
`V8ValueGlobalObject globalObject = v8Runtime.getGlobalObject();
            globalObject.set("Jcollision", collision);
            globalObject.set("JoutPath", outPath.getAbsolutePath());
            globalObject.set("JNodeDistanceScript", this);`

JS code: 
` JNodeDistanceScript.callback(result, screent);`

**Comment by caoccao** [comment]
It's recommended to `invoke` JS functions with Java objects as arguments instead of injecting the Java objects directly to the `globalThis`.

**Comment by qq511340079** [comment]
> It's recommended to `invoke` JS functions with Java objects as arguments instead of injecting the Java objects directly to the `globalThis`.

Can you provide a simple code reference? thanks.

**Comment by caoccao** [comment]
Please check [this](https://www.caoccao.com/Javet/reference/v8_values/v8_function.html#invoke) out.
