### ISSUE TITLE
Cannot import a file locally on the system [macOS, Node.js]

### ISSUE THREAD

**Issue by DeveloLongScript** [caoccao/Javet#397]
Hello! 👋  I've been trying to make a Bukkit plugin that imports a Node.js module and has interceptions to interact with the game, however I've ran into the issue of simply importing a module from the `package.json`.

```java
try (JavetEnginePool<NodeRuntime> javetEnginePool = new JavetEnginePool<NodeRuntime>()) {
  javetEnginePool.getConfig().setJSRuntimeType(JSRuntimeType.Node);
  try (IJavetEngine<NodeRuntime> iJavetEngine = javetEnginePool.getEngine()) {
    NodeRuntime nodeRuntime = iJavetEngine.getV8Runtime(); 
 
nodeRuntime.getNodeModule(NodeModuleModule.class).setRequireRootDirectory(Paths.get(JavetOSUtils.WORKING_DIRECTORY, "plugins/NodeScript/modules", module.getName()).toFile());
    // I have replaced the `.` with the actual main file specified in the `package.json`, yet it has not fixed it either.
    nodeRuntime.getExecutor("import Module from \".\";").setModule(true).executeVoid();
  }
}
```

There is an actual module exported at that location, yet it still returns this error:
```
Cannot find package: '.'
```

I have read the [Modularization guide](https://www.caoccao.com/Javet/reference/resource_management/modularization.html) yet nothing was a fix in that guide.
Thank you for your time.

**Comment by caoccao** [comment]
The module resolution is handled by Javet so that the `package.json` does't take effect. Please follow the doc to implement your own module resolver.

**Comment by DeveloLongScript** [comment]
I've also tried using the actual path of the document instead of a dot which did not fix the issue. I'll take a look at the module resolver again.

**Comment by DeveloLongScript** [comment]
V8 Resolvers can only make synthetic modules from Java code and cannot load modules directly from the filesystem like said in the Modularization guide.
Am I wrong or is there something I'm missing?

**Comment by caoccao** [comment]
V8 only implements the ECMA spec, nothing more. V8 doesn't even know file system or network. I guess the concept **load modules directly from the filesystem** comes from Node.js.

It's up to the V8 consumers to decide how to load modules, where to load modules. Node.js, Chrome, Javet are all V8 consumers. In Javet, choices are left with the downstream applications. So, you are going to implement whatever you want. Hope you can get some ideas from the doc. You don't have to create synthetic modules. `compileModule()` can serve it well.

**Comment by DeveloLongScript** [comment]
Ah, okay. So there is no import system, you have to load modules yourself.
Thanks for the help! ❤️

**Comment by caoccao** [comment]
Yes. Here are a few reasons for your reference.

1. Javet is built to be secure. Any built-in features with file system or network access will lead to security vulnerability.
2. The majority Javet users load modules from database, in-menory cache, etc.
