### ISSUE TITLE
[Feature Request] Custom Snapshots

### ISSUE THREAD

**Issue by SinfullySoul** [caoccao/Javet#399]
Request to allow to take custom snapshots of the v8 runtime though javet-core

**Comment by caoccao** [comment]
Sorry, I don't quite get what you are requesting. Could you be more specific?

**Comment by SinfullySoul** [comment]
what i mean by snapshot is save the entire state of the runtime (including global objects, functions, and variables) and reload it later. V8 engine supports creating custom snapshots that captures the state of the V8 heap and can be used to initialize a new V8 runtime with that saved state.

**Comment by caoccao** [comment]
I'm not sure if this [doc](https://www.caoccao.com/Javet/reference/resource_management/snapshot.html) works for you. Basically, you can run arbitrary scripts in arbitrary times before creating the snapshot in Javet V8 mode.

**Comment by SinfullySoul** [comment]
how did i miss that in doc o-well, this does help thanks & sorry for opening this issue
