### ISSUE TITLE
documentation issue concerning glibc

### ISSUE THREAD

**Issue by Enrice** [caoccao/Javet#401]
I think I found a glitch on
https://www.caoccao.com/Javet/tutorial/basic/installation.html

It seems unfeasible, that with javet 3.0.3+ we need a LOWER glibc version 2.29 than with 3.0.1 or 3.0.2.
Maybe that was a typo and glibc 2.39 was meant?

**Comment by caoccao** [comment]
Good question. It's not a typo. The glibc requirement was downgraded to v2.29 because Javet users like you reported this issue.
