### ISSUE TITLE
Crash after a few executions

### ISSUE THREAD

**Issue by Enrice** [caoccao/Javet#402]
We have a setup running smoothly under Windows but consistently crashing under Rocky Linux 9. We are using V8 mode only, latest Version 3.1.8 but also experiencing that with 3.0.2.

Final setup is running on a tomcat 8.5 running Java 8. We also tried parallel unit tests with surefire, both showing the same outcome. 

Any idea? I may provider further info if that helps.

**Comment by caoccao** [comment]
Usually, that's coding errors which cause memory leak and eventually bring down the app. A code review may help.

**Comment by Enrice** [comment]
actually Solution 2 in https://www.caoccao.com/Javet/faq/troubleshooting/sigsegv_at_createv8runtime_in_v8_mode_on_aws.html helped.
