### ISSUE TITLE
JavetBuddy is unable to generate bytecode

### ISSUE THREAD

**Issue by AsyncProxy** [caoccao/Javet#403]
1.Follow your example and write an anonymous class.

public class TestJava {

    public int add() {
        return 2;
    }
}
2. Initialize the proxy plugin.

javetProxyConverter.getConfig().setReflectionObjectFactory(JavetReflectionObjectFactory.getInstance());
IJavetAnonymous anonymous = new IJavetAnonymous() {
                @V8Function
                public void JavaAptder(TestJava testJava) throws Exception {
                    testJava.add();
                }
            };

JS: Java.JavaAptder({

    add() {
        return 1000;
    }
})

3.Error: failed with error message Attempt to invoke virtual method 'int com.editor.async.script.TestJava.add()' on a null object reference.

**Comment by caoccao** [comment]
Please follow the [doc](https://www.caoccao.com/Javet/reference/converters/proxy_converter.html#dynamic-anonymous-object-for-class) strictly and try again. The JS code should look like the following.

```js
{
  add: (a, b) => a + b,
}
```

**Comment by AsyncProxy** [comment]
> 请严格按照[文档](https://www.caoccao.com/Javet/reference/converters/proxy_converter.html#dynamic-anonymous-object-for-class)进行操作，然后重试。JS 代码应如下所示。
> 
> ```js
> {
>   add: (a, b) => a + b,
> }
> ```

Please ask me what I did wrong, give a reasonable explanation, I have done it strictly according to the example of the document.
![1](https://github.com/user-attachments/assets/ceced90a-05c2-454c-bad3-b7ccea407dc8)
![2](https://github.com/user-attachments/assets/9bd4c127-cb08-4e1d-842c-acb2d23de219)
![3](https://github.com/user-attachments/assets/ac0b87ec-f542-4d8e-8ea0-12272028f752)
![4](https://github.com/user-attachments/assets/c87f8e01-4c2e-4f94-9385-6edc56c199fc)
![5](https://github.com/user-attachments/assets/f0d2827b-4c08-49a3-878e-033345555a2d)

**Comment by AsyncProxy** [comment]
> 请严格按照[文档](https://www.caoccao.com/Javet/reference/converters/proxy_converter.html#dynamic-anonymous-object-for-class)进行操作，然后重试。JS 代码应如下所示。
> 
> ```js
> {
>   add: (a, b) => a + b,
> }
> ```

I tried java.io.File at the beginning, he reported an error with multiple constructors, which was thrown by ByteBuddy internally, and I later opened the DynamicObjectAutoCloseableInvocationHandler class from your source code to try to generate bytecode, but it didn't work, the same error was thrown, Android architecture.

**Comment by caoccao** [comment]
It only works for classes with default constructor. New features are not planned.

**Comment by AsyncProxy** [comment]
> 它仅适用于具有 default 构造函数的类。新功能未计划。

It's the same as the default constructor class, but it doesn't work, and I see from your anonymous implementation, it seems that you need to pass a class object instead of V8Object, when I pass a specified class object in the test function, he doesn't report an error, but the function is completely inconsistent.

**Comment by anonyein** [comment]
@AsyncProxy net.bytebuddy.ByteBuddy please check this! Maybe it cannot fit Android!

**Comment by caoccao** [comment]
Well, it seems [JavetBuddy](https://github.com/caoccao/JavetBuddy) needs to adapt to Android in the future.

**Comment by AsyncProxy** [comment]
> 好吧，看来 [JavetBuddy](https://github.com/caoccao/JavetBuddy) 将来需要适应 Android。

I've also used ByteBuddy before, it seems to be stuck in the getLoaded place, when I tried to generate class before, it can only work on generating empty shell classes, r8 compiles to dex loading, so I think ByteBuddy may not be compatible with android, but I don't know if there is any other way to quickly generate bytecode.
