### ISSUE TITLE
JVM Crashes with invalid TS Script

### ISSUE THREAD

**Issue by manuelwallrapp** [caoccao/Javet#415]
Hi 

I am using javet 4.0.0, with Java 21 on Mac Os 15.0.1. If I execute a valid Typescript everything works fine. But if I add invalid code to the Typescript, the executeVoid crashes the whole JVM process. 

I attached you a sample project with a Junit test:

https://github.com/manuelwallrapp/javet-jvm-crash-example

You can just run ./gradlew test. 

Best regards

Manu

**Comment by caoccao** [comment]
Thank you for reporting the issue. I took a glance at it, but couldn't identify the issue. I will test it late next week as I'm current traveling around far away without my dev box.

You may also ping me at discord and we might be able to resolve it early.

**Comment by manuelwallrapp** [comment]
Hi Sam

Thank you for your fast response. Yes we can do that. How can I find you on Discord? Otherwise late next week is also ok. 
What time Zone are you in? I am from Switzerland. 

Best.. Manu

**Comment by caoccao** [comment]
A URL to the Discord server is on the Javet home page. I'm in Shanghai which is 7 hours ahead.

**Comment by caoccao** [comment]
Please follow this [doc](https://www.caoccao.com/Javet/reference/v8_values/v8_promise.html#unhandled-rejection). After the following 3 lines are added, the test case will pass.

```diff
        try (V8Runtime v8Runtime = V8Host.getNodeInstance().createV8Runtime(nodeRuntimeOptions)) {
+            v8Runtime.getExecutor("process.on('unhandledRejection', (reason, promise) => {\n" +
+                    "    console.log('Unhandled Rejection at:', promise, 'reason:', reason);\n" +
+                    "});").executeVoid();
            v8Runtime.setV8ModuleResolver((runtime, resourceName, v8ModuleReferrer) -> {
```

The console log is as follows.

```txt
Unhandled Rejection at: Promise {
  <rejected> ReferenceError: sdfsdfsdf is not defined
      at ./estaTektonPipeline.ts:1:1
} reason: ReferenceError: sdfsdfsdf is not defined
    at ./estaTektonPipeline.ts:1:1
```
