### ISSUE TITLE
Error: Cannot find package 'xxxx'

### ISSUE THREAD

**Issue by silasol** [caoccao/Javet#419]
I created a node module called onescript and placed it in the node_modules folder, then called it using index.js.

index.js:
```javascript
import { greet } from 'onescript';

greet('world');

```

Java code :

```java
public class NodeModuleTest {
    public static void test(Context context) {
        try {
            NodeRuntime engine = V8Host.getNodeInstance().createV8Runtime();

            JavetStandardConsoleInterceptor console = new JavetStandardConsoleInterceptor(engine);
            console.register(engine.getGlobalObject());

            engine.getExecutor(new File(context.getFilesDir(), "node-project/index.js")).setModule(true).executeVoid();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

```

error message：

```text
com.caoccao.javet.exceptions.JavetExecutionException: Error: Cannot find package 'onescript'
at com.caoccao.javet.interop.V8Native.moduleExecute(Native Method)
at com.caoccao.javet.interop.V8Runtime.execute(V8Runtime.java:1067)
at com.caoccao.javet.interop.executors.V8StringExecutor.execute(V8StringExecutor.java:107)
at com.caoccao.javet.interop.IV8Executable.executeVoid(IV8Executable.java:192)
at ano.onescript.node.NodeModuleTest.test(NodeModuleTest.java:18)
```

I use node to execute index.js on the computer without any errors :
<img width="592" alt="image" src="https://github.com/user-attachments/assets/7cd90e4f-b286-4bd7-9a2a-f75e1895d195">

demo repo is here : https://github.com/silasol/NodeModuleDemo

**Comment by caoccao** [comment]
Please check this [doc](https://www.caoccao.com/Javet/reference/resource_management/modularization.html) out. You need to implement a module resolver to do the work.

**Comment by silasol** [comment]
In Node Mode, can't we specify the location of node_modules through setRequireRootDirectory or engine.getExecutor(file)?

In the example below about Node mode, I did not find any information about module resolver：
1. https://www.caoccao.com/Javet/reference/resource_management/modularization.html#example
2. https://www.caoccao.com/Javet/tutorial/advanced/interact_with_node_js.html#step-3-main-thread-for-the-interaction

Why do we still need  implement a module resolver  ？

**Comment by caoccao** [comment]
In the Node.js mode, CommonJS is handled by Node.js, but ESM is handled by Javet module resolver.

As your app relies on ESM, you are supposed to write your own module resolver. Please review that doc carefully. The module resolver is there.

**Comment by silasol** [comment]
Ok, thanks for your patience, I will re-read the docs carefully!
