### ISSUE TITLE
[docs] Javet Engine thread behavior in Java Virtual Thread environment

### ISSUE THREAD

**Issue by dopsun** [caoccao/Javet#420]
In this document, https://www.caoccao.com/Javet/development/design.html, it says:

> Javet Engine Pool
> Multiple Javet engines are managed by Javet Engine Pool which works almost the same way as a typical DB connection pool. Javet Engine Pool is thread-safe. However, Javet Engine is NOT thread-safe because it is designed to be single-threaded and lock free for the following reasons.

As now Java supports [Virtual Thread](https://openjdk.org/jeps/444) over OS thread. May worth of clarify Javet Engine's behavior in Java VT environment. (_I searched issues in this repositories, and cannot find discussions around "virtual thread", hence raise a new ticket for this_)

To me, the most critical point to clarify in document is: 

- whether Javet Engine is safe as far as it's running in single virtual thread?

I'm also interested to definitive answer to this question. I'm just started evaluating Javet for a project. By reading architecture with V8, I assume the answer could be no?

**Comment by caoccao** [comment]
Please check this [doc](https://www.caoccao.com/Javet/reference/resource_management/lock.html#coroutines-or-virtual-threads) out. It's in another section.

**Comment by dopsun** [comment]
Thanks @caoccao 

Let me quote the section from the link you shared and close this one.

> ### Coroutines or Virtual Threads
> Kotlin Coroutines and Java 21 Virtual Threads are incompatible with the V8 threading model. The V8 locking mechanism cannot handle the chaos from coroutines or virtual threads, because V8 sees the calls coming from the same OS thread and doesn't actually keep the calls in sequence. Calling Javet API in coroutines or virtual threads will result in the JVM crash, if an additional synchronization is absent.
