### ISSUE TITLE
V8Runtime toObject

### ISSUE THREAD

**Issue by AsyncProxy** [caoccao/Javet#421]
toObject is traversing the object of the reference loop structure, although there is a maximum depth set, but he will not output the traversal data when he detects it, but it does not work directly, can it improve the detection of the reference loop structure, it is detected and it is represented by a small piece of character, continue to traverse down, use the util module of the Node.js to do achieve one by yourself, but it is very troublesome, I still hope to improve it, and toObject is not allowed to be rewritten, only to change the depth.

**Comment by caoccao** [comment]
Please check this [doc](https://www.caoccao.com/Javet/reference/converters/index.html#circular-structure) out.
