### ISSUE TITLE
Warning message when using JavetJVMInterceptor

### ISSUE THREAD

**Issue by privateJiangyaokai** [caoccao/Javet#426]
`
  public static void runNode() throws JavetException {
    long start = System.currentTimeMillis();
    try (NodeRuntime nodeRuntime = V8Host.getNodeInstance().createV8Runtime()) {
      File workingDirectory = new File(JavetOSUtils.WORKING_DIRECTORY, "node_stuff");
      nodeRuntime.getNodeModule(NodeModuleModule.class).setRequireRootDirectory(workingDirectory);
      nodeRuntime.setConverter(javetProxyConverter);
      JavetJVMInterceptor javetJVMInterceptor = new JavetJVMInterceptor(nodeRuntime);
      javetJVMInterceptor.register(nodeRuntime.getGlobalObject());
      try (V8Locker v8Locker = nodeRuntime.getV8Locker()) {
        nodeRuntime.getExecutor("let context = javet.package.com.functorz.javenode.Main").execute();
        nodeRuntime.getExecutor("context.printA()").executeVoid();
      }
    }
    System.out.println(Thread.currentThread().getName() + ": Time taken: " + (System.currentTimeMillis() - start));
  }
  
  public static void printA() {
    System.out.println("a");
  }
`

When I run this code I end up with warnings like the following:
`Dec 14, 2024 2:11:26 AM com.caoccao.javet.utils.JavetDefaultLogger warn
WARNING: 38 V8 callback context object(s) not recycled.`
It looks like
javetJVMInterceptor.register(nodeRuntime.getGlobalObject()) adds 2 javetCallbackContexts
nodeRuntime.getExecutor("let context = javet.package.com.functorz.javenode.Main").execute() adds 34 javetCallbackContexts
nodeRuntime.getExecutor("context.printA()").executeVoid(); adds 1 javetCallbackContext
And then nothing removes them until the end in V8Runtime.close() -> V8Runtime.removeAllReferences() -> V8Runtime.removeCallbackContexts(), where we get a warning if callbackContextMap is not empty. 

Is this intended behavior? Is there something that I am failing to do? And is this warning something I should worry about?
Thanks so much! It is a great project. Contributed as [Momen.app](https://momen.app) to your [project](https://opencollective.com/purchase-macbook-pro-arm/contributions/815696). I hope it can be of help to you!

**Comment by caoccao** [comment]
Hi Yaokai,

Thank you very much for the donation!

The warning you get implies the app doesn't perform the [clean up](https://www.caoccao.com/Javet/tutorial/advanced/access_the_whole_jvm.html#cleanup). Please follow that tutorial as follows.

1. Set `context` to `undefined`. This is to tell V8 GC that `context` is no longer needed.
2. Unregister the `JavetJVMInterceptor`.
3. Call `v8Runtime.lowMemoryNotification()` to tell V8 GC to collect the garbage.

These steps should get rid of the warning. Please let me know if you have any questions.

**Comment by privateJiangyaokai** [comment]
Got it, thanks a lot! That worked. 
A slightly different issue.
```
    try (NodeRuntime nodeRuntime = V8Host.getNodeI18nInstance().createV8Runtime()) {
      File workingDirectory = new File(JavetOSUtils.WORKING_DIRECTORY, "node_stuff");
      nodeRuntime.getNodeModule(NodeModuleModule.class).setRequireRootDirectory(workingDirectory);
      V8Script compileV8Script = nodeRuntime.getExecutor(Path.of(workingDirectory.getAbsolutePath(), "index.js"))
          .compileV8Script();
      compiledScript = compileV8Script.getCachedData();
      nodeRuntime.lowMemoryNotification();
      nodeRuntime.await();
      System.gc();
      System.runFinalization();
    }
```
I have this to pre-compile some code, and I always end up with 
WARNING: 1 V8 object(s) not recycled, 0 weak, 0 module(s).
inside index.js, there is just 
```
const cryptojs = require('crypto-js');
console.log(cryptojs.MD5('hello, world').toString());
```

**Comment by caoccao** [comment]
Please check this [doc](https://www.caoccao.com/Javet/reference/tips/best_practices.html) out.

> Always apply `try-with-resource` to Javet objects regardless of primitive or reference if they are not returned to Javet.

In your case, `compileV8Script` needs to be closed properly as follows. And, you don't need to call `await()`, `gc()`, `lowMemoryNotification()`.

```java
try (NodeRuntime nodeRuntime = V8Host.getNodeI18nInstance().createV8Runtime()) {
    File workingDirectory = new File(JavetOSUtils.WORKING_DIRECTORY, "node_stuff");
    try (V8Script compileV8Script = nodeRuntime.getExecutor(Path.of(workingDirectory.getAbsolutePath(), "index.js"))
        .compileV8Script()) {
        compiledScript = compileV8Script.getCachedData();
    }
}
```

**Comment by privateJiangyaokai** [comment]
thanks

**Comment by privateJiangyaokai** [comment]
thanks
