### ISSUE TITLE
Java Interop without Interception

### ISSUE THREAD

**Issue by Vshnv** [caoccao/Javet#43]
**Description:** Javet seems to not be able to directly interact with Java classes without "intercaption" which seems to not be an option since the classes provided do not entirely belong to the project itself. 

**Question:** Could you guide us to any way we could potentially work around this to have it use reflection?

Thank you.

**Comment by caoccao** [comment]
I guess I haven't completely got what you wanted to achieve. Are you trying to get rid of `@V8Property` and `@V8Function` to set up interception fully based on convention? E.g. All getters/setters map to V8 properties, the rest of public functions map to V8 functions?

Yes, Javet is open to that. Please review the source code `bind()` in [V8ValueObject](https://github.com/caoccao/Javet/blob/main/src/main/java/com/caoccao/javet/values/reference/V8ValueObject.java). It internally calls `bindProperty()` and `bindFunction()` which are both publicly accessible. So, you may create your own version of `bind()` using reflection.

Why doesn't Javet provide this capability? I intended to deliver minimal surprise to users by providing declarative coding experience, which led to `@V8Property` and `@V8Function`. Reflection may expose unexpected API to V8, bringing potential security vulnerability, and that cannot be easily revoked. `@V8Property` and `@V8Function` give the full control over to users without surprise.

Hope that helps. And please let me know if you have any questions.

**Comment by Vshnv** [comment]
Alright, Thanks for the quick reply. Ill try implementing a reflective BaseJavetInterceptor.

> I guess I haven't completely got what you wanted to achieve. Are you trying to get rid of @V8Property and @V8Function to set up interception fully based on convention? E.g. All getters/setters map to V8 properties, the rest of public functions map to V8 functions?

Yes, the issue is that a lot of the classes derive from an external dependency. While making a wrapper class may work if for a few classes, to have it work without breaking previous compatibility, we would need to make wrapper classes for a lot of objects that could be returned from each other. Thus it would be much easier for us with reflectively providing the class.

Anyway, Thanks a lot for the info.

**Comment by caoccao** [comment]
I see. You are not alone. Other uses raised a few similar use cases. This [tutorial](https://github.com/caoccao/Javet/blob/main/docs/tutorial/object_converter.rst) about creating a POJO converter based on reflection may help you quickly create that feature.

**Comment by Vshnv** [comment]
Ah, So I should be using JavetObjectConverter, correct?

**Comment by caoccao** [comment]
> Ah, So I should be using JavetObjectConverter, correct?

If you don't need interception, yes, the object converter is the one. It works so well that you just don't feel its existence.

**Comment by Vshnv** [comment]
Oh, I see. I appreciate your help.
