### ISSUE TITLE
Javet cant handle Unicode character class escapes

### ISSUE THREAD

**Issue by crjobson** [caoccao/Javet#433]
Hi, I am finding that Javet cant handle a regex like:

`/(^(?:[$_\p{ID_Start}][$_\p{ID_Continue}]*\.)*[\p{ID_Start}][$_\p{ID_Continue}]*)\.bind\(([$_\p{ID_Start}][$_\p{ID_Continue}]*)\)$/u`

We get an error like:

`SyntaxError: Invalid regular expression: /(^(?:[$_\p{ID_Start}][$_\p{ID_Continue}]*\.)*[\p{ID_Start}][$_\p{ID_Continue}]*)\.bind\(([$_\p{ID_Start}][$_\p{ID_Continue}]*)\)$/u: Invalid property name in character class`

Digging further it seems Javet doesn't like the p{XXX} syntax at all, although this has been supported for a while in Chrome (and underlying V8).  Is there some setting somewhere needed to enable this?

This regex capability is described here:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Unicode_character_class_escape

According to this web page, this feature has been supported since Chrome 64 (V8 6.4) so I am surprised it is not working in Javet, but I could have missed something.

**Comment by caoccao** [comment]
Please check this [doc](https://www.caoccao.com/Javet/tutorial/advanced/internationalization_i18n.html) out.

**Comment by crjobson** [comment]
Thanks so much for the response!  I wondered if this was the case,  I also (after I created the issue, which is my bad) discovered that this has been mentioned in the discord channel.  I should have read the discord first before raising the issue, and apologise for being so trigger happy.  I'll dig into the process of I18N support but for now maybe I can work around this issue without the need for it.

BTW: Javet is great ...

**Comment by caoccao** [comment]
Thank you. And, yes, discord channels are golden mines. You've got it. It's up to you to decide when to close this issue, I suppose.

**Comment by crjobson** [comment]
I should have read the docs first (and/or the discord channel).  For now I'll work around the issue and if necessary look into I18N builds ...
