### ISSUE TITLE
Javet requires gcc installation on linux, but works fine on windows

### ISSUE THREAD

**Issue by Vshnv** [caoccao/Javet#48]
**Stack-trace from Linux:** https://paste.helpch.at/emikeyuhug.md

**Question:**
The native libraries seem to be loading fine on windows , but it seems to require gcc 6 to be installed for it to work on linux. Is this intended or some bug? 

If this is intentional, is there anyway to package the required libraries along with the jar?

**Additional Request:**
Could you open your DMs on twitter so we could communicate better? 

Thank you.

**Comment by caoccao** [comment]
This is a known issue. Please refer to [installation](https://github.com/caoccao/Javet/blob/main/docs/tutorial/installation.rst) or [What's Wrong with GLIBCXX_3.4.26?](https://github.com/caoccao/Javet/discussions/26) for detail.

**Comment by Vshnv** [comment]
Could the library possibly be statically linked?

**Comment by caoccao** [comment]
> Could the library possibly be statically linked?

I don't think so, as that implies embedding Linux itself.
