### ISSUE TITLE
Can not run script from root

### ISSUE THREAD

**Issue by hajekj14** [caoccao/Javet#62]
Not working:

```bash
root
├── node_modules
└── main.js
```

Working:

```bash
root
├── node_modules
└──main
   └── main.js
```

Is possible to make working both?

btw. thx for awesome lib ;-)

**Comment by caoccao** [comment]
This is a tricky thing related to how Node.js locates `node_modules`.

Please check this [commit](https://github.com/caoccao/Javet/commit/94cf49e678b85f95f95e1644453ce5c94ef02dd9) out for the workaround which is really simple.

Let's assume the file structure is as following.
```
root
├── node_modules
└── main.js
```

All what you need to do are:

1. Create a dummy directory under root. E.g. `root/dummy`.
2. Create a `File` or `Path` with double dots `..`. E.g. `root/dummy/../main.js`.

That works as this [commit](https://github.com/caoccao/Javet/commit/94cf49e678b85f95f95e1644453ce5c94ef02dd9) shows. Hope that's what you are looking for. Please let me know if you have any questions.
