### ISSUE TITLE
Static methods with JavetProxyConverter

### ISSUE THREAD

**Issue by Cormanz** [caoccao/Javet#64]
Hi! So I was doing some testing with `JavetProxyConverter`, and encountered the following problem:

If I have an instance of a class, say `Class<my.pkg.StaticClass>`, I can't access its static methods. There are a lot of libraries in Java which use classes with static methods.

Could `JavetProxyConverter` proxy static methods of `Class` instances?

**Comment by caoccao** [comment]
It's supported in v0.9.6, however I forgot to add test case validating that. Here's the [test case](https://github.com/caoccao/Javet/commit/72d4466fc1145990bc1dffed295f901b9332c811). Do you mind leaving your code for troubleshooting?

**Comment by Cormanz** [comment]
> It's supported in v0.9.6, however I forgot to add test case validating that. Here's the [test case](https://github.com/caoccao/Javet/commit/72d4466fc1145990bc1dffed295f901b9332c811). Do you mind leaving your code for troubleshooting?

Huh, that's weird. Whenever we tried accessing methods from a static class, it didn't work.

Java:
```java
this.v8Runtime.getGlobalObject().set("Bukkit", Bukkit.class);
```
V8:
```java
Bukkit.broadcastMessage("pineapple");
```

This gives `TypeError: Bukkit.broadcastMessage is not a function`.

**Comment by caoccao** [comment]
I see. That's not in the scope of v0.9.6. I think it can be implemented with a little tweak to `JavetProxyConverter`.

**Comment by Cormanz** [comment]
> I see. That's not in the scope of v0.9.6. I think it can be implemented with a little tweak to `JavetProxyConverter`. In v0.9.6, you have to inject an instance though you only want to call static functions.

Yeah makes sense, but I don't *only* want to call static functions, I want to be able to do both.
Appreciated that you're adding this functionality, that'll help a ton!

**Comment by caoccao** [comment]
If you want to do both, that's nice. Just call `.set("Bukkit", new Bukkit())` and it will work.

**Comment by Cormanz** [comment]
> If you want to do both, that's nice. Just call `.set("Bukkit", new Bukkit())` and it will work.

Oh I mean I want to be able to access both static methods of classes (from Bukkit.class), and regular methods from instances (like Server), since both patterns are commonly used in what I'm using

**Comment by caoccao** [comment]
I see. I'll implement that in next release.

**Comment by MrEnxo** [comment]
when will that be?

**Comment by caoccao** [comment]
It's included in this [commit](https://github.com/caoccao/Javet/commit/848c4354875202f313e042d74dec69d84ab6bae6). Please let me know if you have any questions.

**Comment by Cormanz** [comment]
Nope, LGTM. Thanks for implementing!

**Comment by caoccao** [comment]
I just found it didn't support `public static` fields and `public` fields. This [commit](https://github.com/caoccao/Javet/commit/a73b475926bf5604816a23beaa5a3aa507ac3838) fills the gap.
