### ISSUE TITLE
Suggestion: Github actions to make dev Builds

### ISSUE THREAD

**Issue by MrEnxo** [caoccao/Javet#67]
Its a simple as the title, Probs not as simple to make but it might work. Making github actions to build the dev branch each commit would be nice so if we wanted a feature that you have made but not released it. this way we can obtain a jar easily and use it in our projects

**Comment by caoccao** [comment]
The idea is good.

However, the challenge is Javet heavily relies on JNI libraries. Any JNI interface mismatches would prevent Javet from being initialized.

Preparing the build environment takes huge effort as it involves building Node.js and V8 from source code.

Anyway, I'll give it a try in the future.

**Comment by MrEnxo** [comment]
> Any JNI interface mismatches would prevent Javet from being initialized.

what do you mean by JNI interface mismatch, like how does that happen?

**Comment by orvit-png** [comment]
Looking for a friend, would 0.9.6 JNI work with 0.9.7

**Comment by caoccao** [comment]
> what do you mean by JNI interface mismatch, like how does that happen?

JVM is a C++ library and Javet is also a C++ library. When JVM tries to load Javet, if these two libraries are not binary compatible, JVM will crash. It's pretty much C++ stuff.

**Comment by MrEnxo** [comment]
can u make a release for use me, @orvit-png  and @Cormanz are trying to make a project and we need the new features in 0.9.7 lol

**Comment by caoccao** [comment]
> Looking for a friend, would 0.9.6 JNI work with 0.9.7
> 
> Edit: it turns out the only friend I needed was myself :(

That depends on whether there are changes to the JNI or not. Sometimes, they are compatible. One of the reasons that Javet C++ libraries are versioned is the binary incompatibility can be avoided.

**Comment by orvit-png** [comment]
Have any of the changes regarding 0.9.7 come out to affect the JNI? My build continues to fail so I don't know what to do.

**Comment by caoccao** [comment]
> can u make a release for use me, @orvit-png and @Cormanz are trying to make a project and we need the new features in 0.9.7 lol

Please visit [gitter](https://gitter.im/caoccao/Javet?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) to contact me for detail.
