### ISSUE TITLE
0.9.7 Test Build Issue

### ISSUE THREAD

**Issue by MrEnxo** [caoccao/Javet#68]
```java
this.runtime.getGlobalObject().set("Class",  Class.class);
```

```js
const Bukkit = Class.forName("org.bukkit.Bukkit")
const Materials = Class.forName("org.bukkit.Material")

let test = Materials.ACACIA_BUTTON

console.log(test)

```
On the Js Console.log(test) responds with "com.caoccao.javet.values.reference.V8ValueProxy" which im pretty sure is not supposed to happend but if I do .ToString() it responds with the actual name of the enum. This happens with any other value if you try to console.log it

**Comment by caoccao** [comment]
Yeah, that's a workaround I created today. Let me remove it.

**Comment by MrEnxo** [comment]
alright!

**Comment by caoccao** [comment]
Done. Please download again.

**Comment by MrEnxo** [comment]
on the Google Drive?

**Comment by MrEnxo** [comment]
I got it working, Thanks!
