### ISSUE TITLE
Passing a Function into a Java Class

### ISSUE THREAD

**Issue by MrEnxo** [caoccao/Javet#73]
When you pass a Function into a normal Java Class you don't get the V8ValueFunction you get the Function Entity but that can't be turned into a V8ValueFunction. 
This is quite an Annoying Issue because I have to turn all my Java Classes into V8ValueObjects with import statements and make work-arounds for the V8ValueFunction.

**Comment by caoccao** [comment]
That was a decision I made when designing proxy based injection. I thought proxy based injection should only be applied to regular Java objects that don't know Javet at all. In your case, if your Java objects know Javet, please use the standard way to avoid double conversions.

**Comment by MrEnxo** [comment]
> 
> 
> That was a decision I made when designing proxy based injection. I thought proxy based injection should only be applied to regular Java objects that don't know Javet at all. In your case, if your Java objects know Javet, please use the standard way to avoid double conversions.

how about add like a options system into the proxy so we can choose for our application

**Comment by caoccao** [comment]
> how about add like a options system into the proxy so we can choose for our application

I'll find a simple solution.

**Comment by MrEnxo** [comment]
any solution for this?

**Comment by caoccao** [comment]
> any solution for this?

It is possible, but requires considerable coding effort and careful design. I'll spend sometime on it later.

**Comment by caoccao** [comment]
This is enabled by this [commit](https://github.com/caoccao/Javet/commit/4593b211d02647f89862da4b8d0eab87bda19396). You are welcome taking a try.
