### ISSUE TITLE
JavetProxyConverter: Interfaces

### ISSUE THREAD

**Issue by Cormanz** [caoccao/Javet#74]
Hello! In java, interfaces are represented by `java.lang.Class` via reflection, and you can check if its an interface via `type.isInterface()`. I'm suggesting we allow for the conversion of interfaces in Java reflection  to V8 via JavetProxyConverter

```ts
const interface = Class.forName('my.java.Interface');
```

There is a few benefits to this.
- Check if another proxied object is an instance of this java interface.
- Creating instances of this interfaces via proxies.

There may be others but I haven't thought of them. Thanks!

**Comment by caoccao** [comment]
That has been implemented by this [commit](https://github.com/caoccao/Javet/commit/e3c3cda7aeea863a9ddac19c4e6549f3cce8c321). Please let me know if you have any questions.

**Comment by Cormanz** [comment]
> That has been implemented by this [commit](https://github.com/caoccao/Javet/commit/e3c3cda7aeea863a9ddac19c4e6549f3cce8c321). Please let me know if you have any questions.

I do have one, how would we check if a proxied java object is an instance of a proxied java interface/class?

**Comment by caoccao** [comment]
> I do have one, how would we check if a proxied java object is an instance of a proxied java interface/class?

In Java, you can call `Class.isAssignableFrom(...)` or `Class.isInstance(...)`. So, in JavaScript you can do that as well. There are many API available. And you may create your own interceptors that leverage the Java bindings to almost any purpose.

**Comment by Cormanz** [comment]
Oh, very much appreciated to answer that, thanks!

**Comment by caoccao** [comment]
Implementing interface in JS is enabled by this [commit](https://github.com/caoccao/Javet/commit/09059b7507bb0d3852c48581938d119008d58e0f).
