### ISSUE TITLE
JavetProxyConverter: "new" on proxied static classes

### ISSUE THREAD

**Issue by Cormanz** [caoccao/Javet#75]
Hello! So let's take a class like for example, `java.lang.Thread` (just as an example)

```ts
const Thread = Class.forName('java.lang.Thread');
```

If I want to initialize an instance of this class via JS, I should be able to do something like `new Thread(() => console.log('Hi!'))`, but you can't because this isn't supported.

The desired output would be a proxied instance of `Thread` that we can interact with. The example of passing in a JS function as an argument is based on the expected behaviour that these functions will be converted to whatever the functional interface needed is

Thanks!

**Comment by MrEnxo** [comment]
a way of initializing classes built into V8 would be nice.

**Comment by caoccao** [comment]
I think `new Object()` is fine. However, creating an instance of an interface places a new level of technical challenge. I'll investigate that.

Interesting and intuitive feature. 👍

**Comment by Cormanz** [comment]
> I think `new Object()` is fine. However, creating an instance of an interface places a new level of technical challenge. I'll investigate that.
> 
> Interesting and intuitive feature. 👍

It is actually very possible using Java proxies, which I suggest you read about for covering this problem.

**Comment by caoccao** [comment]
> It is actually very possible using Java proxies, which I suggest you read about for covering this problem.

It's beyond that. Java proxy is a subtle issue here. It may leak memory in one thread, may core dump among threads.

**Comment by caoccao** [comment]
Creating an instance by `new ClassName(...)` has been commit to dev branch via [5eed567](https://github.com/caoccao/Javet/commit/5eed567274ca5ffc9cadda59a71d559430c168f8), [b9ec19b](https://github.com/caoccao/Javet/commit/b9ec19b29d95ca6757ee26dff728bb66da1535cf), [5dbcfa0](https://github.com/caoccao/Javet/commit/5dbcfa05d434772aaf66a595852bb82398ac1ab8).

**Comment by Cormanz** [comment]
> > It is actually very possible using Java proxies, which I suggest you read about for covering this problem.
> 
> It's beyond that. Java proxy is a subtle issue here. It may leak memory in one thread, may core dump among threads.

Oh, that's information I was not aware of.

**Comment by caoccao** [comment]
Implementing interface in JS is enabled by this [commit](https://github.com/caoccao/Javet/commit/09059b7507bb0d3852c48581938d119008d58e0f).
