### ISSUE TITLE
Can javet be used in Android system?

### ISSUE THREAD

**Issue by farendaibiao** [caoccao/Javet#79]
As J2V8, can javet be used in Android system?
lib, the .so file, can be found.

**Comment by caoccao** [comment]
I think in the future, it's possible because a group of developers told me they would look into supporting Android.

Interestingly, today, I just added support to Mac OS x86_64 at dev branch.

**Comment by farendaibiao** [comment]
> I think in the future, it's possible because a group of developers told me they would look into supporting Android.
> 
> Interestingly, today, I just added support to Mac OS x86_64 at dev branch.

All right, I test the Gradle code, and only the lib cannot be found, maybe armv8 not exist

**Comment by caoccao** [comment]
It's quite hard to build Javet successfully. If you really want to do so, I suggest you start with the docker build which was added to main branch yesterday.

**Comment by farendaibiao** [comment]
> It's quite hard to build Javet successfully. If you really want to do so, I suggest you start with the docker build which was added to main branch yesterday.

Thank you for your advice!
