### ISSUE TITLE
V8 flag support for --max-old-space-size

### ISSUE THREAD

**Issue by robertlazarski** [caoccao/Javet#90]
We attempted to migrate off of J2V8 and all seemed well. We just use the V8 support on Ubuntu 20.04.2 LTS - not the Node support. The coding was relatively simple to migrate and testing passed QA. 

However in our production systems with 32GB of memory we run some big jobs that repeatably hit V8 very hard. As soon as we started running Javet on these jobs that crashed our Wildfly 20 server that runs the Javet code and the rest of our code in a webapp.  

I suspect the lack of --max-old-space-size, that we used with J2V8. Namely --max-old-space-size=2048 via V8.setFlags("--max-old-space-size=2048");

Looking at the source of the V8Host class method setFlags() , max-old-space-size is not supported. So we skipped it, but that didn't seem to pan out in our big production jobs.

**Comment by caoccao** [comment]
Understood. I'll update Javet to open arbitrary flags. I didn't do so because I was wondering whether developers know how to well tune V8 or not. You feedback gives me confident in trusting Javet users doing the right thing.

**Comment by caoccao** [comment]
That feature was pushed to dev branch in this [commit](https://github.com/caoccao/Javet/commit/4b23710684763cde2178b77e7773720edf16098d). I plan to release the next version on Sep 27, 2021. Before then, you may try the linux build at https://github.com/caoccao/Javet/actions.

Please let me know if it works and wish you a successful migration.

**Comment by robertlazarski** [comment]
Hello, thank you for the quick turn around. 

I tested the latest artifact in the Github actions of the Javet project on our non-production servers today with 32GB of memory under heavy load with 50% assigned to the JVM. 

The server is still crashing. For each crash there is a hs_err_*.log file created. The error is happening in the close() code, which I am using like release() from J2V8. Maybe that is incorrect coding, not sure. 

I am going to create another issue as I am unclear if the server crash is really related to the --max-old-space-size arg that seems implemented now - but rather a memory access issue in the native C++ code.

**Comment by caoccao** [comment]
Sure, please refer to #93 for detail.
