### ISSUE TITLE
NodeJs support

### ISSUE THREAD

**Issue by mrinalsharma** [caoccao/Javet#97]
Can Javet  be used in java program to Run nodejs modules ? Which version of nodejs is supported?

How long you are planning to maintain this project?

**Comment by caoccao** [comment]
> Can Javet  be used in java program to Run nodejs modules ? Which version of nodejs is supported?

Yes. The tutorial could be a good start for you.

v0.x.x supports Node.js v14. v1.x.x (to be released in 1 week) supports Node.js v16.

> How long you are planning to maintain this project?

I think, many years. Healthy sponsorship may be the cure.

**Comment by mrinalsharma** [comment]
Thank you for replying, your answers would help more Nieve people like me.

Is it possible to call a java object method from node imodule. The usecase would be, from java load node runtime and execute a JavaScript class method. Then from the JavaScript class method call back to java object method.

**Comment by caoccao** [comment]
> Thank you for replying, your answers would help more Nieve people like me.
> 
> Is it possible to call a java object method from node imodule. The usecase would be, from java load node runtime and execute a JavaScript class method. Then from the JavaScript class method call back to java object method.

Yes, Javet provides complete bi-directional interop between Java and JavaScript.
